/*
BSG SMS Gateway API

Comprehensive API for sending SMS, Viber messages, HLR/MNP requests and service management

API version: 1.0.0
Contact: support@bsg.world
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapiv1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SmsMassStatusRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SmsMassStatusRequest{}

// SmsMassStatusRequest Request to check status for multiple SMS messages by their IDs
type SmsMassStatusRequest struct {
	// Array of message IDs to check status for
	Ids []int32 `json:"ids"`
}

type _SmsMassStatusRequest SmsMassStatusRequest

// NewSmsMassStatusRequest instantiates a new SmsMassStatusRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSmsMassStatusRequest(ids []int32) *SmsMassStatusRequest {
	this := SmsMassStatusRequest{}
	this.Ids = ids
	return &this
}

// NewSmsMassStatusRequestWithDefaults instantiates a new SmsMassStatusRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSmsMassStatusRequestWithDefaults() *SmsMassStatusRequest {
	this := SmsMassStatusRequest{}
	return &this
}

// GetIds returns the Ids field value
func (o *SmsMassStatusRequest) GetIds() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value
// and a boolean to check if the value has been set.
func (o *SmsMassStatusRequest) GetIdsOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ids, true
}

// SetIds sets field value
func (o *SmsMassStatusRequest) SetIds(v []int32) {
	o.Ids = v
}

func (o SmsMassStatusRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SmsMassStatusRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ids"] = o.Ids
	return toSerialize, nil
}

func (o *SmsMassStatusRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSmsMassStatusRequest := _SmsMassStatusRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSmsMassStatusRequest)

	if err != nil {
		return err
	}

	*o = SmsMassStatusRequest(varSmsMassStatusRequest)

	return err
}

type NullableSmsMassStatusRequest struct {
	value *SmsMassStatusRequest
	isSet bool
}

func (v NullableSmsMassStatusRequest) Get() *SmsMassStatusRequest {
	return v.value
}

func (v *NullableSmsMassStatusRequest) Set(val *SmsMassStatusRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSmsMassStatusRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSmsMassStatusRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmsMassStatusRequest(val *SmsMassStatusRequest) *NullableSmsMassStatusRequest {
	return &NullableSmsMassStatusRequest{value: val, isSet: true}
}

func (v NullableSmsMassStatusRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmsMassStatusRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


