/*
BSG SMS Gateway API

Comprehensive API for sending SMS, Viber messages, HLR/MNP requests and service management

API version: 1.0.0
Contact: support@bsg.world
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapiv1

import (
	"encoding/json"
	"time"
)

// checks if the ExportCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExportCreateRequest{}

// ExportCreateRequest Request to create data export. Provide either message_id array OR filter parameters (not both). Upload data is stored on the server for one month from the creation date. One client can only have 2 active exports on the server. To create a new one, a previous export must be deleted. A parameter with empty string value equals an unspecified parameter.
type ExportCreateRequest struct {
	// Array of message IDs to export. If provided, ALL other parameters must be empty.
	MessageId []int32 `json:"message_id,omitempty"`
	// Phone numbers in international format to filter by
	Msisdn []string `json:"msisdn,omitempty"`
	// Filter by sender/originator name
	Originator *string `json:"originator,omitempty"`
	// Filter by message source type (e.g. api, smpp). Empty string = not specified.
	SourceType *string `json:"source_type,omitempty"`
	// Filter by message type
	MessageType *string `json:"message_type,omitempty"`
	// Start of message received date range (ISO 8601 format)
	TimeInFrom *time.Time `json:"time_in_from,omitempty"`
	// End of message received date range (must be >= time_in_from)
	TimeInTo *time.Time `json:"time_in_to,omitempty"`
	// Start of message sent date range (ISO 8601 format)
	TimeSentFrom *time.Time `json:"time_sent_from,omitempty"`
	// End of message sent date range (must be >= time_sent_from)
	TimeSentTo *time.Time `json:"time_sent_to,omitempty"`
	// ISO 3166-1 alpha-2 country code (exactly 2 characters)
	CountryId *string `json:"country_id,omitempty" validate:"regexp=^[A-Z]{2}$"`
	// Short link clicks filter value. Empty string = not specified.
	SlClicks *string `json:"sl_clicks,omitempty"`
	// Clicks comparison operator (>, <, =, >=, <=). Empty string = not specified.
	SlClicksComp *string `json:"sl_clicks_comp,omitempty"`
	// Clicks count comparison value. Empty string = not specified.
	SlClicksCount *string `json:"sl_clicks_count,omitempty"`
}

// NewExportCreateRequest instantiates a new ExportCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExportCreateRequest() *ExportCreateRequest {
	this := ExportCreateRequest{}
	return &this
}

// NewExportCreateRequestWithDefaults instantiates a new ExportCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExportCreateRequestWithDefaults() *ExportCreateRequest {
	this := ExportCreateRequest{}
	return &this
}

// GetMessageId returns the MessageId field value if set, zero value otherwise.
func (o *ExportCreateRequest) GetMessageId() []int32 {
	if o == nil || IsNil(o.MessageId) {
		var ret []int32
		return ret
	}
	return o.MessageId
}

// GetMessageIdOk returns a tuple with the MessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportCreateRequest) GetMessageIdOk() ([]int32, bool) {
	if o == nil || IsNil(o.MessageId) {
		return nil, false
	}
	return o.MessageId, true
}

// HasMessageId returns a boolean if a field has been set.
func (o *ExportCreateRequest) HasMessageId() bool {
	if o != nil && !IsNil(o.MessageId) {
		return true
	}

	return false
}

// SetMessageId gets a reference to the given []int32 and assigns it to the MessageId field.
func (o *ExportCreateRequest) SetMessageId(v []int32) {
	o.MessageId = v
}

// GetMsisdn returns the Msisdn field value if set, zero value otherwise.
func (o *ExportCreateRequest) GetMsisdn() []string {
	if o == nil || IsNil(o.Msisdn) {
		var ret []string
		return ret
	}
	return o.Msisdn
}

// GetMsisdnOk returns a tuple with the Msisdn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportCreateRequest) GetMsisdnOk() ([]string, bool) {
	if o == nil || IsNil(o.Msisdn) {
		return nil, false
	}
	return o.Msisdn, true
}

// HasMsisdn returns a boolean if a field has been set.
func (o *ExportCreateRequest) HasMsisdn() bool {
	if o != nil && !IsNil(o.Msisdn) {
		return true
	}

	return false
}

// SetMsisdn gets a reference to the given []string and assigns it to the Msisdn field.
func (o *ExportCreateRequest) SetMsisdn(v []string) {
	o.Msisdn = v
}

// GetOriginator returns the Originator field value if set, zero value otherwise.
func (o *ExportCreateRequest) GetOriginator() string {
	if o == nil || IsNil(o.Originator) {
		var ret string
		return ret
	}
	return *o.Originator
}

// GetOriginatorOk returns a tuple with the Originator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportCreateRequest) GetOriginatorOk() (*string, bool) {
	if o == nil || IsNil(o.Originator) {
		return nil, false
	}
	return o.Originator, true
}

// HasOriginator returns a boolean if a field has been set.
func (o *ExportCreateRequest) HasOriginator() bool {
	if o != nil && !IsNil(o.Originator) {
		return true
	}

	return false
}

// SetOriginator gets a reference to the given string and assigns it to the Originator field.
func (o *ExportCreateRequest) SetOriginator(v string) {
	o.Originator = &v
}

// GetSourceType returns the SourceType field value if set, zero value otherwise.
func (o *ExportCreateRequest) GetSourceType() string {
	if o == nil || IsNil(o.SourceType) {
		var ret string
		return ret
	}
	return *o.SourceType
}

// GetSourceTypeOk returns a tuple with the SourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportCreateRequest) GetSourceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.SourceType) {
		return nil, false
	}
	return o.SourceType, true
}

// HasSourceType returns a boolean if a field has been set.
func (o *ExportCreateRequest) HasSourceType() bool {
	if o != nil && !IsNil(o.SourceType) {
		return true
	}

	return false
}

// SetSourceType gets a reference to the given string and assigns it to the SourceType field.
func (o *ExportCreateRequest) SetSourceType(v string) {
	o.SourceType = &v
}

// GetMessageType returns the MessageType field value if set, zero value otherwise.
func (o *ExportCreateRequest) GetMessageType() string {
	if o == nil || IsNil(o.MessageType) {
		var ret string
		return ret
	}
	return *o.MessageType
}

// GetMessageTypeOk returns a tuple with the MessageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportCreateRequest) GetMessageTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MessageType) {
		return nil, false
	}
	return o.MessageType, true
}

// HasMessageType returns a boolean if a field has been set.
func (o *ExportCreateRequest) HasMessageType() bool {
	if o != nil && !IsNil(o.MessageType) {
		return true
	}

	return false
}

// SetMessageType gets a reference to the given string and assigns it to the MessageType field.
func (o *ExportCreateRequest) SetMessageType(v string) {
	o.MessageType = &v
}

// GetTimeInFrom returns the TimeInFrom field value if set, zero value otherwise.
func (o *ExportCreateRequest) GetTimeInFrom() time.Time {
	if o == nil || IsNil(o.TimeInFrom) {
		var ret time.Time
		return ret
	}
	return *o.TimeInFrom
}

// GetTimeInFromOk returns a tuple with the TimeInFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportCreateRequest) GetTimeInFromOk() (*time.Time, bool) {
	if o == nil || IsNil(o.TimeInFrom) {
		return nil, false
	}
	return o.TimeInFrom, true
}

// HasTimeInFrom returns a boolean if a field has been set.
func (o *ExportCreateRequest) HasTimeInFrom() bool {
	if o != nil && !IsNil(o.TimeInFrom) {
		return true
	}

	return false
}

// SetTimeInFrom gets a reference to the given time.Time and assigns it to the TimeInFrom field.
func (o *ExportCreateRequest) SetTimeInFrom(v time.Time) {
	o.TimeInFrom = &v
}

// GetTimeInTo returns the TimeInTo field value if set, zero value otherwise.
func (o *ExportCreateRequest) GetTimeInTo() time.Time {
	if o == nil || IsNil(o.TimeInTo) {
		var ret time.Time
		return ret
	}
	return *o.TimeInTo
}

// GetTimeInToOk returns a tuple with the TimeInTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportCreateRequest) GetTimeInToOk() (*time.Time, bool) {
	if o == nil || IsNil(o.TimeInTo) {
		return nil, false
	}
	return o.TimeInTo, true
}

// HasTimeInTo returns a boolean if a field has been set.
func (o *ExportCreateRequest) HasTimeInTo() bool {
	if o != nil && !IsNil(o.TimeInTo) {
		return true
	}

	return false
}

// SetTimeInTo gets a reference to the given time.Time and assigns it to the TimeInTo field.
func (o *ExportCreateRequest) SetTimeInTo(v time.Time) {
	o.TimeInTo = &v
}

// GetTimeSentFrom returns the TimeSentFrom field value if set, zero value otherwise.
func (o *ExportCreateRequest) GetTimeSentFrom() time.Time {
	if o == nil || IsNil(o.TimeSentFrom) {
		var ret time.Time
		return ret
	}
	return *o.TimeSentFrom
}

// GetTimeSentFromOk returns a tuple with the TimeSentFrom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportCreateRequest) GetTimeSentFromOk() (*time.Time, bool) {
	if o == nil || IsNil(o.TimeSentFrom) {
		return nil, false
	}
	return o.TimeSentFrom, true
}

// HasTimeSentFrom returns a boolean if a field has been set.
func (o *ExportCreateRequest) HasTimeSentFrom() bool {
	if o != nil && !IsNil(o.TimeSentFrom) {
		return true
	}

	return false
}

// SetTimeSentFrom gets a reference to the given time.Time and assigns it to the TimeSentFrom field.
func (o *ExportCreateRequest) SetTimeSentFrom(v time.Time) {
	o.TimeSentFrom = &v
}

// GetTimeSentTo returns the TimeSentTo field value if set, zero value otherwise.
func (o *ExportCreateRequest) GetTimeSentTo() time.Time {
	if o == nil || IsNil(o.TimeSentTo) {
		var ret time.Time
		return ret
	}
	return *o.TimeSentTo
}

// GetTimeSentToOk returns a tuple with the TimeSentTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportCreateRequest) GetTimeSentToOk() (*time.Time, bool) {
	if o == nil || IsNil(o.TimeSentTo) {
		return nil, false
	}
	return o.TimeSentTo, true
}

// HasTimeSentTo returns a boolean if a field has been set.
func (o *ExportCreateRequest) HasTimeSentTo() bool {
	if o != nil && !IsNil(o.TimeSentTo) {
		return true
	}

	return false
}

// SetTimeSentTo gets a reference to the given time.Time and assigns it to the TimeSentTo field.
func (o *ExportCreateRequest) SetTimeSentTo(v time.Time) {
	o.TimeSentTo = &v
}

// GetCountryId returns the CountryId field value if set, zero value otherwise.
func (o *ExportCreateRequest) GetCountryId() string {
	if o == nil || IsNil(o.CountryId) {
		var ret string
		return ret
	}
	return *o.CountryId
}

// GetCountryIdOk returns a tuple with the CountryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportCreateRequest) GetCountryIdOk() (*string, bool) {
	if o == nil || IsNil(o.CountryId) {
		return nil, false
	}
	return o.CountryId, true
}

// HasCountryId returns a boolean if a field has been set.
func (o *ExportCreateRequest) HasCountryId() bool {
	if o != nil && !IsNil(o.CountryId) {
		return true
	}

	return false
}

// SetCountryId gets a reference to the given string and assigns it to the CountryId field.
func (o *ExportCreateRequest) SetCountryId(v string) {
	o.CountryId = &v
}

// GetSlClicks returns the SlClicks field value if set, zero value otherwise.
func (o *ExportCreateRequest) GetSlClicks() string {
	if o == nil || IsNil(o.SlClicks) {
		var ret string
		return ret
	}
	return *o.SlClicks
}

// GetSlClicksOk returns a tuple with the SlClicks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportCreateRequest) GetSlClicksOk() (*string, bool) {
	if o == nil || IsNil(o.SlClicks) {
		return nil, false
	}
	return o.SlClicks, true
}

// HasSlClicks returns a boolean if a field has been set.
func (o *ExportCreateRequest) HasSlClicks() bool {
	if o != nil && !IsNil(o.SlClicks) {
		return true
	}

	return false
}

// SetSlClicks gets a reference to the given string and assigns it to the SlClicks field.
func (o *ExportCreateRequest) SetSlClicks(v string) {
	o.SlClicks = &v
}

// GetSlClicksComp returns the SlClicksComp field value if set, zero value otherwise.
func (o *ExportCreateRequest) GetSlClicksComp() string {
	if o == nil || IsNil(o.SlClicksComp) {
		var ret string
		return ret
	}
	return *o.SlClicksComp
}

// GetSlClicksCompOk returns a tuple with the SlClicksComp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportCreateRequest) GetSlClicksCompOk() (*string, bool) {
	if o == nil || IsNil(o.SlClicksComp) {
		return nil, false
	}
	return o.SlClicksComp, true
}

// HasSlClicksComp returns a boolean if a field has been set.
func (o *ExportCreateRequest) HasSlClicksComp() bool {
	if o != nil && !IsNil(o.SlClicksComp) {
		return true
	}

	return false
}

// SetSlClicksComp gets a reference to the given string and assigns it to the SlClicksComp field.
func (o *ExportCreateRequest) SetSlClicksComp(v string) {
	o.SlClicksComp = &v
}

// GetSlClicksCount returns the SlClicksCount field value if set, zero value otherwise.
func (o *ExportCreateRequest) GetSlClicksCount() string {
	if o == nil || IsNil(o.SlClicksCount) {
		var ret string
		return ret
	}
	return *o.SlClicksCount
}

// GetSlClicksCountOk returns a tuple with the SlClicksCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExportCreateRequest) GetSlClicksCountOk() (*string, bool) {
	if o == nil || IsNil(o.SlClicksCount) {
		return nil, false
	}
	return o.SlClicksCount, true
}

// HasSlClicksCount returns a boolean if a field has been set.
func (o *ExportCreateRequest) HasSlClicksCount() bool {
	if o != nil && !IsNil(o.SlClicksCount) {
		return true
	}

	return false
}

// SetSlClicksCount gets a reference to the given string and assigns it to the SlClicksCount field.
func (o *ExportCreateRequest) SetSlClicksCount(v string) {
	o.SlClicksCount = &v
}

func (o ExportCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExportCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MessageId) {
		toSerialize["message_id"] = o.MessageId
	}
	if !IsNil(o.Msisdn) {
		toSerialize["msisdn"] = o.Msisdn
	}
	if !IsNil(o.Originator) {
		toSerialize["originator"] = o.Originator
	}
	if !IsNil(o.SourceType) {
		toSerialize["source_type"] = o.SourceType
	}
	if !IsNil(o.MessageType) {
		toSerialize["message_type"] = o.MessageType
	}
	if !IsNil(o.TimeInFrom) {
		toSerialize["time_in_from"] = o.TimeInFrom
	}
	if !IsNil(o.TimeInTo) {
		toSerialize["time_in_to"] = o.TimeInTo
	}
	if !IsNil(o.TimeSentFrom) {
		toSerialize["time_sent_from"] = o.TimeSentFrom
	}
	if !IsNil(o.TimeSentTo) {
		toSerialize["time_sent_to"] = o.TimeSentTo
	}
	if !IsNil(o.CountryId) {
		toSerialize["country_id"] = o.CountryId
	}
	if !IsNil(o.SlClicks) {
		toSerialize["sl_clicks"] = o.SlClicks
	}
	if !IsNil(o.SlClicksComp) {
		toSerialize["sl_clicks_comp"] = o.SlClicksComp
	}
	if !IsNil(o.SlClicksCount) {
		toSerialize["sl_clicks_count"] = o.SlClicksCount
	}
	return toSerialize, nil
}

type NullableExportCreateRequest struct {
	value *ExportCreateRequest
	isSet bool
}

func (v NullableExportCreateRequest) Get() *ExportCreateRequest {
	return v.value
}

func (v *NullableExportCreateRequest) Set(val *ExportCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExportCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExportCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExportCreateRequest(val *ExportCreateRequest) *NullableExportCreateRequest {
	return &NullableExportCreateRequest{value: val, isSet: true}
}

func (v NullableExportCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExportCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


