/*
BSG SMS Gateway API

Comprehensive API for sending SMS, Viber messages, HLR/MNP requests and service management

API version: 1.0.0
Contact: support@bsg.world
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapiv1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HlrCreateRequestOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HlrCreateRequestOneOf{}

// HlrCreateRequestOneOf Single HLR request for /check endpoint
type HlrCreateRequestOneOf struct {
	// Phone number in international format
	Msisdn string `json:"msisdn"`
	// External reference ID for tracking (optional for sync)
	Reference *string `json:"reference,omitempty"`
	// Tariff code for pricing (optional, uses default if not provided)
	Tariff *int32 `json:"tariff,omitempty"`
	// URL for delivery reports (optional)
	CallbackUrl *string `json:"callback_url,omitempty"`
}

type _HlrCreateRequestOneOf HlrCreateRequestOneOf

// NewHlrCreateRequestOneOf instantiates a new HlrCreateRequestOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHlrCreateRequestOneOf(msisdn string) *HlrCreateRequestOneOf {
	this := HlrCreateRequestOneOf{}
	this.Msisdn = msisdn
	return &this
}

// NewHlrCreateRequestOneOfWithDefaults instantiates a new HlrCreateRequestOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHlrCreateRequestOneOfWithDefaults() *HlrCreateRequestOneOf {
	this := HlrCreateRequestOneOf{}
	return &this
}

// GetMsisdn returns the Msisdn field value
func (o *HlrCreateRequestOneOf) GetMsisdn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msisdn
}

// GetMsisdnOk returns a tuple with the Msisdn field value
// and a boolean to check if the value has been set.
func (o *HlrCreateRequestOneOf) GetMsisdnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msisdn, true
}

// SetMsisdn sets field value
func (o *HlrCreateRequestOneOf) SetMsisdn(v string) {
	o.Msisdn = v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *HlrCreateRequestOneOf) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HlrCreateRequestOneOf) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *HlrCreateRequestOneOf) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *HlrCreateRequestOneOf) SetReference(v string) {
	o.Reference = &v
}

// GetTariff returns the Tariff field value if set, zero value otherwise.
func (o *HlrCreateRequestOneOf) GetTariff() int32 {
	if o == nil || IsNil(o.Tariff) {
		var ret int32
		return ret
	}
	return *o.Tariff
}

// GetTariffOk returns a tuple with the Tariff field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HlrCreateRequestOneOf) GetTariffOk() (*int32, bool) {
	if o == nil || IsNil(o.Tariff) {
		return nil, false
	}
	return o.Tariff, true
}

// HasTariff returns a boolean if a field has been set.
func (o *HlrCreateRequestOneOf) HasTariff() bool {
	if o != nil && !IsNil(o.Tariff) {
		return true
	}

	return false
}

// SetTariff gets a reference to the given int32 and assigns it to the Tariff field.
func (o *HlrCreateRequestOneOf) SetTariff(v int32) {
	o.Tariff = &v
}

// GetCallbackUrl returns the CallbackUrl field value if set, zero value otherwise.
func (o *HlrCreateRequestOneOf) GetCallbackUrl() string {
	if o == nil || IsNil(o.CallbackUrl) {
		var ret string
		return ret
	}
	return *o.CallbackUrl
}

// GetCallbackUrlOk returns a tuple with the CallbackUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *HlrCreateRequestOneOf) GetCallbackUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CallbackUrl) {
		return nil, false
	}
	return o.CallbackUrl, true
}

// HasCallbackUrl returns a boolean if a field has been set.
func (o *HlrCreateRequestOneOf) HasCallbackUrl() bool {
	if o != nil && !IsNil(o.CallbackUrl) {
		return true
	}

	return false
}

// SetCallbackUrl gets a reference to the given string and assigns it to the CallbackUrl field.
func (o *HlrCreateRequestOneOf) SetCallbackUrl(v string) {
	o.CallbackUrl = &v
}

func (o HlrCreateRequestOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HlrCreateRequestOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["msisdn"] = o.Msisdn
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	if !IsNil(o.Tariff) {
		toSerialize["tariff"] = o.Tariff
	}
	if !IsNil(o.CallbackUrl) {
		toSerialize["callback_url"] = o.CallbackUrl
	}
	return toSerialize, nil
}

func (o *HlrCreateRequestOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"msisdn",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHlrCreateRequestOneOf := _HlrCreateRequestOneOf{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHlrCreateRequestOneOf)

	if err != nil {
		return err
	}

	*o = HlrCreateRequestOneOf(varHlrCreateRequestOneOf)

	return err
}

type NullableHlrCreateRequestOneOf struct {
	value *HlrCreateRequestOneOf
	isSet bool
}

func (v NullableHlrCreateRequestOneOf) Get() *HlrCreateRequestOneOf {
	return v.value
}

func (v *NullableHlrCreateRequestOneOf) Set(val *HlrCreateRequestOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableHlrCreateRequestOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableHlrCreateRequestOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHlrCreateRequestOneOf(val *HlrCreateRequestOneOf) *NullableHlrCreateRequestOneOf {
	return &NullableHlrCreateRequestOneOf{value: val, isSet: true}
}

func (v NullableHlrCreateRequestOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHlrCreateRequestOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


