/*
BSG SMS Gateway API

Comprehensive API for sending SMS, Viber messages, HLR/MNP requests and service management

API version: 1.0.0
Contact: support@bsg.world
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapiv1

import (
	"encoding/json"
	"fmt"
)

// checks if the SmsPriceCheckRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SmsPriceCheckRequest{}

// SmsPriceCheckRequest Request to calculate SMS price without sending the message. Supports same three types as SMS sending: single phone, multiple phones, or OTP.
type SmsPriceCheckRequest struct {
	SMSPriceCheckMultiplePhones *SMSPriceCheckMultiplePhones
	SMSPriceCheckSinglePhone *SMSPriceCheckSinglePhone
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *SmsPriceCheckRequest) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = json.Unmarshal(data, &jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'phone'
	if jsonDict["destination"] == "phone" {
		// try to unmarshal JSON data into Model0
		err = json.Unmarshal(data, &dst.Model0);
		if err == nil {
			jsonModel0, _ := json.Marshal(dst.Model0)
			if string(jsonModel0) == "{}" { // empty struct
				dst.Model0 = nil
			} else {
				return nil // data stored in dst.Model0, return on the first match
			}
		} else {
			dst.Model0 = nil
		}
	}

	// check if the discriminator value is 'phones'
	if jsonDict["destination"] == "phones" {
		// try to unmarshal JSON data into Model1
		err = json.Unmarshal(data, &dst.Model1);
		if err == nil {
			jsonModel1, _ := json.Marshal(dst.Model1)
			if string(jsonModel1) == "{}" { // empty struct
				dst.Model1 = nil
			} else {
				return nil // data stored in dst.Model1, return on the first match
			}
		} else {
			dst.Model1 = nil
		}
	}

	// check if the discriminator value is 'SMS_Price_Check___Multiple_Phones'
	if jsonDict["destination"] == "SMS_Price_Check___Multiple_Phones" {
		// try to unmarshal JSON data into SMSPriceCheckMultiplePhones
		err = json.Unmarshal(data, &dst.SMSPriceCheckMultiplePhones);
		if err == nil {
			jsonSMSPriceCheckMultiplePhones, _ := json.Marshal(dst.SMSPriceCheckMultiplePhones)
			if string(jsonSMSPriceCheckMultiplePhones) == "{}" { // empty struct
				dst.SMSPriceCheckMultiplePhones = nil
			} else {
				return nil // data stored in dst.SMSPriceCheckMultiplePhones, return on the first match
			}
		} else {
			dst.SMSPriceCheckMultiplePhones = nil
		}
	}

	// check if the discriminator value is 'SMS_Price_Check___Single_Phone'
	if jsonDict["destination"] == "SMS_Price_Check___Single_Phone" {
		// try to unmarshal JSON data into SMSPriceCheckSinglePhone
		err = json.Unmarshal(data, &dst.SMSPriceCheckSinglePhone);
		if err == nil {
			jsonSMSPriceCheckSinglePhone, _ := json.Marshal(dst.SMSPriceCheckSinglePhone)
			if string(jsonSMSPriceCheckSinglePhone) == "{}" { // empty struct
				dst.SMSPriceCheckSinglePhone = nil
			} else {
				return nil // data stored in dst.SMSPriceCheckSinglePhone, return on the first match
			}
		} else {
			dst.SMSPriceCheckSinglePhone = nil
		}
	}

	// try to unmarshal JSON data into SMSPriceCheckMultiplePhones
	err = json.Unmarshal(data, &dst.SMSPriceCheckMultiplePhones);
	if err == nil {
		jsonSMSPriceCheckMultiplePhones, _ := json.Marshal(dst.SMSPriceCheckMultiplePhones)
		if string(jsonSMSPriceCheckMultiplePhones) == "{}" { // empty struct
			dst.SMSPriceCheckMultiplePhones = nil
		} else {
			return nil // data stored in dst.SMSPriceCheckMultiplePhones, return on the first match
		}
	} else {
		dst.SMSPriceCheckMultiplePhones = nil
	}

	// try to unmarshal JSON data into SMSPriceCheckSinglePhone
	err = json.Unmarshal(data, &dst.SMSPriceCheckSinglePhone);
	if err == nil {
		jsonSMSPriceCheckSinglePhone, _ := json.Marshal(dst.SMSPriceCheckSinglePhone)
		if string(jsonSMSPriceCheckSinglePhone) == "{}" { // empty struct
			dst.SMSPriceCheckSinglePhone = nil
		} else {
			return nil // data stored in dst.SMSPriceCheckSinglePhone, return on the first match
		}
	} else {
		dst.SMSPriceCheckSinglePhone = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(SmsPriceCheckRequest)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src SmsPriceCheckRequest) MarshalJSON() ([]byte, error) {
	if src.SMSPriceCheckMultiplePhones != nil {
		return json.Marshal(&src.SMSPriceCheckMultiplePhones)
	}

	if src.SMSPriceCheckSinglePhone != nil {
		return json.Marshal(&src.SMSPriceCheckSinglePhone)
	}

	return nil, nil // no data in anyOf schemas
}

func (src SmsPriceCheckRequest) ToMap() (map[string]interface{}, error) {
	if src.SMSPriceCheckMultiplePhones != nil {
		return src.SMSPriceCheckMultiplePhones.ToMap()
	}

	if src.SMSPriceCheckSinglePhone != nil {
		return src.SMSPriceCheckSinglePhone.ToMap()
	}

    return nil, nil // no data in anyOf schemas
}

type NullableSmsPriceCheckRequest struct {
	value *SmsPriceCheckRequest
	isSet bool
}

func (v NullableSmsPriceCheckRequest) Get() *SmsPriceCheckRequest {
	return v.value
}

func (v *NullableSmsPriceCheckRequest) Set(val *SmsPriceCheckRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSmsPriceCheckRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSmsPriceCheckRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmsPriceCheckRequest(val *SmsPriceCheckRequest) *NullableSmsPriceCheckRequest {
	return &NullableSmsPriceCheckRequest{value: val, isSet: true}
}

func (v NullableSmsPriceCheckRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmsPriceCheckRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


