/*
BSG SMS Gateway API

Comprehensive API for sending SMS, Viber messages, HLR/MNP requests and service management

API version: 1.0.0
Contact: support@bsg.world
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapiv1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SmsPriceCheckResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SmsPriceCheckResponse{}

// SmsPriceCheckResponse Response containing SMS price calculation without sending the message
type SmsPriceCheckResponse struct {
	// Error code: 0 for success. Common errors: 1=Invalid phone, 7=Invalid originator, 24=Invalid payload JSON, 14=Not enough balance, 15=Invalid price grid
	Error int32 `json:"error"`
	// Human-readable error description
	ErrorDescription string `json:"errorDescription"`
	// Total calculated price for the SMS message(s) that would be sent
	Totalprice float32 `json:"totalprice"`
	// Currency code according to ISO-4217 standard
	Currency string `json:"currency" validate:"regexp=^[A-Z]{3}$"`
}

type _SmsPriceCheckResponse SmsPriceCheckResponse

// NewSmsPriceCheckResponse instantiates a new SmsPriceCheckResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSmsPriceCheckResponse(error_ int32, errorDescription string, totalprice float32, currency string) *SmsPriceCheckResponse {
	this := SmsPriceCheckResponse{}
	this.Error = error_
	this.ErrorDescription = errorDescription
	this.Totalprice = totalprice
	this.Currency = currency
	return &this
}

// NewSmsPriceCheckResponseWithDefaults instantiates a new SmsPriceCheckResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSmsPriceCheckResponseWithDefaults() *SmsPriceCheckResponse {
	this := SmsPriceCheckResponse{}
	return &this
}

// GetError returns the Error field value
func (o *SmsPriceCheckResponse) GetError() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *SmsPriceCheckResponse) GetErrorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *SmsPriceCheckResponse) SetError(v int32) {
	o.Error = v
}

// GetErrorDescription returns the ErrorDescription field value
func (o *SmsPriceCheckResponse) GetErrorDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ErrorDescription
}

// GetErrorDescriptionOk returns a tuple with the ErrorDescription field value
// and a boolean to check if the value has been set.
func (o *SmsPriceCheckResponse) GetErrorDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorDescription, true
}

// SetErrorDescription sets field value
func (o *SmsPriceCheckResponse) SetErrorDescription(v string) {
	o.ErrorDescription = v
}

// GetTotalprice returns the Totalprice field value
func (o *SmsPriceCheckResponse) GetTotalprice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Totalprice
}

// GetTotalpriceOk returns a tuple with the Totalprice field value
// and a boolean to check if the value has been set.
func (o *SmsPriceCheckResponse) GetTotalpriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Totalprice, true
}

// SetTotalprice sets field value
func (o *SmsPriceCheckResponse) SetTotalprice(v float32) {
	o.Totalprice = v
}

// GetCurrency returns the Currency field value
func (o *SmsPriceCheckResponse) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *SmsPriceCheckResponse) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *SmsPriceCheckResponse) SetCurrency(v string) {
	o.Currency = v
}

func (o SmsPriceCheckResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SmsPriceCheckResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	toSerialize["errorDescription"] = o.ErrorDescription
	toSerialize["totalprice"] = o.Totalprice
	toSerialize["currency"] = o.Currency
	return toSerialize, nil
}

func (o *SmsPriceCheckResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
		"errorDescription",
		"totalprice",
		"currency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSmsPriceCheckResponse := _SmsPriceCheckResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSmsPriceCheckResponse)

	if err != nil {
		return err
	}

	*o = SmsPriceCheckResponse(varSmsPriceCheckResponse)

	return err
}

type NullableSmsPriceCheckResponse struct {
	value *SmsPriceCheckResponse
	isSet bool
}

func (v NullableSmsPriceCheckResponse) Get() *SmsPriceCheckResponse {
	return v.value
}

func (v *NullableSmsPriceCheckResponse) Set(val *SmsPriceCheckResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSmsPriceCheckResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSmsPriceCheckResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmsPriceCheckResponse(val *SmsPriceCheckResponse) *NullableSmsPriceCheckResponse {
	return &NullableSmsPriceCheckResponse{value: val, isSet: true}
}

func (v NullableSmsPriceCheckResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmsPriceCheckResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


