/*
BSG SMS Gateway API

Comprehensive API for sending SMS, Viber messages, HLR/MNP requests and service management

API version: 1.0.0
Contact: support@bsg.world
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapiv1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ViberPricesRequestMessagesInnerToInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViberPricesRequestMessagesInnerToInner{}

// ViberPricesRequestMessagesInnerToInner struct for ViberPricesRequestMessagesInnerToInner
type ViberPricesRequestMessagesInnerToInner struct {
	// Recipient phone number in international format
	Msisdn string `json:"msisdn" validate:"regexp=^[1-9][0-9]{7,14}$"`
}

type _ViberPricesRequestMessagesInnerToInner ViberPricesRequestMessagesInnerToInner

// NewViberPricesRequestMessagesInnerToInner instantiates a new ViberPricesRequestMessagesInnerToInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViberPricesRequestMessagesInnerToInner(msisdn string) *ViberPricesRequestMessagesInnerToInner {
	this := ViberPricesRequestMessagesInnerToInner{}
	this.Msisdn = msisdn
	return &this
}

// NewViberPricesRequestMessagesInnerToInnerWithDefaults instantiates a new ViberPricesRequestMessagesInnerToInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViberPricesRequestMessagesInnerToInnerWithDefaults() *ViberPricesRequestMessagesInnerToInner {
	this := ViberPricesRequestMessagesInnerToInner{}
	return &this
}

// GetMsisdn returns the Msisdn field value
func (o *ViberPricesRequestMessagesInnerToInner) GetMsisdn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msisdn
}

// GetMsisdnOk returns a tuple with the Msisdn field value
// and a boolean to check if the value has been set.
func (o *ViberPricesRequestMessagesInnerToInner) GetMsisdnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msisdn, true
}

// SetMsisdn sets field value
func (o *ViberPricesRequestMessagesInnerToInner) SetMsisdn(v string) {
	o.Msisdn = v
}

func (o ViberPricesRequestMessagesInnerToInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViberPricesRequestMessagesInnerToInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["msisdn"] = o.Msisdn
	return toSerialize, nil
}

func (o *ViberPricesRequestMessagesInnerToInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"msisdn",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varViberPricesRequestMessagesInnerToInner := _ViberPricesRequestMessagesInnerToInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varViberPricesRequestMessagesInnerToInner)

	if err != nil {
		return err
	}

	*o = ViberPricesRequestMessagesInnerToInner(varViberPricesRequestMessagesInnerToInner)

	return err
}

type NullableViberPricesRequestMessagesInnerToInner struct {
	value *ViberPricesRequestMessagesInnerToInner
	isSet bool
}

func (v NullableViberPricesRequestMessagesInnerToInner) Get() *ViberPricesRequestMessagesInnerToInner {
	return v.value
}

func (v *NullableViberPricesRequestMessagesInnerToInner) Set(val *ViberPricesRequestMessagesInnerToInner) {
	v.value = val
	v.isSet = true
}

func (v NullableViberPricesRequestMessagesInnerToInner) IsSet() bool {
	return v.isSet
}

func (v *NullableViberPricesRequestMessagesInnerToInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViberPricesRequestMessagesInnerToInner(val *ViberPricesRequestMessagesInnerToInner) *NullableViberPricesRequestMessagesInnerToInner {
	return &NullableViberPricesRequestMessagesInnerToInner{value: val, isSet: true}
}

func (v NullableViberPricesRequestMessagesInnerToInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViberPricesRequestMessagesInnerToInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


