/*
BSG SMS Gateway API

Comprehensive API for sending SMS, Viber messages, HLR/MNP requests and service management

API version: 1.0.0
Contact: support@bsg.world
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapiv1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Sms2WayIncomingResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Sms2WayIncomingResponse{}

// Sms2WayIncomingResponse Response containing incoming 2-way SMS messages
type Sms2WayIncomingResponse struct {
	// Error code: 0 for success, 35 for inactive 2way SMS service
	Error int32 `json:"error"`
	// Human-readable error description
	ErrorDescription string `json:"errorDescription"`
	// Array of incoming messages
	Result []Sms2WayIncomingResponseResultInner `json:"result"`
	// Total number of messages found
	TotalCount int32 `json:"total_count"`
}

type _Sms2WayIncomingResponse Sms2WayIncomingResponse

// NewSms2WayIncomingResponse instantiates a new Sms2WayIncomingResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSms2WayIncomingResponse(error_ int32, errorDescription string, result []Sms2WayIncomingResponseResultInner, totalCount int32) *Sms2WayIncomingResponse {
	this := Sms2WayIncomingResponse{}
	this.Error = error_
	this.ErrorDescription = errorDescription
	this.Result = result
	this.TotalCount = totalCount
	return &this
}

// NewSms2WayIncomingResponseWithDefaults instantiates a new Sms2WayIncomingResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSms2WayIncomingResponseWithDefaults() *Sms2WayIncomingResponse {
	this := Sms2WayIncomingResponse{}
	return &this
}

// GetError returns the Error field value
func (o *Sms2WayIncomingResponse) GetError() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *Sms2WayIncomingResponse) GetErrorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *Sms2WayIncomingResponse) SetError(v int32) {
	o.Error = v
}

// GetErrorDescription returns the ErrorDescription field value
func (o *Sms2WayIncomingResponse) GetErrorDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ErrorDescription
}

// GetErrorDescriptionOk returns a tuple with the ErrorDescription field value
// and a boolean to check if the value has been set.
func (o *Sms2WayIncomingResponse) GetErrorDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorDescription, true
}

// SetErrorDescription sets field value
func (o *Sms2WayIncomingResponse) SetErrorDescription(v string) {
	o.ErrorDescription = v
}

// GetResult returns the Result field value
func (o *Sms2WayIncomingResponse) GetResult() []Sms2WayIncomingResponseResultInner {
	if o == nil {
		var ret []Sms2WayIncomingResponseResultInner
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *Sms2WayIncomingResponse) GetResultOk() ([]Sms2WayIncomingResponseResultInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Result, true
}

// SetResult sets field value
func (o *Sms2WayIncomingResponse) SetResult(v []Sms2WayIncomingResponseResultInner) {
	o.Result = v
}

// GetTotalCount returns the TotalCount field value
func (o *Sms2WayIncomingResponse) GetTotalCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *Sms2WayIncomingResponse) GetTotalCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *Sms2WayIncomingResponse) SetTotalCount(v int32) {
	o.TotalCount = v
}

func (o Sms2WayIncomingResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Sms2WayIncomingResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	toSerialize["errorDescription"] = o.ErrorDescription
	toSerialize["result"] = o.Result
	toSerialize["total_count"] = o.TotalCount
	return toSerialize, nil
}

func (o *Sms2WayIncomingResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
		"errorDescription",
		"result",
		"total_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSms2WayIncomingResponse := _Sms2WayIncomingResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSms2WayIncomingResponse)

	if err != nil {
		return err
	}

	*o = Sms2WayIncomingResponse(varSms2WayIncomingResponse)

	return err
}

type NullableSms2WayIncomingResponse struct {
	value *Sms2WayIncomingResponse
	isSet bool
}

func (v NullableSms2WayIncomingResponse) Get() *Sms2WayIncomingResponse {
	return v.value
}

func (v *NullableSms2WayIncomingResponse) Set(val *Sms2WayIncomingResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSms2WayIncomingResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSms2WayIncomingResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSms2WayIncomingResponse(val *Sms2WayIncomingResponse) *NullableSms2WayIncomingResponse {
	return &NullableSms2WayIncomingResponse{value: val, isSet: true}
}

func (v NullableSms2WayIncomingResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSms2WayIncomingResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


