/*
BSG SMS Gateway API

Comprehensive API for sending SMS, Viber messages, HLR/MNP requests and service management

API version: 1.0.0
Contact: support@bsg.world
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapiv1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HlrPricesResponsePricesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HlrPricesResponsePricesInner{}

// HlrPricesResponsePricesInner Pricing entry for a specific destination
type HlrPricesResponsePricesInner struct {
	// Service type (always \"hlr\" for this API)
	Type string `json:"type"`
	// ISO 3166-1 alpha-2 country code
	Country string `json:"country" validate:"regexp=^[A-Z]{2}$"`
	// Full country name in English
	CountryName string `json:"country_name"`
	// Mobile Country Code (ITU-T E.212)
	Mcc string `json:"mcc" validate:"regexp=^[0-9]{3}$"`
	// Mobile Network Code (0 = all operators)
	Mnc string `json:"mnc"`
	// Price per HLR lookup with 7 decimal precision
	Price string `json:"price" validate:"regexp=^[0-9]+\\\\.[0-9]{7}$"`
	// Currency code (ISO 4217)
	Currency string `json:"currency" validate:"regexp=^[A-Z]{3}$"`
}

type _HlrPricesResponsePricesInner HlrPricesResponsePricesInner

// NewHlrPricesResponsePricesInner instantiates a new HlrPricesResponsePricesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHlrPricesResponsePricesInner(type_ string, country string, countryName string, mcc string, mnc string, price string, currency string) *HlrPricesResponsePricesInner {
	this := HlrPricesResponsePricesInner{}
	this.Type = type_
	this.Country = country
	this.CountryName = countryName
	this.Mcc = mcc
	this.Mnc = mnc
	this.Price = price
	this.Currency = currency
	return &this
}

// NewHlrPricesResponsePricesInnerWithDefaults instantiates a new HlrPricesResponsePricesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHlrPricesResponsePricesInnerWithDefaults() *HlrPricesResponsePricesInner {
	this := HlrPricesResponsePricesInner{}
	return &this
}

// GetType returns the Type field value
func (o *HlrPricesResponsePricesInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *HlrPricesResponsePricesInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *HlrPricesResponsePricesInner) SetType(v string) {
	o.Type = v
}

// GetCountry returns the Country field value
func (o *HlrPricesResponsePricesInner) GetCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Country
}

// GetCountryOk returns a tuple with the Country field value
// and a boolean to check if the value has been set.
func (o *HlrPricesResponsePricesInner) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Country, true
}

// SetCountry sets field value
func (o *HlrPricesResponsePricesInner) SetCountry(v string) {
	o.Country = v
}

// GetCountryName returns the CountryName field value
func (o *HlrPricesResponsePricesInner) GetCountryName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryName
}

// GetCountryNameOk returns a tuple with the CountryName field value
// and a boolean to check if the value has been set.
func (o *HlrPricesResponsePricesInner) GetCountryNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryName, true
}

// SetCountryName sets field value
func (o *HlrPricesResponsePricesInner) SetCountryName(v string) {
	o.CountryName = v
}

// GetMcc returns the Mcc field value
func (o *HlrPricesResponsePricesInner) GetMcc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mcc
}

// GetMccOk returns a tuple with the Mcc field value
// and a boolean to check if the value has been set.
func (o *HlrPricesResponsePricesInner) GetMccOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mcc, true
}

// SetMcc sets field value
func (o *HlrPricesResponsePricesInner) SetMcc(v string) {
	o.Mcc = v
}

// GetMnc returns the Mnc field value
func (o *HlrPricesResponsePricesInner) GetMnc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mnc
}

// GetMncOk returns a tuple with the Mnc field value
// and a boolean to check if the value has been set.
func (o *HlrPricesResponsePricesInner) GetMncOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mnc, true
}

// SetMnc sets field value
func (o *HlrPricesResponsePricesInner) SetMnc(v string) {
	o.Mnc = v
}

// GetPrice returns the Price field value
func (o *HlrPricesResponsePricesInner) GetPrice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *HlrPricesResponsePricesInner) GetPriceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *HlrPricesResponsePricesInner) SetPrice(v string) {
	o.Price = v
}

// GetCurrency returns the Currency field value
func (o *HlrPricesResponsePricesInner) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *HlrPricesResponsePricesInner) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *HlrPricesResponsePricesInner) SetCurrency(v string) {
	o.Currency = v
}

func (o HlrPricesResponsePricesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HlrPricesResponsePricesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["country"] = o.Country
	toSerialize["country_name"] = o.CountryName
	toSerialize["mcc"] = o.Mcc
	toSerialize["mnc"] = o.Mnc
	toSerialize["price"] = o.Price
	toSerialize["currency"] = o.Currency
	return toSerialize, nil
}

func (o *HlrPricesResponsePricesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"country",
		"country_name",
		"mcc",
		"mnc",
		"price",
		"currency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHlrPricesResponsePricesInner := _HlrPricesResponsePricesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHlrPricesResponsePricesInner)

	if err != nil {
		return err
	}

	*o = HlrPricesResponsePricesInner(varHlrPricesResponsePricesInner)

	return err
}

type NullableHlrPricesResponsePricesInner struct {
	value *HlrPricesResponsePricesInner
	isSet bool
}

func (v NullableHlrPricesResponsePricesInner) Get() *HlrPricesResponsePricesInner {
	return v.value
}

func (v *NullableHlrPricesResponsePricesInner) Set(val *HlrPricesResponsePricesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableHlrPricesResponsePricesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableHlrPricesResponsePricesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHlrPricesResponsePricesInner(val *HlrPricesResponsePricesInner) *NullableHlrPricesResponsePricesInner {
	return &NullableHlrPricesResponsePricesInner{value: val, isSet: true}
}

func (v NullableHlrPricesResponsePricesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHlrPricesResponsePricesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


