/*
BSG SMS Gateway API

Comprehensive API for sending SMS, Viber messages, HLR/MNP requests and service management

API version: 1.0.0
Contact: support@bsg.world
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapiv1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MnpCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MnpCreateResponse{}

// MnpCreateResponse MNP lookup response with results and pricing
type MnpCreateResponse struct {
	// Array of MNP lookup results for each requested number
	Result []MnpCreateResponseResultInner `json:"result"`
	// Total price for all MNP lookups in the request
	TotalPrice float32 `json:"total_price"`
	// Currency code (ISO 4217)
	Currency string `json:"currency" validate:"regexp=^[A-Z]{3}$"`
}

type _MnpCreateResponse MnpCreateResponse

// NewMnpCreateResponse instantiates a new MnpCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMnpCreateResponse(result []MnpCreateResponseResultInner, totalPrice float32, currency string) *MnpCreateResponse {
	this := MnpCreateResponse{}
	this.Result = result
	this.TotalPrice = totalPrice
	this.Currency = currency
	return &this
}

// NewMnpCreateResponseWithDefaults instantiates a new MnpCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMnpCreateResponseWithDefaults() *MnpCreateResponse {
	this := MnpCreateResponse{}
	return &this
}

// GetResult returns the Result field value
func (o *MnpCreateResponse) GetResult() []MnpCreateResponseResultInner {
	if o == nil {
		var ret []MnpCreateResponseResultInner
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *MnpCreateResponse) GetResultOk() ([]MnpCreateResponseResultInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Result, true
}

// SetResult sets field value
func (o *MnpCreateResponse) SetResult(v []MnpCreateResponseResultInner) {
	o.Result = v
}

// GetTotalPrice returns the TotalPrice field value
func (o *MnpCreateResponse) GetTotalPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalPrice
}

// GetTotalPriceOk returns a tuple with the TotalPrice field value
// and a boolean to check if the value has been set.
func (o *MnpCreateResponse) GetTotalPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalPrice, true
}

// SetTotalPrice sets field value
func (o *MnpCreateResponse) SetTotalPrice(v float32) {
	o.TotalPrice = v
}

// GetCurrency returns the Currency field value
func (o *MnpCreateResponse) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *MnpCreateResponse) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *MnpCreateResponse) SetCurrency(v string) {
	o.Currency = v
}

func (o MnpCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MnpCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	toSerialize["total_price"] = o.TotalPrice
	toSerialize["currency"] = o.Currency
	return toSerialize, nil
}

func (o *MnpCreateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
		"total_price",
		"currency",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMnpCreateResponse := _MnpCreateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMnpCreateResponse)

	if err != nil {
		return err
	}

	*o = MnpCreateResponse(varMnpCreateResponse)

	return err
}

type NullableMnpCreateResponse struct {
	value *MnpCreateResponse
	isSet bool
}

func (v NullableMnpCreateResponse) Get() *MnpCreateResponse {
	return v.value
}

func (v *NullableMnpCreateResponse) Set(val *MnpCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMnpCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMnpCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMnpCreateResponse(val *MnpCreateResponse) *NullableMnpCreateResponse {
	return &NullableMnpCreateResponse{value: val, isSet: true}
}

func (v NullableMnpCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMnpCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


