/*
BSG SMS Gateway API

Comprehensive API for sending SMS, Viber messages, HLR/MNP requests and service management

API version: 1.0.0
Contact: support@bsg.world
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapiv1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SmsOtpCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SmsOtpCreateRequest{}

// SmsOtpCreateRequest struct for SmsOtpCreateRequest
type SmsOtpCreateRequest struct {
	// Message destination type for OTP messages
	Destination string `json:"destination"`
	// Phone number for OTP delivery
	Msisdn string `json:"msisdn" validate:"regexp=^[1-9][0-9]{7,14}$"`
	// Reference ID for OTP tracking
	Reference *string `json:"reference,omitempty" validate:"regexp=^[a-zA-Z0-9_-]+$"`
	// Sender name for OTP message
	Originator string `json:"originator"`
	// OTP SMS text with auto-generation placeholders. Supported patterns: {gen_otp_09,4} - 4-digit numbers (0-9), {gen_otp_09,6} - 6-digit numbers, {gen_otp_AZ,4} - 4 uppercase letters (A-Z), {gen_otp_az,4} - 4 lowercase letters (a-z), {gen_otp_aZ,4} - 4 mixed case letters, {gen_otp_a9,8} - 8 chars letters+numbers, {gen_otp_**,6} - 6 chars with special symbols
	Body string `json:"body"`
	// HTTPS URL for receiving delivery reports (DLR). Must be accessible from our servers. We will POST delivery status updates to this endpoint
	CallbackUrl *string `json:"callback_url,omitempty"`
	// HTTPS URL for receiving 2-way SMS responses. Only works if 2way=true and sender supports incoming messages
	CallbackUrl2way *string `json:"callback_url_2way,omitempty"`
	// Specific tariff code to use for pricing this message. Optional - uses user's default tariff if not specified
	Tariff *int32 `json:"tariff,omitempty"`
	// Message validity period in hours. Default is 72 hours (3 days). Maximum is 87840 hours (10 years). After this time, undelivered message will expire
	Validity *int32 `json:"validity,omitempty"`
}

type _SmsOtpCreateRequest SmsOtpCreateRequest

// NewSmsOtpCreateRequest instantiates a new SmsOtpCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSmsOtpCreateRequest(destination string, msisdn string, originator string, body string) *SmsOtpCreateRequest {
	this := SmsOtpCreateRequest{}
	this.Destination = destination
	this.Msisdn = msisdn
	this.Originator = originator
	this.Body = body
	return &this
}

// NewSmsOtpCreateRequestWithDefaults instantiates a new SmsOtpCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSmsOtpCreateRequestWithDefaults() *SmsOtpCreateRequest {
	this := SmsOtpCreateRequest{}
	return &this
}

// GetDestination returns the Destination field value
func (o *SmsOtpCreateRequest) GetDestination() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value
// and a boolean to check if the value has been set.
func (o *SmsOtpCreateRequest) GetDestinationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Destination, true
}

// SetDestination sets field value
func (o *SmsOtpCreateRequest) SetDestination(v string) {
	o.Destination = v
}

// GetMsisdn returns the Msisdn field value
func (o *SmsOtpCreateRequest) GetMsisdn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msisdn
}

// GetMsisdnOk returns a tuple with the Msisdn field value
// and a boolean to check if the value has been set.
func (o *SmsOtpCreateRequest) GetMsisdnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msisdn, true
}

// SetMsisdn sets field value
func (o *SmsOtpCreateRequest) SetMsisdn(v string) {
	o.Msisdn = v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *SmsOtpCreateRequest) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmsOtpCreateRequest) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *SmsOtpCreateRequest) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *SmsOtpCreateRequest) SetReference(v string) {
	o.Reference = &v
}

// GetOriginator returns the Originator field value
func (o *SmsOtpCreateRequest) GetOriginator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Originator
}

// GetOriginatorOk returns a tuple with the Originator field value
// and a boolean to check if the value has been set.
func (o *SmsOtpCreateRequest) GetOriginatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Originator, true
}

// SetOriginator sets field value
func (o *SmsOtpCreateRequest) SetOriginator(v string) {
	o.Originator = v
}

// GetBody returns the Body field value
func (o *SmsOtpCreateRequest) GetBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *SmsOtpCreateRequest) GetBodyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *SmsOtpCreateRequest) SetBody(v string) {
	o.Body = v
}

// GetCallbackUrl returns the CallbackUrl field value if set, zero value otherwise.
func (o *SmsOtpCreateRequest) GetCallbackUrl() string {
	if o == nil || IsNil(o.CallbackUrl) {
		var ret string
		return ret
	}
	return *o.CallbackUrl
}

// GetCallbackUrlOk returns a tuple with the CallbackUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmsOtpCreateRequest) GetCallbackUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CallbackUrl) {
		return nil, false
	}
	return o.CallbackUrl, true
}

// HasCallbackUrl returns a boolean if a field has been set.
func (o *SmsOtpCreateRequest) HasCallbackUrl() bool {
	if o != nil && !IsNil(o.CallbackUrl) {
		return true
	}

	return false
}

// SetCallbackUrl gets a reference to the given string and assigns it to the CallbackUrl field.
func (o *SmsOtpCreateRequest) SetCallbackUrl(v string) {
	o.CallbackUrl = &v
}

// GetCallbackUrl2way returns the CallbackUrl2way field value if set, zero value otherwise.
func (o *SmsOtpCreateRequest) GetCallbackUrl2way() string {
	if o == nil || IsNil(o.CallbackUrl2way) {
		var ret string
		return ret
	}
	return *o.CallbackUrl2way
}

// GetCallbackUrl2wayOk returns a tuple with the CallbackUrl2way field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmsOtpCreateRequest) GetCallbackUrl2wayOk() (*string, bool) {
	if o == nil || IsNil(o.CallbackUrl2way) {
		return nil, false
	}
	return o.CallbackUrl2way, true
}

// HasCallbackUrl2way returns a boolean if a field has been set.
func (o *SmsOtpCreateRequest) HasCallbackUrl2way() bool {
	if o != nil && !IsNil(o.CallbackUrl2way) {
		return true
	}

	return false
}

// SetCallbackUrl2way gets a reference to the given string and assigns it to the CallbackUrl2way field.
func (o *SmsOtpCreateRequest) SetCallbackUrl2way(v string) {
	o.CallbackUrl2way = &v
}

// GetTariff returns the Tariff field value if set, zero value otherwise.
func (o *SmsOtpCreateRequest) GetTariff() int32 {
	if o == nil || IsNil(o.Tariff) {
		var ret int32
		return ret
	}
	return *o.Tariff
}

// GetTariffOk returns a tuple with the Tariff field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmsOtpCreateRequest) GetTariffOk() (*int32, bool) {
	if o == nil || IsNil(o.Tariff) {
		return nil, false
	}
	return o.Tariff, true
}

// HasTariff returns a boolean if a field has been set.
func (o *SmsOtpCreateRequest) HasTariff() bool {
	if o != nil && !IsNil(o.Tariff) {
		return true
	}

	return false
}

// SetTariff gets a reference to the given int32 and assigns it to the Tariff field.
func (o *SmsOtpCreateRequest) SetTariff(v int32) {
	o.Tariff = &v
}

// GetValidity returns the Validity field value if set, zero value otherwise.
func (o *SmsOtpCreateRequest) GetValidity() int32 {
	if o == nil || IsNil(o.Validity) {
		var ret int32
		return ret
	}
	return *o.Validity
}

// GetValidityOk returns a tuple with the Validity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmsOtpCreateRequest) GetValidityOk() (*int32, bool) {
	if o == nil || IsNil(o.Validity) {
		return nil, false
	}
	return o.Validity, true
}

// HasValidity returns a boolean if a field has been set.
func (o *SmsOtpCreateRequest) HasValidity() bool {
	if o != nil && !IsNil(o.Validity) {
		return true
	}

	return false
}

// SetValidity gets a reference to the given int32 and assigns it to the Validity field.
func (o *SmsOtpCreateRequest) SetValidity(v int32) {
	o.Validity = &v
}

func (o SmsOtpCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SmsOtpCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["destination"] = o.Destination
	toSerialize["msisdn"] = o.Msisdn
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	toSerialize["originator"] = o.Originator
	toSerialize["body"] = o.Body
	if !IsNil(o.CallbackUrl) {
		toSerialize["callback_url"] = o.CallbackUrl
	}
	if !IsNil(o.CallbackUrl2way) {
		toSerialize["callback_url_2way"] = o.CallbackUrl2way
	}
	if !IsNil(o.Tariff) {
		toSerialize["tariff"] = o.Tariff
	}
	if !IsNil(o.Validity) {
		toSerialize["validity"] = o.Validity
	}
	return toSerialize, nil
}

func (o *SmsOtpCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"destination",
		"msisdn",
		"originator",
		"body",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSmsOtpCreateRequest := _SmsOtpCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSmsOtpCreateRequest)

	if err != nil {
		return err
	}

	*o = SmsOtpCreateRequest(varSmsOtpCreateRequest)

	return err
}

type NullableSmsOtpCreateRequest struct {
	value *SmsOtpCreateRequest
	isSet bool
}

func (v NullableSmsOtpCreateRequest) Get() *SmsOtpCreateRequest {
	return v.value
}

func (v *NullableSmsOtpCreateRequest) Set(val *SmsOtpCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSmsOtpCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSmsOtpCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmsOtpCreateRequest(val *SmsOtpCreateRequest) *NullableSmsOtpCreateRequest {
	return &NullableSmsOtpCreateRequest{value: val, isSet: true}
}

func (v NullableSmsOtpCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmsOtpCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


