/*
BSG SMS Gateway API

Comprehensive API for sending SMS, Viber messages, HLR/MNP requests and service management

API version: 1.0.0
Contact: support@bsg.world
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapiv1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HlrPricesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HlrPricesResponse{}

// HlrPricesResponse HLR pricing information for available destinations
type HlrPricesResponse struct {
	// Error code (0 = success)
	Error int32 `json:"error"`
	// Human-readable error description
	ErrorDescription string `json:"errorDescription"`
	// List of available HLR destinations with pricing
	Prices []HlrPricesResponsePricesInner `json:"prices"`
}

type _HlrPricesResponse HlrPricesResponse

// NewHlrPricesResponse instantiates a new HlrPricesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHlrPricesResponse(error_ int32, errorDescription string, prices []HlrPricesResponsePricesInner) *HlrPricesResponse {
	this := HlrPricesResponse{}
	this.Error = error_
	this.ErrorDescription = errorDescription
	this.Prices = prices
	return &this
}

// NewHlrPricesResponseWithDefaults instantiates a new HlrPricesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHlrPricesResponseWithDefaults() *HlrPricesResponse {
	this := HlrPricesResponse{}
	return &this
}

// GetError returns the Error field value
func (o *HlrPricesResponse) GetError() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *HlrPricesResponse) GetErrorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *HlrPricesResponse) SetError(v int32) {
	o.Error = v
}

// GetErrorDescription returns the ErrorDescription field value
func (o *HlrPricesResponse) GetErrorDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ErrorDescription
}

// GetErrorDescriptionOk returns a tuple with the ErrorDescription field value
// and a boolean to check if the value has been set.
func (o *HlrPricesResponse) GetErrorDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorDescription, true
}

// SetErrorDescription sets field value
func (o *HlrPricesResponse) SetErrorDescription(v string) {
	o.ErrorDescription = v
}

// GetPrices returns the Prices field value
func (o *HlrPricesResponse) GetPrices() []HlrPricesResponsePricesInner {
	if o == nil {
		var ret []HlrPricesResponsePricesInner
		return ret
	}

	return o.Prices
}

// GetPricesOk returns a tuple with the Prices field value
// and a boolean to check if the value has been set.
func (o *HlrPricesResponse) GetPricesOk() ([]HlrPricesResponsePricesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Prices, true
}

// SetPrices sets field value
func (o *HlrPricesResponse) SetPrices(v []HlrPricesResponsePricesInner) {
	o.Prices = v
}

func (o HlrPricesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HlrPricesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	toSerialize["errorDescription"] = o.ErrorDescription
	toSerialize["prices"] = o.Prices
	return toSerialize, nil
}

func (o *HlrPricesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
		"errorDescription",
		"prices",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHlrPricesResponse := _HlrPricesResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHlrPricesResponse)

	if err != nil {
		return err
	}

	*o = HlrPricesResponse(varHlrPricesResponse)

	return err
}

type NullableHlrPricesResponse struct {
	value *HlrPricesResponse
	isSet bool
}

func (v NullableHlrPricesResponse) Get() *HlrPricesResponse {
	return v.value
}

func (v *NullableHlrPricesResponse) Set(val *HlrPricesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHlrPricesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHlrPricesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHlrPricesResponse(val *HlrPricesResponse) *NullableHlrPricesResponse {
	return &NullableHlrPricesResponse{value: val, isSet: true}
}

func (v NullableHlrPricesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHlrPricesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


