/*
BSG SMS Gateway API

Comprehensive API for sending SMS, Viber messages, HLR/MNP requests and service management

API version: 1.0.0
Contact: support@bsg.world
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapiv1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ViberMessageStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViberMessageStatusResponse{}

// ViberMessageStatusResponse struct for ViberMessageStatusResponse
type ViberMessageStatusResponse struct {
	Error int32 `json:"error"`
	ErrorDescription string `json:"errorDescription"`
	Id *string `json:"id,omitempty"`
	Msisdn *string `json:"msisdn,omitempty"`
	Reference *string `json:"reference,omitempty"`
	TimeIn *string `json:"time_in,omitempty"`
	TimeSent NullableString `json:"time_sent,omitempty"`
	TimeDr NullableString `json:"time_dr,omitempty"`
	Status *string `json:"status,omitempty"`
	Price *float32 `json:"price,omitempty"`
	Currency *string `json:"currency,omitempty"`
}

type _ViberMessageStatusResponse ViberMessageStatusResponse

// NewViberMessageStatusResponse instantiates a new ViberMessageStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViberMessageStatusResponse(error_ int32, errorDescription string) *ViberMessageStatusResponse {
	this := ViberMessageStatusResponse{}
	this.Error = error_
	this.ErrorDescription = errorDescription
	return &this
}

// NewViberMessageStatusResponseWithDefaults instantiates a new ViberMessageStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViberMessageStatusResponseWithDefaults() *ViberMessageStatusResponse {
	this := ViberMessageStatusResponse{}
	return &this
}

// GetError returns the Error field value
func (o *ViberMessageStatusResponse) GetError() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *ViberMessageStatusResponse) GetErrorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *ViberMessageStatusResponse) SetError(v int32) {
	o.Error = v
}

// GetErrorDescription returns the ErrorDescription field value
func (o *ViberMessageStatusResponse) GetErrorDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ErrorDescription
}

// GetErrorDescriptionOk returns a tuple with the ErrorDescription field value
// and a boolean to check if the value has been set.
func (o *ViberMessageStatusResponse) GetErrorDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorDescription, true
}

// SetErrorDescription sets field value
func (o *ViberMessageStatusResponse) SetErrorDescription(v string) {
	o.ErrorDescription = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ViberMessageStatusResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViberMessageStatusResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ViberMessageStatusResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ViberMessageStatusResponse) SetId(v string) {
	o.Id = &v
}

// GetMsisdn returns the Msisdn field value if set, zero value otherwise.
func (o *ViberMessageStatusResponse) GetMsisdn() string {
	if o == nil || IsNil(o.Msisdn) {
		var ret string
		return ret
	}
	return *o.Msisdn
}

// GetMsisdnOk returns a tuple with the Msisdn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViberMessageStatusResponse) GetMsisdnOk() (*string, bool) {
	if o == nil || IsNil(o.Msisdn) {
		return nil, false
	}
	return o.Msisdn, true
}

// HasMsisdn returns a boolean if a field has been set.
func (o *ViberMessageStatusResponse) HasMsisdn() bool {
	if o != nil && !IsNil(o.Msisdn) {
		return true
	}

	return false
}

// SetMsisdn gets a reference to the given string and assigns it to the Msisdn field.
func (o *ViberMessageStatusResponse) SetMsisdn(v string) {
	o.Msisdn = &v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *ViberMessageStatusResponse) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViberMessageStatusResponse) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *ViberMessageStatusResponse) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *ViberMessageStatusResponse) SetReference(v string) {
	o.Reference = &v
}

// GetTimeIn returns the TimeIn field value if set, zero value otherwise.
func (o *ViberMessageStatusResponse) GetTimeIn() string {
	if o == nil || IsNil(o.TimeIn) {
		var ret string
		return ret
	}
	return *o.TimeIn
}

// GetTimeInOk returns a tuple with the TimeIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViberMessageStatusResponse) GetTimeInOk() (*string, bool) {
	if o == nil || IsNil(o.TimeIn) {
		return nil, false
	}
	return o.TimeIn, true
}

// HasTimeIn returns a boolean if a field has been set.
func (o *ViberMessageStatusResponse) HasTimeIn() bool {
	if o != nil && !IsNil(o.TimeIn) {
		return true
	}

	return false
}

// SetTimeIn gets a reference to the given string and assigns it to the TimeIn field.
func (o *ViberMessageStatusResponse) SetTimeIn(v string) {
	o.TimeIn = &v
}

// GetTimeSent returns the TimeSent field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ViberMessageStatusResponse) GetTimeSent() string {
	if o == nil || IsNil(o.TimeSent.Get()) {
		var ret string
		return ret
	}
	return *o.TimeSent.Get()
}

// GetTimeSentOk returns a tuple with the TimeSent field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ViberMessageStatusResponse) GetTimeSentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TimeSent.Get(), o.TimeSent.IsSet()
}

// HasTimeSent returns a boolean if a field has been set.
func (o *ViberMessageStatusResponse) HasTimeSent() bool {
	if o != nil && o.TimeSent.IsSet() {
		return true
	}

	return false
}

// SetTimeSent gets a reference to the given NullableString and assigns it to the TimeSent field.
func (o *ViberMessageStatusResponse) SetTimeSent(v string) {
	o.TimeSent.Set(&v)
}
// SetTimeSentNil sets the value for TimeSent to be an explicit nil
func (o *ViberMessageStatusResponse) SetTimeSentNil() {
	o.TimeSent.Set(nil)
}

// UnsetTimeSent ensures that no value is present for TimeSent, not even an explicit nil
func (o *ViberMessageStatusResponse) UnsetTimeSent() {
	o.TimeSent.Unset()
}

// GetTimeDr returns the TimeDr field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ViberMessageStatusResponse) GetTimeDr() string {
	if o == nil || IsNil(o.TimeDr.Get()) {
		var ret string
		return ret
	}
	return *o.TimeDr.Get()
}

// GetTimeDrOk returns a tuple with the TimeDr field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ViberMessageStatusResponse) GetTimeDrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TimeDr.Get(), o.TimeDr.IsSet()
}

// HasTimeDr returns a boolean if a field has been set.
func (o *ViberMessageStatusResponse) HasTimeDr() bool {
	if o != nil && o.TimeDr.IsSet() {
		return true
	}

	return false
}

// SetTimeDr gets a reference to the given NullableString and assigns it to the TimeDr field.
func (o *ViberMessageStatusResponse) SetTimeDr(v string) {
	o.TimeDr.Set(&v)
}
// SetTimeDrNil sets the value for TimeDr to be an explicit nil
func (o *ViberMessageStatusResponse) SetTimeDrNil() {
	o.TimeDr.Set(nil)
}

// UnsetTimeDr ensures that no value is present for TimeDr, not even an explicit nil
func (o *ViberMessageStatusResponse) UnsetTimeDr() {
	o.TimeDr.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ViberMessageStatusResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViberMessageStatusResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ViberMessageStatusResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ViberMessageStatusResponse) SetStatus(v string) {
	o.Status = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *ViberMessageStatusResponse) GetPrice() float32 {
	if o == nil || IsNil(o.Price) {
		var ret float32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViberMessageStatusResponse) GetPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *ViberMessageStatusResponse) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float32 and assigns it to the Price field.
func (o *ViberMessageStatusResponse) SetPrice(v float32) {
	o.Price = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *ViberMessageStatusResponse) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViberMessageStatusResponse) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *ViberMessageStatusResponse) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *ViberMessageStatusResponse) SetCurrency(v string) {
	o.Currency = &v
}

func (o ViberMessageStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViberMessageStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	toSerialize["errorDescription"] = o.ErrorDescription
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Msisdn) {
		toSerialize["msisdn"] = o.Msisdn
	}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	if !IsNil(o.TimeIn) {
		toSerialize["time_in"] = o.TimeIn
	}
	if o.TimeSent.IsSet() {
		toSerialize["time_sent"] = o.TimeSent.Get()
	}
	if o.TimeDr.IsSet() {
		toSerialize["time_dr"] = o.TimeDr.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	return toSerialize, nil
}

func (o *ViberMessageStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
		"errorDescription",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varViberMessageStatusResponse := _ViberMessageStatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varViberMessageStatusResponse)

	if err != nil {
		return err
	}

	*o = ViberMessageStatusResponse(varViberMessageStatusResponse)

	return err
}

type NullableViberMessageStatusResponse struct {
	value *ViberMessageStatusResponse
	isSet bool
}

func (v NullableViberMessageStatusResponse) Get() *ViberMessageStatusResponse {
	return v.value
}

func (v *NullableViberMessageStatusResponse) Set(val *ViberMessageStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableViberMessageStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableViberMessageStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViberMessageStatusResponse(val *ViberMessageStatusResponse) *NullableViberMessageStatusResponse {
	return &NullableViberMessageStatusResponse{value: val, isSet: true}
}

func (v NullableViberMessageStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViberMessageStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


