/*
BSG SMS Gateway API

Comprehensive API for sending SMS, Viber messages, HLR/MNP requests and service management

API version: 1.0.0
Contact: support@bsg.world
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapiv1

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// MnpCreateRequest - struct for MnpCreateRequest
type MnpCreateRequest struct {
	MnpCreateRequestOneOf *MnpCreateRequestOneOf
	MnpCreateRequestOneOf1 *MnpCreateRequestOneOf1
}

// MnpCreateRequestOneOfAsMnpCreateRequest is a convenience function that returns MnpCreateRequestOneOf wrapped in MnpCreateRequest
func MnpCreateRequestOneOfAsMnpCreateRequest(v *MnpCreateRequestOneOf) MnpCreateRequest {
	return MnpCreateRequest{
		MnpCreateRequestOneOf: v,
	}
}

// MnpCreateRequestOneOf1AsMnpCreateRequest is a convenience function that returns MnpCreateRequestOneOf1 wrapped in MnpCreateRequest
func MnpCreateRequestOneOf1AsMnpCreateRequest(v *MnpCreateRequestOneOf1) MnpCreateRequest {
	return MnpCreateRequest{
		MnpCreateRequestOneOf1: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *MnpCreateRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into MnpCreateRequestOneOf
	err = newStrictDecoder(data).Decode(&dst.MnpCreateRequestOneOf)
	if err == nil {
		jsonMnpCreateRequestOneOf, _ := json.Marshal(dst.MnpCreateRequestOneOf)
		if string(jsonMnpCreateRequestOneOf) == "{}" { // empty struct
			dst.MnpCreateRequestOneOf = nil
		} else {
			if err = validator.Validate(dst.MnpCreateRequestOneOf); err != nil {
				dst.MnpCreateRequestOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.MnpCreateRequestOneOf = nil
	}

	// try to unmarshal data into MnpCreateRequestOneOf1
	err = newStrictDecoder(data).Decode(&dst.MnpCreateRequestOneOf1)
	if err == nil {
		jsonMnpCreateRequestOneOf1, _ := json.Marshal(dst.MnpCreateRequestOneOf1)
		if string(jsonMnpCreateRequestOneOf1) == "{}" { // empty struct
			dst.MnpCreateRequestOneOf1 = nil
		} else {
			if err = validator.Validate(dst.MnpCreateRequestOneOf1); err != nil {
				dst.MnpCreateRequestOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.MnpCreateRequestOneOf1 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.MnpCreateRequestOneOf = nil
		dst.MnpCreateRequestOneOf1 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(MnpCreateRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(MnpCreateRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src MnpCreateRequest) MarshalJSON() ([]byte, error) {
	if src.MnpCreateRequestOneOf != nil {
		return json.Marshal(&src.MnpCreateRequestOneOf)
	}

	if src.MnpCreateRequestOneOf1 != nil {
		return json.Marshal(&src.MnpCreateRequestOneOf1)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *MnpCreateRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.MnpCreateRequestOneOf != nil {
		return obj.MnpCreateRequestOneOf
	}

	if obj.MnpCreateRequestOneOf1 != nil {
		return obj.MnpCreateRequestOneOf1
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj MnpCreateRequest) GetActualInstanceValue() (interface{}) {
	if obj.MnpCreateRequestOneOf != nil {
		return *obj.MnpCreateRequestOneOf
	}

	if obj.MnpCreateRequestOneOf1 != nil {
		return *obj.MnpCreateRequestOneOf1
	}

	// all schemas are nil
	return nil
}

type NullableMnpCreateRequest struct {
	value *MnpCreateRequest
	isSet bool
}

func (v NullableMnpCreateRequest) Get() *MnpCreateRequest {
	return v.value
}

func (v *NullableMnpCreateRequest) Set(val *MnpCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMnpCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMnpCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMnpCreateRequest(val *MnpCreateRequest) *NullableMnpCreateRequest {
	return &NullableMnpCreateRequest{value: val, isSet: true}
}

func (v NullableMnpCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMnpCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


