/*
BSG SMS Gateway API

Comprehensive API for sending SMS, Viber messages, HLR/MNP requests and service management

API version: 1.0.0
Contact: support@bsg.world
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapiv1

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MnpServiceStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MnpServiceStatusResponse{}

// MnpServiceStatusResponse MNP service status and usage statistics
type MnpServiceStatusResponse struct {
	// Error code (0 = success)
	Error int32 `json:"error"`
	// Human-readable error description
	ErrorDescription string `json:"errorDescription"`
	// Service status
	Status *string `json:"status,omitempty"`
	// Total number of MNP lookup requests
	TotalRequests *int32 `json:"total_requests,omitempty"`
	// Number of MNP lookup requests today
	TodayRequests *int32 `json:"today_requests,omitempty"`
}

type _MnpServiceStatusResponse MnpServiceStatusResponse

// NewMnpServiceStatusResponse instantiates a new MnpServiceStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMnpServiceStatusResponse(error_ int32, errorDescription string) *MnpServiceStatusResponse {
	this := MnpServiceStatusResponse{}
	this.Error = error_
	this.ErrorDescription = errorDescription
	return &this
}

// NewMnpServiceStatusResponseWithDefaults instantiates a new MnpServiceStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMnpServiceStatusResponseWithDefaults() *MnpServiceStatusResponse {
	this := MnpServiceStatusResponse{}
	return &this
}

// GetError returns the Error field value
func (o *MnpServiceStatusResponse) GetError() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *MnpServiceStatusResponse) GetErrorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *MnpServiceStatusResponse) SetError(v int32) {
	o.Error = v
}

// GetErrorDescription returns the ErrorDescription field value
func (o *MnpServiceStatusResponse) GetErrorDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ErrorDescription
}

// GetErrorDescriptionOk returns a tuple with the ErrorDescription field value
// and a boolean to check if the value has been set.
func (o *MnpServiceStatusResponse) GetErrorDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ErrorDescription, true
}

// SetErrorDescription sets field value
func (o *MnpServiceStatusResponse) SetErrorDescription(v string) {
	o.ErrorDescription = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *MnpServiceStatusResponse) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MnpServiceStatusResponse) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *MnpServiceStatusResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *MnpServiceStatusResponse) SetStatus(v string) {
	o.Status = &v
}

// GetTotalRequests returns the TotalRequests field value if set, zero value otherwise.
func (o *MnpServiceStatusResponse) GetTotalRequests() int32 {
	if o == nil || IsNil(o.TotalRequests) {
		var ret int32
		return ret
	}
	return *o.TotalRequests
}

// GetTotalRequestsOk returns a tuple with the TotalRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MnpServiceStatusResponse) GetTotalRequestsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalRequests) {
		return nil, false
	}
	return o.TotalRequests, true
}

// HasTotalRequests returns a boolean if a field has been set.
func (o *MnpServiceStatusResponse) HasTotalRequests() bool {
	if o != nil && !IsNil(o.TotalRequests) {
		return true
	}

	return false
}

// SetTotalRequests gets a reference to the given int32 and assigns it to the TotalRequests field.
func (o *MnpServiceStatusResponse) SetTotalRequests(v int32) {
	o.TotalRequests = &v
}

// GetTodayRequests returns the TodayRequests field value if set, zero value otherwise.
func (o *MnpServiceStatusResponse) GetTodayRequests() int32 {
	if o == nil || IsNil(o.TodayRequests) {
		var ret int32
		return ret
	}
	return *o.TodayRequests
}

// GetTodayRequestsOk returns a tuple with the TodayRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MnpServiceStatusResponse) GetTodayRequestsOk() (*int32, bool) {
	if o == nil || IsNil(o.TodayRequests) {
		return nil, false
	}
	return o.TodayRequests, true
}

// HasTodayRequests returns a boolean if a field has been set.
func (o *MnpServiceStatusResponse) HasTodayRequests() bool {
	if o != nil && !IsNil(o.TodayRequests) {
		return true
	}

	return false
}

// SetTodayRequests gets a reference to the given int32 and assigns it to the TodayRequests field.
func (o *MnpServiceStatusResponse) SetTodayRequests(v int32) {
	o.TodayRequests = &v
}

func (o MnpServiceStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MnpServiceStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	toSerialize["errorDescription"] = o.ErrorDescription
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.TotalRequests) {
		toSerialize["total_requests"] = o.TotalRequests
	}
	if !IsNil(o.TodayRequests) {
		toSerialize["today_requests"] = o.TodayRequests
	}
	return toSerialize, nil
}

func (o *MnpServiceStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
		"errorDescription",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMnpServiceStatusResponse := _MnpServiceStatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMnpServiceStatusResponse)

	if err != nil {
		return err
	}

	*o = MnpServiceStatusResponse(varMnpServiceStatusResponse)

	return err
}

type NullableMnpServiceStatusResponse struct {
	value *MnpServiceStatusResponse
	isSet bool
}

func (v NullableMnpServiceStatusResponse) Get() *MnpServiceStatusResponse {
	return v.value
}

func (v *NullableMnpServiceStatusResponse) Set(val *MnpServiceStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMnpServiceStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMnpServiceStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMnpServiceStatusResponse(val *MnpServiceStatusResponse) *NullableMnpServiceStatusResponse {
	return &NullableMnpServiceStatusResponse{value: val, isSet: true}
}

func (v NullableMnpServiceStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMnpServiceStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


