/*
BSG SMS Gateway API

Comprehensive API for sending SMS, Viber messages, HLR/MNP requests and service management

API version: 1.0.0
Contact: support@bsg.world
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapiv1

import (
	"encoding/json"
)

// checks if the ViberPriceCheckRequestMessagesInnerOptions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViberPriceCheckRequestMessagesInnerOptions{}

// ViberPriceCheckRequestMessagesInnerOptions Optional. Viber-specific options (buttons, images, SMS fallback)
type ViberPriceCheckRequestMessagesInnerOptions struct {
	Viber *ViberPriceCheckRequestMessagesInnerOptionsViber `json:"viber,omitempty"`
}

// NewViberPriceCheckRequestMessagesInnerOptions instantiates a new ViberPriceCheckRequestMessagesInnerOptions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViberPriceCheckRequestMessagesInnerOptions() *ViberPriceCheckRequestMessagesInnerOptions {
	this := ViberPriceCheckRequestMessagesInnerOptions{}
	return &this
}

// NewViberPriceCheckRequestMessagesInnerOptionsWithDefaults instantiates a new ViberPriceCheckRequestMessagesInnerOptions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViberPriceCheckRequestMessagesInnerOptionsWithDefaults() *ViberPriceCheckRequestMessagesInnerOptions {
	this := ViberPriceCheckRequestMessagesInnerOptions{}
	return &this
}

// GetViber returns the Viber field value if set, zero value otherwise.
func (o *ViberPriceCheckRequestMessagesInnerOptions) GetViber() ViberPriceCheckRequestMessagesInnerOptionsViber {
	if o == nil || IsNil(o.Viber) {
		var ret ViberPriceCheckRequestMessagesInnerOptionsViber
		return ret
	}
	return *o.Viber
}

// GetViberOk returns a tuple with the Viber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViberPriceCheckRequestMessagesInnerOptions) GetViberOk() (*ViberPriceCheckRequestMessagesInnerOptionsViber, bool) {
	if o == nil || IsNil(o.Viber) {
		return nil, false
	}
	return o.Viber, true
}

// HasViber returns a boolean if a field has been set.
func (o *ViberPriceCheckRequestMessagesInnerOptions) HasViber() bool {
	if o != nil && !IsNil(o.Viber) {
		return true
	}

	return false
}

// SetViber gets a reference to the given ViberPriceCheckRequestMessagesInnerOptionsViber and assigns it to the Viber field.
func (o *ViberPriceCheckRequestMessagesInnerOptions) SetViber(v ViberPriceCheckRequestMessagesInnerOptionsViber) {
	o.Viber = &v
}

func (o ViberPriceCheckRequestMessagesInnerOptions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViberPriceCheckRequestMessagesInnerOptions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Viber) {
		toSerialize["viber"] = o.Viber
	}
	return toSerialize, nil
}

type NullableViberPriceCheckRequestMessagesInnerOptions struct {
	value *ViberPriceCheckRequestMessagesInnerOptions
	isSet bool
}

func (v NullableViberPriceCheckRequestMessagesInnerOptions) Get() *ViberPriceCheckRequestMessagesInnerOptions {
	return v.value
}

func (v *NullableViberPriceCheckRequestMessagesInnerOptions) Set(val *ViberPriceCheckRequestMessagesInnerOptions) {
	v.value = val
	v.isSet = true
}

func (v NullableViberPriceCheckRequestMessagesInnerOptions) IsSet() bool {
	return v.isSet
}

func (v *NullableViberPriceCheckRequestMessagesInnerOptions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViberPriceCheckRequestMessagesInnerOptions(val *ViberPriceCheckRequestMessagesInnerOptions) *NullableViberPriceCheckRequestMessagesInnerOptions {
	return &NullableViberPriceCheckRequestMessagesInnerOptions{value: val, isSet: true}
}

func (v NullableViberPriceCheckRequestMessagesInnerOptions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViberPriceCheckRequestMessagesInnerOptions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


