/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ShortLink type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShortLink{}

// ShortLink struct for ShortLink
type ShortLink struct {
	// Target url
	Link string `json:"link"`
	// Word in message text that need to be replaced by generated short link
	Placeholder string `json:"placeholder"`
	// List of short domain identifiers to use for generate short links to follow at target url
	DomainIds []string `json:"domain_ids"`
	// Change domain each X messages
	ChangeDomainAfter NullableInt32 `json:"change_domain_after,omitempty"`
	// Add (https) protocol to short link or not
	Protocol *bool `json:"protocol,omitempty"`
}

type _ShortLink ShortLink

// NewShortLink instantiates a new ShortLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShortLink(link string, placeholder string, domainIds []string) *ShortLink {
	this := ShortLink{}
	this.Link = link
	this.Placeholder = placeholder
	this.DomainIds = domainIds
	var protocol bool = true
	this.Protocol = &protocol
	return &this
}

// NewShortLinkWithDefaults instantiates a new ShortLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShortLinkWithDefaults() *ShortLink {
	this := ShortLink{}
	var protocol bool = true
	this.Protocol = &protocol
	return &this
}

// GetLink returns the Link field value
func (o *ShortLink) GetLink() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Link
}

// GetLinkOk returns a tuple with the Link field value
// and a boolean to check if the value has been set.
func (o *ShortLink) GetLinkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Link, true
}

// SetLink sets field value
func (o *ShortLink) SetLink(v string) {
	o.Link = v
}

// GetPlaceholder returns the Placeholder field value
func (o *ShortLink) GetPlaceholder() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Placeholder
}

// GetPlaceholderOk returns a tuple with the Placeholder field value
// and a boolean to check if the value has been set.
func (o *ShortLink) GetPlaceholderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Placeholder, true
}

// SetPlaceholder sets field value
func (o *ShortLink) SetPlaceholder(v string) {
	o.Placeholder = v
}

// GetDomainIds returns the DomainIds field value
func (o *ShortLink) GetDomainIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.DomainIds
}

// GetDomainIdsOk returns a tuple with the DomainIds field value
// and a boolean to check if the value has been set.
func (o *ShortLink) GetDomainIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DomainIds, true
}

// SetDomainIds sets field value
func (o *ShortLink) SetDomainIds(v []string) {
	o.DomainIds = v
}

// GetChangeDomainAfter returns the ChangeDomainAfter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ShortLink) GetChangeDomainAfter() int32 {
	if o == nil || IsNil(o.ChangeDomainAfter.Get()) {
		var ret int32
		return ret
	}
	return *o.ChangeDomainAfter.Get()
}

// GetChangeDomainAfterOk returns a tuple with the ChangeDomainAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ShortLink) GetChangeDomainAfterOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ChangeDomainAfter.Get(), o.ChangeDomainAfter.IsSet()
}

// HasChangeDomainAfter returns a boolean if a field has been set.
func (o *ShortLink) HasChangeDomainAfter() bool {
	if o != nil && o.ChangeDomainAfter.IsSet() {
		return true
	}

	return false
}

// SetChangeDomainAfter gets a reference to the given NullableInt32 and assigns it to the ChangeDomainAfter field.
func (o *ShortLink) SetChangeDomainAfter(v int32) {
	o.ChangeDomainAfter.Set(&v)
}
// SetChangeDomainAfterNil sets the value for ChangeDomainAfter to be an explicit nil
func (o *ShortLink) SetChangeDomainAfterNil() {
	o.ChangeDomainAfter.Set(nil)
}

// UnsetChangeDomainAfter ensures that no value is present for ChangeDomainAfter, not even an explicit nil
func (o *ShortLink) UnsetChangeDomainAfter() {
	o.ChangeDomainAfter.Unset()
}

// GetProtocol returns the Protocol field value if set, zero value otherwise.
func (o *ShortLink) GetProtocol() bool {
	if o == nil || IsNil(o.Protocol) {
		var ret bool
		return ret
	}
	return *o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShortLink) GetProtocolOk() (*bool, bool) {
	if o == nil || IsNil(o.Protocol) {
		return nil, false
	}
	return o.Protocol, true
}

// HasProtocol returns a boolean if a field has been set.
func (o *ShortLink) HasProtocol() bool {
	if o != nil && !IsNil(o.Protocol) {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given bool and assigns it to the Protocol field.
func (o *ShortLink) SetProtocol(v bool) {
	o.Protocol = &v
}

func (o ShortLink) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShortLink) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["link"] = o.Link
	toSerialize["placeholder"] = o.Placeholder
	toSerialize["domain_ids"] = o.DomainIds
	if o.ChangeDomainAfter.IsSet() {
		toSerialize["change_domain_after"] = o.ChangeDomainAfter.Get()
	}
	if !IsNil(o.Protocol) {
		toSerialize["protocol"] = o.Protocol
	}
	return toSerialize, nil
}

func (o *ShortLink) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"link",
		"placeholder",
		"domain_ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varShortLink := _ShortLink{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varShortLink)

	if err != nil {
		return err
	}

	*o = ShortLink(varShortLink)

	return err
}

type NullableShortLink struct {
	value *ShortLink
	isSet bool
}

func (v NullableShortLink) Get() *ShortLink {
	return v.value
}

func (v *NullableShortLink) Set(val *ShortLink) {
	v.value = val
	v.isSet = true
}

func (v NullableShortLink) IsSet() bool {
	return v.isSet
}

func (v *NullableShortLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShortLink(val *ShortLink) *NullableShortLink {
	return &NullableShortLink{value: val, isSet: true}
}

func (v NullableShortLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShortLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


