/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
)

// checks if the StatisticsData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatisticsData{}

// StatisticsData struct for StatisticsData
type StatisticsData struct {
	Delivered *int32 `json:"delivered,omitempty"`
	Sent *int32 `json:"sent,omitempty"`
	Scheduled *int32 `json:"scheduled,omitempty"`
	Moderation *int32 `json:"moderation,omitempty"`
	Accepted *int32 `json:"accepted,omitempty"`
	Sending *int32 `json:"sending,omitempty"`
	Expired *int32 `json:"expired,omitempty"`
	Failed *int32 `json:"failed,omitempty"`
	Undelivered *int32 `json:"undelivered,omitempty"`
	Unknown *int32 `json:"unknown,omitempty"`
	Read *int32 `json:"read,omitempty"`
	NotViberUser *int32 `json:"not_viber_user,omitempty"`
	NotRcsUser *int32 `json:"not_rcs_user,omitempty"`
}

// NewStatisticsData instantiates a new StatisticsData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatisticsData() *StatisticsData {
	this := StatisticsData{}
	return &this
}

// NewStatisticsDataWithDefaults instantiates a new StatisticsData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatisticsDataWithDefaults() *StatisticsData {
	this := StatisticsData{}
	return &this
}

// GetDelivered returns the Delivered field value if set, zero value otherwise.
func (o *StatisticsData) GetDelivered() int32 {
	if o == nil || IsNil(o.Delivered) {
		var ret int32
		return ret
	}
	return *o.Delivered
}

// GetDeliveredOk returns a tuple with the Delivered field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsData) GetDeliveredOk() (*int32, bool) {
	if o == nil || IsNil(o.Delivered) {
		return nil, false
	}
	return o.Delivered, true
}

// HasDelivered returns a boolean if a field has been set.
func (o *StatisticsData) HasDelivered() bool {
	if o != nil && !IsNil(o.Delivered) {
		return true
	}

	return false
}

// SetDelivered gets a reference to the given int32 and assigns it to the Delivered field.
func (o *StatisticsData) SetDelivered(v int32) {
	o.Delivered = &v
}

// GetSent returns the Sent field value if set, zero value otherwise.
func (o *StatisticsData) GetSent() int32 {
	if o == nil || IsNil(o.Sent) {
		var ret int32
		return ret
	}
	return *o.Sent
}

// GetSentOk returns a tuple with the Sent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsData) GetSentOk() (*int32, bool) {
	if o == nil || IsNil(o.Sent) {
		return nil, false
	}
	return o.Sent, true
}

// HasSent returns a boolean if a field has been set.
func (o *StatisticsData) HasSent() bool {
	if o != nil && !IsNil(o.Sent) {
		return true
	}

	return false
}

// SetSent gets a reference to the given int32 and assigns it to the Sent field.
func (o *StatisticsData) SetSent(v int32) {
	o.Sent = &v
}

// GetScheduled returns the Scheduled field value if set, zero value otherwise.
func (o *StatisticsData) GetScheduled() int32 {
	if o == nil || IsNil(o.Scheduled) {
		var ret int32
		return ret
	}
	return *o.Scheduled
}

// GetScheduledOk returns a tuple with the Scheduled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsData) GetScheduledOk() (*int32, bool) {
	if o == nil || IsNil(o.Scheduled) {
		return nil, false
	}
	return o.Scheduled, true
}

// HasScheduled returns a boolean if a field has been set.
func (o *StatisticsData) HasScheduled() bool {
	if o != nil && !IsNil(o.Scheduled) {
		return true
	}

	return false
}

// SetScheduled gets a reference to the given int32 and assigns it to the Scheduled field.
func (o *StatisticsData) SetScheduled(v int32) {
	o.Scheduled = &v
}

// GetModeration returns the Moderation field value if set, zero value otherwise.
func (o *StatisticsData) GetModeration() int32 {
	if o == nil || IsNil(o.Moderation) {
		var ret int32
		return ret
	}
	return *o.Moderation
}

// GetModerationOk returns a tuple with the Moderation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsData) GetModerationOk() (*int32, bool) {
	if o == nil || IsNil(o.Moderation) {
		return nil, false
	}
	return o.Moderation, true
}

// HasModeration returns a boolean if a field has been set.
func (o *StatisticsData) HasModeration() bool {
	if o != nil && !IsNil(o.Moderation) {
		return true
	}

	return false
}

// SetModeration gets a reference to the given int32 and assigns it to the Moderation field.
func (o *StatisticsData) SetModeration(v int32) {
	o.Moderation = &v
}

// GetAccepted returns the Accepted field value if set, zero value otherwise.
func (o *StatisticsData) GetAccepted() int32 {
	if o == nil || IsNil(o.Accepted) {
		var ret int32
		return ret
	}
	return *o.Accepted
}

// GetAcceptedOk returns a tuple with the Accepted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsData) GetAcceptedOk() (*int32, bool) {
	if o == nil || IsNil(o.Accepted) {
		return nil, false
	}
	return o.Accepted, true
}

// HasAccepted returns a boolean if a field has been set.
func (o *StatisticsData) HasAccepted() bool {
	if o != nil && !IsNil(o.Accepted) {
		return true
	}

	return false
}

// SetAccepted gets a reference to the given int32 and assigns it to the Accepted field.
func (o *StatisticsData) SetAccepted(v int32) {
	o.Accepted = &v
}

// GetSending returns the Sending field value if set, zero value otherwise.
func (o *StatisticsData) GetSending() int32 {
	if o == nil || IsNil(o.Sending) {
		var ret int32
		return ret
	}
	return *o.Sending
}

// GetSendingOk returns a tuple with the Sending field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsData) GetSendingOk() (*int32, bool) {
	if o == nil || IsNil(o.Sending) {
		return nil, false
	}
	return o.Sending, true
}

// HasSending returns a boolean if a field has been set.
func (o *StatisticsData) HasSending() bool {
	if o != nil && !IsNil(o.Sending) {
		return true
	}

	return false
}

// SetSending gets a reference to the given int32 and assigns it to the Sending field.
func (o *StatisticsData) SetSending(v int32) {
	o.Sending = &v
}

// GetExpired returns the Expired field value if set, zero value otherwise.
func (o *StatisticsData) GetExpired() int32 {
	if o == nil || IsNil(o.Expired) {
		var ret int32
		return ret
	}
	return *o.Expired
}

// GetExpiredOk returns a tuple with the Expired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsData) GetExpiredOk() (*int32, bool) {
	if o == nil || IsNil(o.Expired) {
		return nil, false
	}
	return o.Expired, true
}

// HasExpired returns a boolean if a field has been set.
func (o *StatisticsData) HasExpired() bool {
	if o != nil && !IsNil(o.Expired) {
		return true
	}

	return false
}

// SetExpired gets a reference to the given int32 and assigns it to the Expired field.
func (o *StatisticsData) SetExpired(v int32) {
	o.Expired = &v
}

// GetFailed returns the Failed field value if set, zero value otherwise.
func (o *StatisticsData) GetFailed() int32 {
	if o == nil || IsNil(o.Failed) {
		var ret int32
		return ret
	}
	return *o.Failed
}

// GetFailedOk returns a tuple with the Failed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsData) GetFailedOk() (*int32, bool) {
	if o == nil || IsNil(o.Failed) {
		return nil, false
	}
	return o.Failed, true
}

// HasFailed returns a boolean if a field has been set.
func (o *StatisticsData) HasFailed() bool {
	if o != nil && !IsNil(o.Failed) {
		return true
	}

	return false
}

// SetFailed gets a reference to the given int32 and assigns it to the Failed field.
func (o *StatisticsData) SetFailed(v int32) {
	o.Failed = &v
}

// GetUndelivered returns the Undelivered field value if set, zero value otherwise.
func (o *StatisticsData) GetUndelivered() int32 {
	if o == nil || IsNil(o.Undelivered) {
		var ret int32
		return ret
	}
	return *o.Undelivered
}

// GetUndeliveredOk returns a tuple with the Undelivered field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsData) GetUndeliveredOk() (*int32, bool) {
	if o == nil || IsNil(o.Undelivered) {
		return nil, false
	}
	return o.Undelivered, true
}

// HasUndelivered returns a boolean if a field has been set.
func (o *StatisticsData) HasUndelivered() bool {
	if o != nil && !IsNil(o.Undelivered) {
		return true
	}

	return false
}

// SetUndelivered gets a reference to the given int32 and assigns it to the Undelivered field.
func (o *StatisticsData) SetUndelivered(v int32) {
	o.Undelivered = &v
}

// GetUnknown returns the Unknown field value if set, zero value otherwise.
func (o *StatisticsData) GetUnknown() int32 {
	if o == nil || IsNil(o.Unknown) {
		var ret int32
		return ret
	}
	return *o.Unknown
}

// GetUnknownOk returns a tuple with the Unknown field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsData) GetUnknownOk() (*int32, bool) {
	if o == nil || IsNil(o.Unknown) {
		return nil, false
	}
	return o.Unknown, true
}

// HasUnknown returns a boolean if a field has been set.
func (o *StatisticsData) HasUnknown() bool {
	if o != nil && !IsNil(o.Unknown) {
		return true
	}

	return false
}

// SetUnknown gets a reference to the given int32 and assigns it to the Unknown field.
func (o *StatisticsData) SetUnknown(v int32) {
	o.Unknown = &v
}

// GetRead returns the Read field value if set, zero value otherwise.
func (o *StatisticsData) GetRead() int32 {
	if o == nil || IsNil(o.Read) {
		var ret int32
		return ret
	}
	return *o.Read
}

// GetReadOk returns a tuple with the Read field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsData) GetReadOk() (*int32, bool) {
	if o == nil || IsNil(o.Read) {
		return nil, false
	}
	return o.Read, true
}

// HasRead returns a boolean if a field has been set.
func (o *StatisticsData) HasRead() bool {
	if o != nil && !IsNil(o.Read) {
		return true
	}

	return false
}

// SetRead gets a reference to the given int32 and assigns it to the Read field.
func (o *StatisticsData) SetRead(v int32) {
	o.Read = &v
}

// GetNotViberUser returns the NotViberUser field value if set, zero value otherwise.
func (o *StatisticsData) GetNotViberUser() int32 {
	if o == nil || IsNil(o.NotViberUser) {
		var ret int32
		return ret
	}
	return *o.NotViberUser
}

// GetNotViberUserOk returns a tuple with the NotViberUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsData) GetNotViberUserOk() (*int32, bool) {
	if o == nil || IsNil(o.NotViberUser) {
		return nil, false
	}
	return o.NotViberUser, true
}

// HasNotViberUser returns a boolean if a field has been set.
func (o *StatisticsData) HasNotViberUser() bool {
	if o != nil && !IsNil(o.NotViberUser) {
		return true
	}

	return false
}

// SetNotViberUser gets a reference to the given int32 and assigns it to the NotViberUser field.
func (o *StatisticsData) SetNotViberUser(v int32) {
	o.NotViberUser = &v
}

// GetNotRcsUser returns the NotRcsUser field value if set, zero value otherwise.
func (o *StatisticsData) GetNotRcsUser() int32 {
	if o == nil || IsNil(o.NotRcsUser) {
		var ret int32
		return ret
	}
	return *o.NotRcsUser
}

// GetNotRcsUserOk returns a tuple with the NotRcsUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsData) GetNotRcsUserOk() (*int32, bool) {
	if o == nil || IsNil(o.NotRcsUser) {
		return nil, false
	}
	return o.NotRcsUser, true
}

// HasNotRcsUser returns a boolean if a field has been set.
func (o *StatisticsData) HasNotRcsUser() bool {
	if o != nil && !IsNil(o.NotRcsUser) {
		return true
	}

	return false
}

// SetNotRcsUser gets a reference to the given int32 and assigns it to the NotRcsUser field.
func (o *StatisticsData) SetNotRcsUser(v int32) {
	o.NotRcsUser = &v
}

func (o StatisticsData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatisticsData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Delivered) {
		toSerialize["delivered"] = o.Delivered
	}
	if !IsNil(o.Sent) {
		toSerialize["sent"] = o.Sent
	}
	if !IsNil(o.Scheduled) {
		toSerialize["scheduled"] = o.Scheduled
	}
	if !IsNil(o.Moderation) {
		toSerialize["moderation"] = o.Moderation
	}
	if !IsNil(o.Accepted) {
		toSerialize["accepted"] = o.Accepted
	}
	if !IsNil(o.Sending) {
		toSerialize["sending"] = o.Sending
	}
	if !IsNil(o.Expired) {
		toSerialize["expired"] = o.Expired
	}
	if !IsNil(o.Failed) {
		toSerialize["failed"] = o.Failed
	}
	if !IsNil(o.Undelivered) {
		toSerialize["undelivered"] = o.Undelivered
	}
	if !IsNil(o.Unknown) {
		toSerialize["unknown"] = o.Unknown
	}
	if !IsNil(o.Read) {
		toSerialize["read"] = o.Read
	}
	if !IsNil(o.NotViberUser) {
		toSerialize["not_viber_user"] = o.NotViberUser
	}
	if !IsNil(o.NotRcsUser) {
		toSerialize["not_rcs_user"] = o.NotRcsUser
	}
	return toSerialize, nil
}

type NullableStatisticsData struct {
	value *StatisticsData
	isSet bool
}

func (v NullableStatisticsData) Get() *StatisticsData {
	return v.value
}

func (v *NullableStatisticsData) Set(val *StatisticsData) {
	v.value = val
	v.isSet = true
}

func (v NullableStatisticsData) IsSet() bool {
	return v.isSet
}

func (v *NullableStatisticsData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatisticsData(val *StatisticsData) *NullableStatisticsData {
	return &NullableStatisticsData{value: val, isSet: true}
}

func (v NullableStatisticsData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatisticsData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


