/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
	"fmt"
)

// ShortLinkStatus If original link is used at first time it may not pass the moderation automatically. Be careful only link in **active** status can be used for redirect!*
type ShortLinkStatus string

// List of short_link_status
const (
	ACTIVE ShortLinkStatus = "active"
	BLOCKED ShortLinkStatus = "blocked"
	NOT_PAID ShortLinkStatus = "not_paid"
	DELETED ShortLinkStatus = "deleted"
	PROBLEM ShortLinkStatus = "problem"
)

// All allowed values of ShortLinkStatus enum
var AllowedShortLinkStatusEnumValues = []ShortLinkStatus{
	"active",
	"blocked",
	"not_paid",
	"deleted",
	"problem",
}

func (v *ShortLinkStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ShortLinkStatus(value)
	for _, existing := range AllowedShortLinkStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ShortLinkStatus", value)
}

// NewShortLinkStatusFromValue returns a pointer to a valid ShortLinkStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewShortLinkStatusFromValue(v string) (*ShortLinkStatus, error) {
	ev := ShortLinkStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ShortLinkStatus: valid values are %v", v, AllowedShortLinkStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ShortLinkStatus) IsValid() bool {
	for _, existing := range AllowedShortLinkStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to short_link_status value
func (v ShortLinkStatus) Ptr() *ShortLinkStatus {
	return &v
}

type NullableShortLinkStatus struct {
	value *ShortLinkStatus
	isSet bool
}

func (v NullableShortLinkStatus) Get() *ShortLinkStatus {
	return v.value
}

func (v *NullableShortLinkStatus) Set(val *ShortLinkStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableShortLinkStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableShortLinkStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShortLinkStatus(val *ShortLinkStatus) *NullableShortLinkStatus {
	return &NullableShortLinkStatus{value: val, isSet: true}
}

func (v NullableShortLinkStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShortLinkStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

