/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
)

// checks if the ContactListUpdate422Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContactListUpdate422Response{}

// ContactListUpdate422Response struct for ContactListUpdate422Response
type ContactListUpdate422Response struct {
	// It may be one of the following errors:  - **Contact group is not found** - There is not contact list with this id, use correct contact list id - **Contact group is already exists** - There are exists another contact list with the same **name**, use different name for new list   
	Message *string `json:"message,omitempty"`
	// errors
	Errors []interface{} `json:"errors,omitempty"`
}

// NewContactListUpdate422Response instantiates a new ContactListUpdate422Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContactListUpdate422Response() *ContactListUpdate422Response {
	this := ContactListUpdate422Response{}
	return &this
}

// NewContactListUpdate422ResponseWithDefaults instantiates a new ContactListUpdate422Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContactListUpdate422ResponseWithDefaults() *ContactListUpdate422Response {
	this := ContactListUpdate422Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ContactListUpdate422Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactListUpdate422Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ContactListUpdate422Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ContactListUpdate422Response) SetMessage(v string) {
	o.Message = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *ContactListUpdate422Response) GetErrors() []interface{} {
	if o == nil || IsNil(o.Errors) {
		var ret []interface{}
		return ret
	}
	return o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactListUpdate422Response) GetErrorsOk() ([]interface{}, bool) {
	if o == nil || IsNil(o.Errors) {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *ContactListUpdate422Response) HasErrors() bool {
	if o != nil && !IsNil(o.Errors) {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []interface{} and assigns it to the Errors field.
func (o *ContactListUpdate422Response) SetErrors(v []interface{}) {
	o.Errors = v
}

func (o ContactListUpdate422Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContactListUpdate422Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Errors) {
		toSerialize["errors"] = o.Errors
	}
	return toSerialize, nil
}

type NullableContactListUpdate422Response struct {
	value *ContactListUpdate422Response
	isSet bool
}

func (v NullableContactListUpdate422Response) Get() *ContactListUpdate422Response {
	return v.value
}

func (v *NullableContactListUpdate422Response) Set(val *ContactListUpdate422Response) {
	v.value = val
	v.isSet = true
}

func (v NullableContactListUpdate422Response) IsSet() bool {
	return v.isSet
}

func (v *NullableContactListUpdate422Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContactListUpdate422Response(val *ContactListUpdate422Response) *NullableContactListUpdate422Response {
	return &NullableContactListUpdate422Response{value: val, isSet: true}
}

func (v NullableContactListUpdate422Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContactListUpdate422Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


