/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
	"time"
)

// checks if the TwoFactorAuthenticationSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TwoFactorAuthenticationSchema{}

// TwoFactorAuthenticationSchema struct for TwoFactorAuthenticationSchema
type TwoFactorAuthenticationSchema struct {
	// The ID of the generated authentication
	Id *string `json:"id,omitempty"`
	// Number of the recipient of the message with a one-time code
	Recipient *string `json:"recipient,omitempty"`
	Status *OtpStatus `json:"status,omitempty"`
	Channel *OtpChannel `json:"channel,omitempty"`
	// Sender name
	Sender *string `json:"sender,omitempty"`
	// SMS sender name
	SenderAlt NullableString `json:"sender_alt,omitempty"`
	// Message text.
	MessageText *string `json:"message_text,omitempty"`
	// OTP expiration date
	CodeLifetime *int32 `json:"code_lifetime,omitempty"`
	// The number of OTP check attempts
	CodeMaxTries *int32 `json:"code_max_tries,omitempty"`
	// The number of digits in the OTP
	CodeDigits *int32 `json:"code_digits,omitempty"`
	// Authentication cost. At the time of creating the authentication, 0 is indicated
	Price *float32 `json:"price,omitempty"`
	// The three-letter code of the currency in which the value is indicated. Corresponds to the user’s account currency
	Currency *string `json:"currency,omitempty"`
	// The country code of the recipient of the one-time password according to the ISO 3166-1 alpha-2 standard
	CountryCode *string `json:"country_code,omitempty"`
	// Date and time when the authentication expires in ISO 8601 format
	ExpiredAt *time.Time `json:"expired_at,omitempty"`
	// The date and time of the authentication session were created in ISO 8601 format
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// Date and time when the authentication session was closed. At the time of creating the authentication, the value “null” is indicated
	FinishedAt *time.Time `json:"finished_at,omitempty"`
}

// NewTwoFactorAuthenticationSchema instantiates a new TwoFactorAuthenticationSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTwoFactorAuthenticationSchema() *TwoFactorAuthenticationSchema {
	this := TwoFactorAuthenticationSchema{}
	return &this
}

// NewTwoFactorAuthenticationSchemaWithDefaults instantiates a new TwoFactorAuthenticationSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTwoFactorAuthenticationSchemaWithDefaults() *TwoFactorAuthenticationSchema {
	this := TwoFactorAuthenticationSchema{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TwoFactorAuthenticationSchema) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFactorAuthenticationSchema) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TwoFactorAuthenticationSchema) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TwoFactorAuthenticationSchema) SetId(v string) {
	o.Id = &v
}

// GetRecipient returns the Recipient field value if set, zero value otherwise.
func (o *TwoFactorAuthenticationSchema) GetRecipient() string {
	if o == nil || IsNil(o.Recipient) {
		var ret string
		return ret
	}
	return *o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFactorAuthenticationSchema) GetRecipientOk() (*string, bool) {
	if o == nil || IsNil(o.Recipient) {
		return nil, false
	}
	return o.Recipient, true
}

// HasRecipient returns a boolean if a field has been set.
func (o *TwoFactorAuthenticationSchema) HasRecipient() bool {
	if o != nil && !IsNil(o.Recipient) {
		return true
	}

	return false
}

// SetRecipient gets a reference to the given string and assigns it to the Recipient field.
func (o *TwoFactorAuthenticationSchema) SetRecipient(v string) {
	o.Recipient = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *TwoFactorAuthenticationSchema) GetStatus() OtpStatus {
	if o == nil || IsNil(o.Status) {
		var ret OtpStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFactorAuthenticationSchema) GetStatusOk() (*OtpStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *TwoFactorAuthenticationSchema) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given OtpStatus and assigns it to the Status field.
func (o *TwoFactorAuthenticationSchema) SetStatus(v OtpStatus) {
	o.Status = &v
}

// GetChannel returns the Channel field value if set, zero value otherwise.
func (o *TwoFactorAuthenticationSchema) GetChannel() OtpChannel {
	if o == nil || IsNil(o.Channel) {
		var ret OtpChannel
		return ret
	}
	return *o.Channel
}

// GetChannelOk returns a tuple with the Channel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFactorAuthenticationSchema) GetChannelOk() (*OtpChannel, bool) {
	if o == nil || IsNil(o.Channel) {
		return nil, false
	}
	return o.Channel, true
}

// HasChannel returns a boolean if a field has been set.
func (o *TwoFactorAuthenticationSchema) HasChannel() bool {
	if o != nil && !IsNil(o.Channel) {
		return true
	}

	return false
}

// SetChannel gets a reference to the given OtpChannel and assigns it to the Channel field.
func (o *TwoFactorAuthenticationSchema) SetChannel(v OtpChannel) {
	o.Channel = &v
}

// GetSender returns the Sender field value if set, zero value otherwise.
func (o *TwoFactorAuthenticationSchema) GetSender() string {
	if o == nil || IsNil(o.Sender) {
		var ret string
		return ret
	}
	return *o.Sender
}

// GetSenderOk returns a tuple with the Sender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFactorAuthenticationSchema) GetSenderOk() (*string, bool) {
	if o == nil || IsNil(o.Sender) {
		return nil, false
	}
	return o.Sender, true
}

// HasSender returns a boolean if a field has been set.
func (o *TwoFactorAuthenticationSchema) HasSender() bool {
	if o != nil && !IsNil(o.Sender) {
		return true
	}

	return false
}

// SetSender gets a reference to the given string and assigns it to the Sender field.
func (o *TwoFactorAuthenticationSchema) SetSender(v string) {
	o.Sender = &v
}

// GetSenderAlt returns the SenderAlt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TwoFactorAuthenticationSchema) GetSenderAlt() string {
	if o == nil || IsNil(o.SenderAlt.Get()) {
		var ret string
		return ret
	}
	return *o.SenderAlt.Get()
}

// GetSenderAltOk returns a tuple with the SenderAlt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TwoFactorAuthenticationSchema) GetSenderAltOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SenderAlt.Get(), o.SenderAlt.IsSet()
}

// HasSenderAlt returns a boolean if a field has been set.
func (o *TwoFactorAuthenticationSchema) HasSenderAlt() bool {
	if o != nil && o.SenderAlt.IsSet() {
		return true
	}

	return false
}

// SetSenderAlt gets a reference to the given NullableString and assigns it to the SenderAlt field.
func (o *TwoFactorAuthenticationSchema) SetSenderAlt(v string) {
	o.SenderAlt.Set(&v)
}
// SetSenderAltNil sets the value for SenderAlt to be an explicit nil
func (o *TwoFactorAuthenticationSchema) SetSenderAltNil() {
	o.SenderAlt.Set(nil)
}

// UnsetSenderAlt ensures that no value is present for SenderAlt, not even an explicit nil
func (o *TwoFactorAuthenticationSchema) UnsetSenderAlt() {
	o.SenderAlt.Unset()
}

// GetMessageText returns the MessageText field value if set, zero value otherwise.
func (o *TwoFactorAuthenticationSchema) GetMessageText() string {
	if o == nil || IsNil(o.MessageText) {
		var ret string
		return ret
	}
	return *o.MessageText
}

// GetMessageTextOk returns a tuple with the MessageText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFactorAuthenticationSchema) GetMessageTextOk() (*string, bool) {
	if o == nil || IsNil(o.MessageText) {
		return nil, false
	}
	return o.MessageText, true
}

// HasMessageText returns a boolean if a field has been set.
func (o *TwoFactorAuthenticationSchema) HasMessageText() bool {
	if o != nil && !IsNil(o.MessageText) {
		return true
	}

	return false
}

// SetMessageText gets a reference to the given string and assigns it to the MessageText field.
func (o *TwoFactorAuthenticationSchema) SetMessageText(v string) {
	o.MessageText = &v
}

// GetCodeLifetime returns the CodeLifetime field value if set, zero value otherwise.
func (o *TwoFactorAuthenticationSchema) GetCodeLifetime() int32 {
	if o == nil || IsNil(o.CodeLifetime) {
		var ret int32
		return ret
	}
	return *o.CodeLifetime
}

// GetCodeLifetimeOk returns a tuple with the CodeLifetime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFactorAuthenticationSchema) GetCodeLifetimeOk() (*int32, bool) {
	if o == nil || IsNil(o.CodeLifetime) {
		return nil, false
	}
	return o.CodeLifetime, true
}

// HasCodeLifetime returns a boolean if a field has been set.
func (o *TwoFactorAuthenticationSchema) HasCodeLifetime() bool {
	if o != nil && !IsNil(o.CodeLifetime) {
		return true
	}

	return false
}

// SetCodeLifetime gets a reference to the given int32 and assigns it to the CodeLifetime field.
func (o *TwoFactorAuthenticationSchema) SetCodeLifetime(v int32) {
	o.CodeLifetime = &v
}

// GetCodeMaxTries returns the CodeMaxTries field value if set, zero value otherwise.
func (o *TwoFactorAuthenticationSchema) GetCodeMaxTries() int32 {
	if o == nil || IsNil(o.CodeMaxTries) {
		var ret int32
		return ret
	}
	return *o.CodeMaxTries
}

// GetCodeMaxTriesOk returns a tuple with the CodeMaxTries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFactorAuthenticationSchema) GetCodeMaxTriesOk() (*int32, bool) {
	if o == nil || IsNil(o.CodeMaxTries) {
		return nil, false
	}
	return o.CodeMaxTries, true
}

// HasCodeMaxTries returns a boolean if a field has been set.
func (o *TwoFactorAuthenticationSchema) HasCodeMaxTries() bool {
	if o != nil && !IsNil(o.CodeMaxTries) {
		return true
	}

	return false
}

// SetCodeMaxTries gets a reference to the given int32 and assigns it to the CodeMaxTries field.
func (o *TwoFactorAuthenticationSchema) SetCodeMaxTries(v int32) {
	o.CodeMaxTries = &v
}

// GetCodeDigits returns the CodeDigits field value if set, zero value otherwise.
func (o *TwoFactorAuthenticationSchema) GetCodeDigits() int32 {
	if o == nil || IsNil(o.CodeDigits) {
		var ret int32
		return ret
	}
	return *o.CodeDigits
}

// GetCodeDigitsOk returns a tuple with the CodeDigits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFactorAuthenticationSchema) GetCodeDigitsOk() (*int32, bool) {
	if o == nil || IsNil(o.CodeDigits) {
		return nil, false
	}
	return o.CodeDigits, true
}

// HasCodeDigits returns a boolean if a field has been set.
func (o *TwoFactorAuthenticationSchema) HasCodeDigits() bool {
	if o != nil && !IsNil(o.CodeDigits) {
		return true
	}

	return false
}

// SetCodeDigits gets a reference to the given int32 and assigns it to the CodeDigits field.
func (o *TwoFactorAuthenticationSchema) SetCodeDigits(v int32) {
	o.CodeDigits = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *TwoFactorAuthenticationSchema) GetPrice() float32 {
	if o == nil || IsNil(o.Price) {
		var ret float32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFactorAuthenticationSchema) GetPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *TwoFactorAuthenticationSchema) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float32 and assigns it to the Price field.
func (o *TwoFactorAuthenticationSchema) SetPrice(v float32) {
	o.Price = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *TwoFactorAuthenticationSchema) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFactorAuthenticationSchema) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *TwoFactorAuthenticationSchema) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *TwoFactorAuthenticationSchema) SetCurrency(v string) {
	o.Currency = &v
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise.
func (o *TwoFactorAuthenticationSchema) GetCountryCode() string {
	if o == nil || IsNil(o.CountryCode) {
		var ret string
		return ret
	}
	return *o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFactorAuthenticationSchema) GetCountryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CountryCode) {
		return nil, false
	}
	return o.CountryCode, true
}

// HasCountryCode returns a boolean if a field has been set.
func (o *TwoFactorAuthenticationSchema) HasCountryCode() bool {
	if o != nil && !IsNil(o.CountryCode) {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given string and assigns it to the CountryCode field.
func (o *TwoFactorAuthenticationSchema) SetCountryCode(v string) {
	o.CountryCode = &v
}

// GetExpiredAt returns the ExpiredAt field value if set, zero value otherwise.
func (o *TwoFactorAuthenticationSchema) GetExpiredAt() time.Time {
	if o == nil || IsNil(o.ExpiredAt) {
		var ret time.Time
		return ret
	}
	return *o.ExpiredAt
}

// GetExpiredAtOk returns a tuple with the ExpiredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFactorAuthenticationSchema) GetExpiredAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiredAt) {
		return nil, false
	}
	return o.ExpiredAt, true
}

// HasExpiredAt returns a boolean if a field has been set.
func (o *TwoFactorAuthenticationSchema) HasExpiredAt() bool {
	if o != nil && !IsNil(o.ExpiredAt) {
		return true
	}

	return false
}

// SetExpiredAt gets a reference to the given time.Time and assigns it to the ExpiredAt field.
func (o *TwoFactorAuthenticationSchema) SetExpiredAt(v time.Time) {
	o.ExpiredAt = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *TwoFactorAuthenticationSchema) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFactorAuthenticationSchema) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *TwoFactorAuthenticationSchema) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *TwoFactorAuthenticationSchema) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetFinishedAt returns the FinishedAt field value if set, zero value otherwise.
func (o *TwoFactorAuthenticationSchema) GetFinishedAt() time.Time {
	if o == nil || IsNil(o.FinishedAt) {
		var ret time.Time
		return ret
	}
	return *o.FinishedAt
}

// GetFinishedAtOk returns a tuple with the FinishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TwoFactorAuthenticationSchema) GetFinishedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.FinishedAt) {
		return nil, false
	}
	return o.FinishedAt, true
}

// HasFinishedAt returns a boolean if a field has been set.
func (o *TwoFactorAuthenticationSchema) HasFinishedAt() bool {
	if o != nil && !IsNil(o.FinishedAt) {
		return true
	}

	return false
}

// SetFinishedAt gets a reference to the given time.Time and assigns it to the FinishedAt field.
func (o *TwoFactorAuthenticationSchema) SetFinishedAt(v time.Time) {
	o.FinishedAt = &v
}

func (o TwoFactorAuthenticationSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TwoFactorAuthenticationSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Recipient) {
		toSerialize["recipient"] = o.Recipient
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Channel) {
		toSerialize["channel"] = o.Channel
	}
	if !IsNil(o.Sender) {
		toSerialize["sender"] = o.Sender
	}
	if o.SenderAlt.IsSet() {
		toSerialize["sender_alt"] = o.SenderAlt.Get()
	}
	if !IsNil(o.MessageText) {
		toSerialize["message_text"] = o.MessageText
	}
	if !IsNil(o.CodeLifetime) {
		toSerialize["code_lifetime"] = o.CodeLifetime
	}
	if !IsNil(o.CodeMaxTries) {
		toSerialize["code_max_tries"] = o.CodeMaxTries
	}
	if !IsNil(o.CodeDigits) {
		toSerialize["code_digits"] = o.CodeDigits
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.CountryCode) {
		toSerialize["country_code"] = o.CountryCode
	}
	if !IsNil(o.ExpiredAt) {
		toSerialize["expired_at"] = o.ExpiredAt
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.FinishedAt) {
		toSerialize["finished_at"] = o.FinishedAt
	}
	return toSerialize, nil
}

type NullableTwoFactorAuthenticationSchema struct {
	value *TwoFactorAuthenticationSchema
	isSet bool
}

func (v NullableTwoFactorAuthenticationSchema) Get() *TwoFactorAuthenticationSchema {
	return v.value
}

func (v *NullableTwoFactorAuthenticationSchema) Set(val *TwoFactorAuthenticationSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableTwoFactorAuthenticationSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableTwoFactorAuthenticationSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTwoFactorAuthenticationSchema(val *TwoFactorAuthenticationSchema) *NullableTwoFactorAuthenticationSchema {
	return &NullableTwoFactorAuthenticationSchema{value: val, isSet: true}
}

func (v NullableTwoFactorAuthenticationSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTwoFactorAuthenticationSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


