/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RcsMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RcsMessage{}

// RcsMessage struct for RcsMessage
type RcsMessage struct {
	Phone Phone `json:"phone"`
	Sender string `json:"sender"`
	Options Options `json:"options"`
	AlternativeChannel *AlternativeChannel `json:"alternative_channel,omitempty"`
	// Link to get the delivery status of messages. If this parameter is specified in the method, it will take precedence over the value specified in the “Callback URL” field in the Personal Area.
	CallbackUrl interface{} `json:"callback_url,omitempty"`
	TariffCode NullableInt32 `json:"tariff_code,omitempty"`
	// Validity period in seconds. If not set, field \"validity\" is used
	ValiditySeconds NullableInt32 `json:"validity_seconds,omitempty"`
	// Validity period in hours
	Validity NullableInt32 `json:"validity,omitempty"`
	AddToContactBook *bool `json:"add_to_contact_book,omitempty"`
	CheckStopList *bool `json:"check_stop_list,omitempty"`
}

type _RcsMessage RcsMessage

// NewRcsMessage instantiates a new RcsMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRcsMessage(phone Phone, sender string, options Options) *RcsMessage {
	this := RcsMessage{}
	this.Phone = phone
	this.Sender = sender
	this.Options = options
	var validity int32 = 72
	this.Validity = *NewNullableInt32(&validity)
	var addToContactBook bool = true
	this.AddToContactBook = &addToContactBook
	var checkStopList bool = true
	this.CheckStopList = &checkStopList
	return &this
}

// NewRcsMessageWithDefaults instantiates a new RcsMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRcsMessageWithDefaults() *RcsMessage {
	this := RcsMessage{}
	var validity int32 = 72
	this.Validity = *NewNullableInt32(&validity)
	var addToContactBook bool = true
	this.AddToContactBook = &addToContactBook
	var checkStopList bool = true
	this.CheckStopList = &checkStopList
	return &this
}

// GetPhone returns the Phone field value
func (o *RcsMessage) GetPhone() Phone {
	if o == nil {
		var ret Phone
		return ret
	}

	return o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value
// and a boolean to check if the value has been set.
func (o *RcsMessage) GetPhoneOk() (*Phone, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phone, true
}

// SetPhone sets field value
func (o *RcsMessage) SetPhone(v Phone) {
	o.Phone = v
}

// GetSender returns the Sender field value
func (o *RcsMessage) GetSender() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sender
}

// GetSenderOk returns a tuple with the Sender field value
// and a boolean to check if the value has been set.
func (o *RcsMessage) GetSenderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sender, true
}

// SetSender sets field value
func (o *RcsMessage) SetSender(v string) {
	o.Sender = v
}

// GetOptions returns the Options field value
func (o *RcsMessage) GetOptions() Options {
	if o == nil {
		var ret Options
		return ret
	}

	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value
// and a boolean to check if the value has been set.
func (o *RcsMessage) GetOptionsOk() (*Options, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Options, true
}

// SetOptions sets field value
func (o *RcsMessage) SetOptions(v Options) {
	o.Options = v
}

// GetAlternativeChannel returns the AlternativeChannel field value if set, zero value otherwise.
func (o *RcsMessage) GetAlternativeChannel() AlternativeChannel {
	if o == nil || IsNil(o.AlternativeChannel) {
		var ret AlternativeChannel
		return ret
	}
	return *o.AlternativeChannel
}

// GetAlternativeChannelOk returns a tuple with the AlternativeChannel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RcsMessage) GetAlternativeChannelOk() (*AlternativeChannel, bool) {
	if o == nil || IsNil(o.AlternativeChannel) {
		return nil, false
	}
	return o.AlternativeChannel, true
}

// HasAlternativeChannel returns a boolean if a field has been set.
func (o *RcsMessage) HasAlternativeChannel() bool {
	if o != nil && !IsNil(o.AlternativeChannel) {
		return true
	}

	return false
}

// SetAlternativeChannel gets a reference to the given AlternativeChannel and assigns it to the AlternativeChannel field.
func (o *RcsMessage) SetAlternativeChannel(v AlternativeChannel) {
	o.AlternativeChannel = &v
}

// GetCallbackUrl returns the CallbackUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RcsMessage) GetCallbackUrl() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.CallbackUrl
}

// GetCallbackUrlOk returns a tuple with the CallbackUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RcsMessage) GetCallbackUrlOk() (*interface{}, bool) {
	if o == nil || IsNil(o.CallbackUrl) {
		return nil, false
	}
	return &o.CallbackUrl, true
}

// HasCallbackUrl returns a boolean if a field has been set.
func (o *RcsMessage) HasCallbackUrl() bool {
	if o != nil && !IsNil(o.CallbackUrl) {
		return true
	}

	return false
}

// SetCallbackUrl gets a reference to the given interface{} and assigns it to the CallbackUrl field.
func (o *RcsMessage) SetCallbackUrl(v interface{}) {
	o.CallbackUrl = v
}

// GetTariffCode returns the TariffCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RcsMessage) GetTariffCode() int32 {
	if o == nil || IsNil(o.TariffCode.Get()) {
		var ret int32
		return ret
	}
	return *o.TariffCode.Get()
}

// GetTariffCodeOk returns a tuple with the TariffCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RcsMessage) GetTariffCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TariffCode.Get(), o.TariffCode.IsSet()
}

// HasTariffCode returns a boolean if a field has been set.
func (o *RcsMessage) HasTariffCode() bool {
	if o != nil && o.TariffCode.IsSet() {
		return true
	}

	return false
}

// SetTariffCode gets a reference to the given NullableInt32 and assigns it to the TariffCode field.
func (o *RcsMessage) SetTariffCode(v int32) {
	o.TariffCode.Set(&v)
}
// SetTariffCodeNil sets the value for TariffCode to be an explicit nil
func (o *RcsMessage) SetTariffCodeNil() {
	o.TariffCode.Set(nil)
}

// UnsetTariffCode ensures that no value is present for TariffCode, not even an explicit nil
func (o *RcsMessage) UnsetTariffCode() {
	o.TariffCode.Unset()
}

// GetValiditySeconds returns the ValiditySeconds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RcsMessage) GetValiditySeconds() int32 {
	if o == nil || IsNil(o.ValiditySeconds.Get()) {
		var ret int32
		return ret
	}
	return *o.ValiditySeconds.Get()
}

// GetValiditySecondsOk returns a tuple with the ValiditySeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RcsMessage) GetValiditySecondsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ValiditySeconds.Get(), o.ValiditySeconds.IsSet()
}

// HasValiditySeconds returns a boolean if a field has been set.
func (o *RcsMessage) HasValiditySeconds() bool {
	if o != nil && o.ValiditySeconds.IsSet() {
		return true
	}

	return false
}

// SetValiditySeconds gets a reference to the given NullableInt32 and assigns it to the ValiditySeconds field.
func (o *RcsMessage) SetValiditySeconds(v int32) {
	o.ValiditySeconds.Set(&v)
}
// SetValiditySecondsNil sets the value for ValiditySeconds to be an explicit nil
func (o *RcsMessage) SetValiditySecondsNil() {
	o.ValiditySeconds.Set(nil)
}

// UnsetValiditySeconds ensures that no value is present for ValiditySeconds, not even an explicit nil
func (o *RcsMessage) UnsetValiditySeconds() {
	o.ValiditySeconds.Unset()
}

// GetValidity returns the Validity field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RcsMessage) GetValidity() int32 {
	if o == nil || IsNil(o.Validity.Get()) {
		var ret int32
		return ret
	}
	return *o.Validity.Get()
}

// GetValidityOk returns a tuple with the Validity field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RcsMessage) GetValidityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Validity.Get(), o.Validity.IsSet()
}

// HasValidity returns a boolean if a field has been set.
func (o *RcsMessage) HasValidity() bool {
	if o != nil && o.Validity.IsSet() {
		return true
	}

	return false
}

// SetValidity gets a reference to the given NullableInt32 and assigns it to the Validity field.
func (o *RcsMessage) SetValidity(v int32) {
	o.Validity.Set(&v)
}
// SetValidityNil sets the value for Validity to be an explicit nil
func (o *RcsMessage) SetValidityNil() {
	o.Validity.Set(nil)
}

// UnsetValidity ensures that no value is present for Validity, not even an explicit nil
func (o *RcsMessage) UnsetValidity() {
	o.Validity.Unset()
}

// GetAddToContactBook returns the AddToContactBook field value if set, zero value otherwise.
func (o *RcsMessage) GetAddToContactBook() bool {
	if o == nil || IsNil(o.AddToContactBook) {
		var ret bool
		return ret
	}
	return *o.AddToContactBook
}

// GetAddToContactBookOk returns a tuple with the AddToContactBook field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RcsMessage) GetAddToContactBookOk() (*bool, bool) {
	if o == nil || IsNil(o.AddToContactBook) {
		return nil, false
	}
	return o.AddToContactBook, true
}

// HasAddToContactBook returns a boolean if a field has been set.
func (o *RcsMessage) HasAddToContactBook() bool {
	if o != nil && !IsNil(o.AddToContactBook) {
		return true
	}

	return false
}

// SetAddToContactBook gets a reference to the given bool and assigns it to the AddToContactBook field.
func (o *RcsMessage) SetAddToContactBook(v bool) {
	o.AddToContactBook = &v
}

// GetCheckStopList returns the CheckStopList field value if set, zero value otherwise.
func (o *RcsMessage) GetCheckStopList() bool {
	if o == nil || IsNil(o.CheckStopList) {
		var ret bool
		return ret
	}
	return *o.CheckStopList
}

// GetCheckStopListOk returns a tuple with the CheckStopList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RcsMessage) GetCheckStopListOk() (*bool, bool) {
	if o == nil || IsNil(o.CheckStopList) {
		return nil, false
	}
	return o.CheckStopList, true
}

// HasCheckStopList returns a boolean if a field has been set.
func (o *RcsMessage) HasCheckStopList() bool {
	if o != nil && !IsNil(o.CheckStopList) {
		return true
	}

	return false
}

// SetCheckStopList gets a reference to the given bool and assigns it to the CheckStopList field.
func (o *RcsMessage) SetCheckStopList(v bool) {
	o.CheckStopList = &v
}

func (o RcsMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RcsMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["phone"] = o.Phone
	toSerialize["sender"] = o.Sender
	toSerialize["options"] = o.Options
	if !IsNil(o.AlternativeChannel) {
		toSerialize["alternative_channel"] = o.AlternativeChannel
	}
	if o.CallbackUrl != nil {
		toSerialize["callback_url"] = o.CallbackUrl
	}
	if o.TariffCode.IsSet() {
		toSerialize["tariff_code"] = o.TariffCode.Get()
	}
	if o.ValiditySeconds.IsSet() {
		toSerialize["validity_seconds"] = o.ValiditySeconds.Get()
	}
	if o.Validity.IsSet() {
		toSerialize["validity"] = o.Validity.Get()
	}
	if !IsNil(o.AddToContactBook) {
		toSerialize["add_to_contact_book"] = o.AddToContactBook
	}
	if !IsNil(o.CheckStopList) {
		toSerialize["check_stop_list"] = o.CheckStopList
	}
	return toSerialize, nil
}

func (o *RcsMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"phone",
		"sender",
		"options",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRcsMessage := _RcsMessage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRcsMessage)

	if err != nil {
		return err
	}

	*o = RcsMessage(varRcsMessage)

	return err
}

type NullableRcsMessage struct {
	value *RcsMessage
	isSet bool
}

func (v NullableRcsMessage) Get() *RcsMessage {
	return v.value
}

func (v *NullableRcsMessage) Set(val *RcsMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableRcsMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableRcsMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRcsMessage(val *RcsMessage) *NullableRcsMessage {
	return &NullableRcsMessage{value: val, isSet: true}
}

func (v NullableRcsMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRcsMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


