/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetInternalCurrencies200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetInternalCurrencies200Response{}

// GetInternalCurrencies200Response struct for GetInternalCurrencies200Response
type GetInternalCurrencies200Response struct {
	Data []CurrencyItem `json:"data"`
}

type _GetInternalCurrencies200Response GetInternalCurrencies200Response

// NewGetInternalCurrencies200Response instantiates a new GetInternalCurrencies200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetInternalCurrencies200Response(data []CurrencyItem) *GetInternalCurrencies200Response {
	this := GetInternalCurrencies200Response{}
	this.Data = data
	return &this
}

// NewGetInternalCurrencies200ResponseWithDefaults instantiates a new GetInternalCurrencies200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetInternalCurrencies200ResponseWithDefaults() *GetInternalCurrencies200Response {
	this := GetInternalCurrencies200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetInternalCurrencies200Response) GetData() []CurrencyItem {
	if o == nil {
		var ret []CurrencyItem
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetInternalCurrencies200Response) GetDataOk() ([]CurrencyItem, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetInternalCurrencies200Response) SetData(v []CurrencyItem) {
	o.Data = v
}

func (o GetInternalCurrencies200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetInternalCurrencies200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetInternalCurrencies200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetInternalCurrencies200Response := _GetInternalCurrencies200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetInternalCurrencies200Response)

	if err != nil {
		return err
	}

	*o = GetInternalCurrencies200Response(varGetInternalCurrencies200Response)

	return err
}

type NullableGetInternalCurrencies200Response struct {
	value *GetInternalCurrencies200Response
	isSet bool
}

func (v NullableGetInternalCurrencies200Response) Get() *GetInternalCurrencies200Response {
	return v.value
}

func (v *NullableGetInternalCurrencies200Response) Set(val *GetInternalCurrencies200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetInternalCurrencies200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetInternalCurrencies200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetInternalCurrencies200Response(val *GetInternalCurrencies200Response) *NullableGetInternalCurrencies200Response {
	return &NullableGetInternalCurrencies200Response{value: val, isSet: true}
}

func (v NullableGetInternalCurrencies200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetInternalCurrencies200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


