/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WhatsAppMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WhatsAppMessage{}

// WhatsAppMessage struct for WhatsAppMessage
type WhatsAppMessage struct {
	Phone Phone `json:"phone"`
	Sender string `json:"sender"`
	Type string `json:"type"`
	Template NullableWhatsAppMessageTemplate `json:"template,omitempty"`
	AlternativeChannel NullableWhatsAppMessageAlternativeChannel `json:"alternative_channel,omitempty"`
	// Link to get the delivery status of messages. If this parameter is specified in the method, it will take precedence over the value specified in the “Callback URL” field in the Personal Area.
	CallbackUrl interface{} `json:"callback_url,omitempty"`
	AddToContactBook *bool `json:"add_to_contact_book,omitempty"`
	CheckStopList *bool `json:"check_stop_list,omitempty"`
}

type _WhatsAppMessage WhatsAppMessage

// NewWhatsAppMessage instantiates a new WhatsAppMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWhatsAppMessage(phone Phone, sender string, type_ string) *WhatsAppMessage {
	this := WhatsAppMessage{}
	this.Phone = phone
	this.Sender = sender
	this.Type = type_
	var addToContactBook bool = true
	this.AddToContactBook = &addToContactBook
	var checkStopList bool = true
	this.CheckStopList = &checkStopList
	return &this
}

// NewWhatsAppMessageWithDefaults instantiates a new WhatsAppMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWhatsAppMessageWithDefaults() *WhatsAppMessage {
	this := WhatsAppMessage{}
	var addToContactBook bool = true
	this.AddToContactBook = &addToContactBook
	var checkStopList bool = true
	this.CheckStopList = &checkStopList
	return &this
}

// GetPhone returns the Phone field value
func (o *WhatsAppMessage) GetPhone() Phone {
	if o == nil {
		var ret Phone
		return ret
	}

	return o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value
// and a boolean to check if the value has been set.
func (o *WhatsAppMessage) GetPhoneOk() (*Phone, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phone, true
}

// SetPhone sets field value
func (o *WhatsAppMessage) SetPhone(v Phone) {
	o.Phone = v
}

// GetSender returns the Sender field value
func (o *WhatsAppMessage) GetSender() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sender
}

// GetSenderOk returns a tuple with the Sender field value
// and a boolean to check if the value has been set.
func (o *WhatsAppMessage) GetSenderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sender, true
}

// SetSender sets field value
func (o *WhatsAppMessage) SetSender(v string) {
	o.Sender = v
}

// GetType returns the Type field value
func (o *WhatsAppMessage) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *WhatsAppMessage) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *WhatsAppMessage) SetType(v string) {
	o.Type = v
}

// GetTemplate returns the Template field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WhatsAppMessage) GetTemplate() WhatsAppMessageTemplate {
	if o == nil || IsNil(o.Template.Get()) {
		var ret WhatsAppMessageTemplate
		return ret
	}
	return *o.Template.Get()
}

// GetTemplateOk returns a tuple with the Template field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WhatsAppMessage) GetTemplateOk() (*WhatsAppMessageTemplate, bool) {
	if o == nil {
		return nil, false
	}
	return o.Template.Get(), o.Template.IsSet()
}

// HasTemplate returns a boolean if a field has been set.
func (o *WhatsAppMessage) HasTemplate() bool {
	if o != nil && o.Template.IsSet() {
		return true
	}

	return false
}

// SetTemplate gets a reference to the given NullableWhatsAppMessageTemplate and assigns it to the Template field.
func (o *WhatsAppMessage) SetTemplate(v WhatsAppMessageTemplate) {
	o.Template.Set(&v)
}
// SetTemplateNil sets the value for Template to be an explicit nil
func (o *WhatsAppMessage) SetTemplateNil() {
	o.Template.Set(nil)
}

// UnsetTemplate ensures that no value is present for Template, not even an explicit nil
func (o *WhatsAppMessage) UnsetTemplate() {
	o.Template.Unset()
}

// GetAlternativeChannel returns the AlternativeChannel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WhatsAppMessage) GetAlternativeChannel() WhatsAppMessageAlternativeChannel {
	if o == nil || IsNil(o.AlternativeChannel.Get()) {
		var ret WhatsAppMessageAlternativeChannel
		return ret
	}
	return *o.AlternativeChannel.Get()
}

// GetAlternativeChannelOk returns a tuple with the AlternativeChannel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WhatsAppMessage) GetAlternativeChannelOk() (*WhatsAppMessageAlternativeChannel, bool) {
	if o == nil {
		return nil, false
	}
	return o.AlternativeChannel.Get(), o.AlternativeChannel.IsSet()
}

// HasAlternativeChannel returns a boolean if a field has been set.
func (o *WhatsAppMessage) HasAlternativeChannel() bool {
	if o != nil && o.AlternativeChannel.IsSet() {
		return true
	}

	return false
}

// SetAlternativeChannel gets a reference to the given NullableWhatsAppMessageAlternativeChannel and assigns it to the AlternativeChannel field.
func (o *WhatsAppMessage) SetAlternativeChannel(v WhatsAppMessageAlternativeChannel) {
	o.AlternativeChannel.Set(&v)
}
// SetAlternativeChannelNil sets the value for AlternativeChannel to be an explicit nil
func (o *WhatsAppMessage) SetAlternativeChannelNil() {
	o.AlternativeChannel.Set(nil)
}

// UnsetAlternativeChannel ensures that no value is present for AlternativeChannel, not even an explicit nil
func (o *WhatsAppMessage) UnsetAlternativeChannel() {
	o.AlternativeChannel.Unset()
}

// GetCallbackUrl returns the CallbackUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WhatsAppMessage) GetCallbackUrl() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.CallbackUrl
}

// GetCallbackUrlOk returns a tuple with the CallbackUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WhatsAppMessage) GetCallbackUrlOk() (*interface{}, bool) {
	if o == nil || IsNil(o.CallbackUrl) {
		return nil, false
	}
	return &o.CallbackUrl, true
}

// HasCallbackUrl returns a boolean if a field has been set.
func (o *WhatsAppMessage) HasCallbackUrl() bool {
	if o != nil && !IsNil(o.CallbackUrl) {
		return true
	}

	return false
}

// SetCallbackUrl gets a reference to the given interface{} and assigns it to the CallbackUrl field.
func (o *WhatsAppMessage) SetCallbackUrl(v interface{}) {
	o.CallbackUrl = v
}

// GetAddToContactBook returns the AddToContactBook field value if set, zero value otherwise.
func (o *WhatsAppMessage) GetAddToContactBook() bool {
	if o == nil || IsNil(o.AddToContactBook) {
		var ret bool
		return ret
	}
	return *o.AddToContactBook
}

// GetAddToContactBookOk returns a tuple with the AddToContactBook field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppMessage) GetAddToContactBookOk() (*bool, bool) {
	if o == nil || IsNil(o.AddToContactBook) {
		return nil, false
	}
	return o.AddToContactBook, true
}

// HasAddToContactBook returns a boolean if a field has been set.
func (o *WhatsAppMessage) HasAddToContactBook() bool {
	if o != nil && !IsNil(o.AddToContactBook) {
		return true
	}

	return false
}

// SetAddToContactBook gets a reference to the given bool and assigns it to the AddToContactBook field.
func (o *WhatsAppMessage) SetAddToContactBook(v bool) {
	o.AddToContactBook = &v
}

// GetCheckStopList returns the CheckStopList field value if set, zero value otherwise.
func (o *WhatsAppMessage) GetCheckStopList() bool {
	if o == nil || IsNil(o.CheckStopList) {
		var ret bool
		return ret
	}
	return *o.CheckStopList
}

// GetCheckStopListOk returns a tuple with the CheckStopList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WhatsAppMessage) GetCheckStopListOk() (*bool, bool) {
	if o == nil || IsNil(o.CheckStopList) {
		return nil, false
	}
	return o.CheckStopList, true
}

// HasCheckStopList returns a boolean if a field has been set.
func (o *WhatsAppMessage) HasCheckStopList() bool {
	if o != nil && !IsNil(o.CheckStopList) {
		return true
	}

	return false
}

// SetCheckStopList gets a reference to the given bool and assigns it to the CheckStopList field.
func (o *WhatsAppMessage) SetCheckStopList(v bool) {
	o.CheckStopList = &v
}

func (o WhatsAppMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WhatsAppMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["phone"] = o.Phone
	toSerialize["sender"] = o.Sender
	toSerialize["type"] = o.Type
	if o.Template.IsSet() {
		toSerialize["template"] = o.Template.Get()
	}
	if o.AlternativeChannel.IsSet() {
		toSerialize["alternative_channel"] = o.AlternativeChannel.Get()
	}
	if o.CallbackUrl != nil {
		toSerialize["callback_url"] = o.CallbackUrl
	}
	if !IsNil(o.AddToContactBook) {
		toSerialize["add_to_contact_book"] = o.AddToContactBook
	}
	if !IsNil(o.CheckStopList) {
		toSerialize["check_stop_list"] = o.CheckStopList
	}
	return toSerialize, nil
}

func (o *WhatsAppMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"phone",
		"sender",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWhatsAppMessage := _WhatsAppMessage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWhatsAppMessage)

	if err != nil {
		return err
	}

	*o = WhatsAppMessage(varWhatsAppMessage)

	return err
}

type NullableWhatsAppMessage struct {
	value *WhatsAppMessage
	isSet bool
}

func (v NullableWhatsAppMessage) Get() *WhatsAppMessage {
	return v.value
}

func (v *NullableWhatsAppMessage) Set(val *WhatsAppMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableWhatsAppMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableWhatsAppMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWhatsAppMessage(val *WhatsAppMessage) *NullableWhatsAppMessage {
	return &NullableWhatsAppMessage{value: val, isSet: true}
}

func (v NullableWhatsAppMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWhatsAppMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


