/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
)

// checks if the ContactListSearchCriteria type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContactListSearchCriteria{}

// ContactListSearchCriteria Search criteria
type ContactListSearchCriteria struct {
	Field *ContactGroupSearchField `json:"field,omitempty"`
	Operator *SearchOperator `json:"operator,omitempty"`
	// Value to to find using search[field] and search[operator]
	Value *string `json:"value,omitempty"`
}

// NewContactListSearchCriteria instantiates a new ContactListSearchCriteria object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContactListSearchCriteria() *ContactListSearchCriteria {
	this := ContactListSearchCriteria{}
	return &this
}

// NewContactListSearchCriteriaWithDefaults instantiates a new ContactListSearchCriteria object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContactListSearchCriteriaWithDefaults() *ContactListSearchCriteria {
	this := ContactListSearchCriteria{}
	return &this
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *ContactListSearchCriteria) GetField() ContactGroupSearchField {
	if o == nil || IsNil(o.Field) {
		var ret ContactGroupSearchField
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactListSearchCriteria) GetFieldOk() (*ContactGroupSearchField, bool) {
	if o == nil || IsNil(o.Field) {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *ContactListSearchCriteria) HasField() bool {
	if o != nil && !IsNil(o.Field) {
		return true
	}

	return false
}

// SetField gets a reference to the given ContactGroupSearchField and assigns it to the Field field.
func (o *ContactListSearchCriteria) SetField(v ContactGroupSearchField) {
	o.Field = &v
}

// GetOperator returns the Operator field value if set, zero value otherwise.
func (o *ContactListSearchCriteria) GetOperator() SearchOperator {
	if o == nil || IsNil(o.Operator) {
		var ret SearchOperator
		return ret
	}
	return *o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactListSearchCriteria) GetOperatorOk() (*SearchOperator, bool) {
	if o == nil || IsNil(o.Operator) {
		return nil, false
	}
	return o.Operator, true
}

// HasOperator returns a boolean if a field has been set.
func (o *ContactListSearchCriteria) HasOperator() bool {
	if o != nil && !IsNil(o.Operator) {
		return true
	}

	return false
}

// SetOperator gets a reference to the given SearchOperator and assigns it to the Operator field.
func (o *ContactListSearchCriteria) SetOperator(v SearchOperator) {
	o.Operator = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ContactListSearchCriteria) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactListSearchCriteria) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ContactListSearchCriteria) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ContactListSearchCriteria) SetValue(v string) {
	o.Value = &v
}

func (o ContactListSearchCriteria) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContactListSearchCriteria) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Field) {
		toSerialize["field"] = o.Field
	}
	if !IsNil(o.Operator) {
		toSerialize["operator"] = o.Operator
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableContactListSearchCriteria struct {
	value *ContactListSearchCriteria
	isSet bool
}

func (v NullableContactListSearchCriteria) Get() *ContactListSearchCriteria {
	return v.value
}

func (v *NullableContactListSearchCriteria) Set(val *ContactListSearchCriteria) {
	v.value = val
	v.isSet = true
}

func (v NullableContactListSearchCriteria) IsSet() bool {
	return v.isSet
}

func (v *NullableContactListSearchCriteria) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContactListSearchCriteria(val *ContactListSearchCriteria) *NullableContactListSearchCriteria {
	return &NullableContactListSearchCriteria{value: val, isSet: true}
}

func (v NullableContactListSearchCriteria) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContactListSearchCriteria) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


