/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OtpTemplateCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OtpTemplateCreateRequest{}

// OtpTemplateCreateRequest struct for OtpTemplateCreateRequest
type OtpTemplateCreateRequest struct {
	// Name of the template.  A string of 3 to 50 characters.
	Name string `json:"name"`
	// The text of the template message.
	Text string `json:"text"`
	// Two-letter country code(s) for which the template must apply. Sending messages with the OTP code will only be possible if the recipient’s number belongs to the country you specify for the template.
	Countries []string `json:"countries,omitempty"`
}

type _OtpTemplateCreateRequest OtpTemplateCreateRequest

// NewOtpTemplateCreateRequest instantiates a new OtpTemplateCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOtpTemplateCreateRequest(name string, text string) *OtpTemplateCreateRequest {
	this := OtpTemplateCreateRequest{}
	this.Name = name
	this.Text = text
	return &this
}

// NewOtpTemplateCreateRequestWithDefaults instantiates a new OtpTemplateCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOtpTemplateCreateRequestWithDefaults() *OtpTemplateCreateRequest {
	this := OtpTemplateCreateRequest{}
	return &this
}

// GetName returns the Name field value
func (o *OtpTemplateCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OtpTemplateCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OtpTemplateCreateRequest) SetName(v string) {
	o.Name = v
}

// GetText returns the Text field value
func (o *OtpTemplateCreateRequest) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *OtpTemplateCreateRequest) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *OtpTemplateCreateRequest) SetText(v string) {
	o.Text = v
}

// GetCountries returns the Countries field value if set, zero value otherwise.
func (o *OtpTemplateCreateRequest) GetCountries() []string {
	if o == nil || IsNil(o.Countries) {
		var ret []string
		return ret
	}
	return o.Countries
}

// GetCountriesOk returns a tuple with the Countries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OtpTemplateCreateRequest) GetCountriesOk() ([]string, bool) {
	if o == nil || IsNil(o.Countries) {
		return nil, false
	}
	return o.Countries, true
}

// HasCountries returns a boolean if a field has been set.
func (o *OtpTemplateCreateRequest) HasCountries() bool {
	if o != nil && !IsNil(o.Countries) {
		return true
	}

	return false
}

// SetCountries gets a reference to the given []string and assigns it to the Countries field.
func (o *OtpTemplateCreateRequest) SetCountries(v []string) {
	o.Countries = v
}

func (o OtpTemplateCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OtpTemplateCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["text"] = o.Text
	if !IsNil(o.Countries) {
		toSerialize["countries"] = o.Countries
	}
	return toSerialize, nil
}

func (o *OtpTemplateCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOtpTemplateCreateRequest := _OtpTemplateCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOtpTemplateCreateRequest)

	if err != nil {
		return err
	}

	*o = OtpTemplateCreateRequest(varOtpTemplateCreateRequest)

	return err
}

type NullableOtpTemplateCreateRequest struct {
	value *OtpTemplateCreateRequest
	isSet bool
}

func (v NullableOtpTemplateCreateRequest) Get() *OtpTemplateCreateRequest {
	return v.value
}

func (v *NullableOtpTemplateCreateRequest) Set(val *OtpTemplateCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOtpTemplateCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOtpTemplateCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOtpTemplateCreateRequest(val *OtpTemplateCreateRequest) *NullableOtpTemplateCreateRequest {
	return &NullableOtpTemplateCreateRequest{value: val, isSet: true}
}

func (v NullableOtpTemplateCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOtpTemplateCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


