/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// StatJobsCreateRequest - struct for StatJobsCreateRequest
type StatJobsCreateRequest struct {
	CreateJobMessage *CreateJobMessage
	CreateJobParams *CreateJobParams
}

// CreateJobMessageAsStatJobsCreateRequest is a convenience function that returns CreateJobMessage wrapped in StatJobsCreateRequest
func CreateJobMessageAsStatJobsCreateRequest(v *CreateJobMessage) StatJobsCreateRequest {
	return StatJobsCreateRequest{
		CreateJobMessage: v,
	}
}

// CreateJobParamsAsStatJobsCreateRequest is a convenience function that returns CreateJobParams wrapped in StatJobsCreateRequest
func CreateJobParamsAsStatJobsCreateRequest(v *CreateJobParams) StatJobsCreateRequest {
	return StatJobsCreateRequest{
		CreateJobParams: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *StatJobsCreateRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CreateJobMessage
	err = newStrictDecoder(data).Decode(&dst.CreateJobMessage)
	if err == nil {
		jsonCreateJobMessage, _ := json.Marshal(dst.CreateJobMessage)
		if string(jsonCreateJobMessage) == "{}" { // empty struct
			dst.CreateJobMessage = nil
		} else {
			if err = validator.Validate(dst.CreateJobMessage); err != nil {
				dst.CreateJobMessage = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateJobMessage = nil
	}

	// try to unmarshal data into CreateJobParams
	err = newStrictDecoder(data).Decode(&dst.CreateJobParams)
	if err == nil {
		jsonCreateJobParams, _ := json.Marshal(dst.CreateJobParams)
		if string(jsonCreateJobParams) == "{}" { // empty struct
			dst.CreateJobParams = nil
		} else {
			if err = validator.Validate(dst.CreateJobParams); err != nil {
				dst.CreateJobParams = nil
			} else {
				match++
			}
		}
	} else {
		dst.CreateJobParams = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CreateJobMessage = nil
		dst.CreateJobParams = nil

		return fmt.Errorf("data matches more than one schema in oneOf(StatJobsCreateRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(StatJobsCreateRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src StatJobsCreateRequest) MarshalJSON() ([]byte, error) {
	if src.CreateJobMessage != nil {
		return json.Marshal(&src.CreateJobMessage)
	}

	if src.CreateJobParams != nil {
		return json.Marshal(&src.CreateJobParams)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *StatJobsCreateRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.CreateJobMessage != nil {
		return obj.CreateJobMessage
	}

	if obj.CreateJobParams != nil {
		return obj.CreateJobParams
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj StatJobsCreateRequest) GetActualInstanceValue() (interface{}) {
	if obj.CreateJobMessage != nil {
		return *obj.CreateJobMessage
	}

	if obj.CreateJobParams != nil {
		return *obj.CreateJobParams
	}

	// all schemas are nil
	return nil
}

type NullableStatJobsCreateRequest struct {
	value *StatJobsCreateRequest
	isSet bool
}

func (v NullableStatJobsCreateRequest) Get() *StatJobsCreateRequest {
	return v.value
}

func (v *NullableStatJobsCreateRequest) Set(val *StatJobsCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableStatJobsCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableStatJobsCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatJobsCreateRequest(val *StatJobsCreateRequest) *NullableStatJobsCreateRequest {
	return &NullableStatJobsCreateRequest{value: val, isSet: true}
}

func (v NullableStatJobsCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatJobsCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


