/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// Suggestion - Object describe action when user click on button, it may be call to the phone or redirect to the link
type Suggestion struct {
	SuggestionCall *SuggestionCall
	SuggestionLink *SuggestionLink
}

// SuggestionCallAsSuggestion is a convenience function that returns SuggestionCall wrapped in Suggestion
func SuggestionCallAsSuggestion(v *SuggestionCall) Suggestion {
	return Suggestion{
		SuggestionCall: v,
	}
}

// SuggestionLinkAsSuggestion is a convenience function that returns SuggestionLink wrapped in Suggestion
func SuggestionLinkAsSuggestion(v *SuggestionLink) Suggestion {
	return Suggestion{
		SuggestionLink: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *Suggestion) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into SuggestionCall
	err = newStrictDecoder(data).Decode(&dst.SuggestionCall)
	if err == nil {
		jsonSuggestionCall, _ := json.Marshal(dst.SuggestionCall)
		if string(jsonSuggestionCall) == "{}" { // empty struct
			dst.SuggestionCall = nil
		} else {
			if err = validator.Validate(dst.SuggestionCall); err != nil {
				dst.SuggestionCall = nil
			} else {
				match++
			}
		}
	} else {
		dst.SuggestionCall = nil
	}

	// try to unmarshal data into SuggestionLink
	err = newStrictDecoder(data).Decode(&dst.SuggestionLink)
	if err == nil {
		jsonSuggestionLink, _ := json.Marshal(dst.SuggestionLink)
		if string(jsonSuggestionLink) == "{}" { // empty struct
			dst.SuggestionLink = nil
		} else {
			if err = validator.Validate(dst.SuggestionLink); err != nil {
				dst.SuggestionLink = nil
			} else {
				match++
			}
		}
	} else {
		dst.SuggestionLink = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.SuggestionCall = nil
		dst.SuggestionLink = nil

		return fmt.Errorf("data matches more than one schema in oneOf(Suggestion)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(Suggestion)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src Suggestion) MarshalJSON() ([]byte, error) {
	if src.SuggestionCall != nil {
		return json.Marshal(&src.SuggestionCall)
	}

	if src.SuggestionLink != nil {
		return json.Marshal(&src.SuggestionLink)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *Suggestion) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.SuggestionCall != nil {
		return obj.SuggestionCall
	}

	if obj.SuggestionLink != nil {
		return obj.SuggestionLink
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj Suggestion) GetActualInstanceValue() (interface{}) {
	if obj.SuggestionCall != nil {
		return *obj.SuggestionCall
	}

	if obj.SuggestionLink != nil {
		return *obj.SuggestionLink
	}

	// all schemas are nil
	return nil
}

type NullableSuggestion struct {
	value *Suggestion
	isSet bool
}

func (v NullableSuggestion) Get() *Suggestion {
	return v.value
}

func (v *NullableSuggestion) Set(val *Suggestion) {
	v.value = val
	v.isSet = true
}

func (v NullableSuggestion) IsSet() bool {
	return v.isSet
}

func (v *NullableSuggestion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSuggestion(val *Suggestion) *NullableSuggestion {
	return &NullableSuggestion{value: val, isSet: true}
}

func (v NullableSuggestion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSuggestion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


