/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
)

// checks if the ShortUrlsLink404Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShortUrlsLink404Response{}

// ShortUrlsLink404Response struct for ShortUrlsLink404Response
type ShortUrlsLink404Response struct {
	// Not Found
	Message *string `json:"message,omitempty"`
}

// NewShortUrlsLink404Response instantiates a new ShortUrlsLink404Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShortUrlsLink404Response() *ShortUrlsLink404Response {
	this := ShortUrlsLink404Response{}
	return &this
}

// NewShortUrlsLink404ResponseWithDefaults instantiates a new ShortUrlsLink404Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShortUrlsLink404ResponseWithDefaults() *ShortUrlsLink404Response {
	this := ShortUrlsLink404Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ShortUrlsLink404Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShortUrlsLink404Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ShortUrlsLink404Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ShortUrlsLink404Response) SetMessage(v string) {
	o.Message = &v
}

func (o ShortUrlsLink404Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShortUrlsLink404Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableShortUrlsLink404Response struct {
	value *ShortUrlsLink404Response
	isSet bool
}

func (v NullableShortUrlsLink404Response) Get() *ShortUrlsLink404Response {
	return v.value
}

func (v *NullableShortUrlsLink404Response) Set(val *ShortUrlsLink404Response) {
	v.value = val
	v.isSet = true
}

func (v NullableShortUrlsLink404Response) IsSet() bool {
	return v.isSet
}

func (v *NullableShortUrlsLink404Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShortUrlsLink404Response(val *ShortUrlsLink404Response) *NullableShortUrlsLink404Response {
	return &NullableShortUrlsLink404Response{value: val, isSet: true}
}

func (v NullableShortUrlsLink404Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShortUrlsLink404Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


