/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
)

// checks if the OtpTemplate404Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OtpTemplate404Response{}

// OtpTemplate404Response struct for OtpTemplate404Response
type OtpTemplate404Response struct {
	// Model not found  This error can occur when the template identifier is specified incorrectly or the specified template is not present in the system. Please ensure that you are using the correct template identifier and try again.
	Message *string `json:"message,omitempty"`
}

// NewOtpTemplate404Response instantiates a new OtpTemplate404Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOtpTemplate404Response() *OtpTemplate404Response {
	this := OtpTemplate404Response{}
	return &this
}

// NewOtpTemplate404ResponseWithDefaults instantiates a new OtpTemplate404Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOtpTemplate404ResponseWithDefaults() *OtpTemplate404Response {
	this := OtpTemplate404Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *OtpTemplate404Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OtpTemplate404Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *OtpTemplate404Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *OtpTemplate404Response) SetMessage(v string) {
	o.Message = &v
}

func (o OtpTemplate404Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OtpTemplate404Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableOtpTemplate404Response struct {
	value *OtpTemplate404Response
	isSet bool
}

func (v NullableOtpTemplate404Response) Get() *OtpTemplate404Response {
	return v.value
}

func (v *NullableOtpTemplate404Response) Set(val *OtpTemplate404Response) {
	v.value = val
	v.isSet = true
}

func (v NullableOtpTemplate404Response) IsSet() bool {
	return v.isSet
}

func (v *NullableOtpTemplate404Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOtpTemplate404Response(val *OtpTemplate404Response) *NullableOtpTemplate404Response {
	return &NullableOtpTemplate404Response{value: val, isSet: true}
}

func (v NullableOtpTemplate404Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOtpTemplate404Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


