/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OtpTemplateDelete200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OtpTemplateDelete200Response{}

// OtpTemplateDelete200Response struct for OtpTemplateDelete200Response
type OtpTemplateDelete200Response struct {
	Data OtpTemplateDeleteResponseData `json:"data"`
}

type _OtpTemplateDelete200Response OtpTemplateDelete200Response

// NewOtpTemplateDelete200Response instantiates a new OtpTemplateDelete200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOtpTemplateDelete200Response(data OtpTemplateDeleteResponseData) *OtpTemplateDelete200Response {
	this := OtpTemplateDelete200Response{}
	this.Data = data
	return &this
}

// NewOtpTemplateDelete200ResponseWithDefaults instantiates a new OtpTemplateDelete200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOtpTemplateDelete200ResponseWithDefaults() *OtpTemplateDelete200Response {
	this := OtpTemplateDelete200Response{}
	return &this
}

// GetData returns the Data field value
func (o *OtpTemplateDelete200Response) GetData() OtpTemplateDeleteResponseData {
	if o == nil {
		var ret OtpTemplateDeleteResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *OtpTemplateDelete200Response) GetDataOk() (*OtpTemplateDeleteResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *OtpTemplateDelete200Response) SetData(v OtpTemplateDeleteResponseData) {
	o.Data = v
}

func (o OtpTemplateDelete200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OtpTemplateDelete200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *OtpTemplateDelete200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOtpTemplateDelete200Response := _OtpTemplateDelete200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOtpTemplateDelete200Response)

	if err != nil {
		return err
	}

	*o = OtpTemplateDelete200Response(varOtpTemplateDelete200Response)

	return err
}

type NullableOtpTemplateDelete200Response struct {
	value *OtpTemplateDelete200Response
	isSet bool
}

func (v NullableOtpTemplateDelete200Response) Get() *OtpTemplateDelete200Response {
	return v.value
}

func (v *NullableOtpTemplateDelete200Response) Set(val *OtpTemplateDelete200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableOtpTemplateDelete200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableOtpTemplateDelete200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOtpTemplateDelete200Response(val *OtpTemplateDelete200Response) *NullableOtpTemplateDelete200Response {
	return &NullableOtpTemplateDelete200Response{value: val, isSet: true}
}

func (v NullableOtpTemplateDelete200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOtpTemplateDelete200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


