/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Rcs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Rcs{}

// Rcs struct for Rcs
type Rcs struct {
	// The array contains information about the card. The maximum number of cards is 5. Messages with one card are called “Single card”, messages with 2 or more cards are called “Carousel”. Depending on the chosen tariff, the number of cards may be limited (for example, you can send only Single cards).  Details will be provided by manager.
	Cards []Card `json:"cards"`
	// It is specified only for the “text” message type. RCS message text is  up to 160 characters. Can contain emojis (character count for emojis according to UTF-16 code points. Simple emojis take 2 code points, complex emojis take 4, Cyrillic emojis take 1). If the message contains a link in the format http://nosms.cc/XXXX, the System will generate an Unsubscribe link while sending the message
	Text string `json:"text"`
	// The name of the agent used to send the rcs message
	Sender string `json:"sender"`
}

type _Rcs Rcs

// NewRcs instantiates a new Rcs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRcs(cards []Card, text string, sender string) *Rcs {
	this := Rcs{}
	this.Cards = cards
	this.Text = text
	this.Sender = sender
	return &this
}

// NewRcsWithDefaults instantiates a new Rcs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRcsWithDefaults() *Rcs {
	this := Rcs{}
	return &this
}

// GetCards returns the Cards field value
func (o *Rcs) GetCards() []Card {
	if o == nil {
		var ret []Card
		return ret
	}

	return o.Cards
}

// GetCardsOk returns a tuple with the Cards field value
// and a boolean to check if the value has been set.
func (o *Rcs) GetCardsOk() ([]Card, bool) {
	if o == nil {
		return nil, false
	}
	return o.Cards, true
}

// SetCards sets field value
func (o *Rcs) SetCards(v []Card) {
	o.Cards = v
}

// GetText returns the Text field value
func (o *Rcs) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *Rcs) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *Rcs) SetText(v string) {
	o.Text = v
}

// GetSender returns the Sender field value
func (o *Rcs) GetSender() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sender
}

// GetSenderOk returns a tuple with the Sender field value
// and a boolean to check if the value has been set.
func (o *Rcs) GetSenderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sender, true
}

// SetSender sets field value
func (o *Rcs) SetSender(v string) {
	o.Sender = v
}

func (o Rcs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Rcs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cards"] = o.Cards
	toSerialize["text"] = o.Text
	toSerialize["sender"] = o.Sender
	return toSerialize, nil
}

func (o *Rcs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cards",
		"text",
		"sender",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRcs := _Rcs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRcs)

	if err != nil {
		return err
	}

	*o = Rcs(varRcs)

	return err
}

type NullableRcs struct {
	value *Rcs
	isSet bool
}

func (v NullableRcs) Get() *Rcs {
	return v.value
}

func (v *NullableRcs) Set(val *Rcs) {
	v.value = val
	v.isSet = true
}

func (v NullableRcs) IsSet() bool {
	return v.isSet
}

func (v *NullableRcs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRcs(val *Rcs) *NullableRcs {
	return &NullableRcs{value: val, isSet: true}
}

func (v NullableRcs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRcs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


