/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Voice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Voice{}

// Voice struct for Voice
type Voice struct {
	Sender *string `json:"sender,omitempty"`
	Text string `json:"text"`
	Category string `json:"category"`
	Voice NullableString `json:"voice,omitempty"`
	// Language or locale, like \"en\" or \"en_UK)
	Lang NullableString `json:"lang,omitempty"`
}

type _Voice Voice

// NewVoice instantiates a new Voice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVoice(text string, category string) *Voice {
	this := Voice{}
	this.Text = text
	this.Category = category
	return &this
}

// NewVoiceWithDefaults instantiates a new Voice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVoiceWithDefaults() *Voice {
	this := Voice{}
	return &this
}

// GetSender returns the Sender field value if set, zero value otherwise.
func (o *Voice) GetSender() string {
	if o == nil || IsNil(o.Sender) {
		var ret string
		return ret
	}
	return *o.Sender
}

// GetSenderOk returns a tuple with the Sender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Voice) GetSenderOk() (*string, bool) {
	if o == nil || IsNil(o.Sender) {
		return nil, false
	}
	return o.Sender, true
}

// HasSender returns a boolean if a field has been set.
func (o *Voice) HasSender() bool {
	if o != nil && !IsNil(o.Sender) {
		return true
	}

	return false
}

// SetSender gets a reference to the given string and assigns it to the Sender field.
func (o *Voice) SetSender(v string) {
	o.Sender = &v
}

// GetText returns the Text field value
func (o *Voice) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *Voice) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *Voice) SetText(v string) {
	o.Text = v
}

// GetCategory returns the Category field value
func (o *Voice) GetCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *Voice) GetCategoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *Voice) SetCategory(v string) {
	o.Category = v
}

// GetVoice returns the Voice field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Voice) GetVoice() string {
	if o == nil || IsNil(o.Voice.Get()) {
		var ret string
		return ret
	}
	return *o.Voice.Get()
}

// GetVoiceOk returns a tuple with the Voice field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Voice) GetVoiceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Voice.Get(), o.Voice.IsSet()
}

// HasVoice returns a boolean if a field has been set.
func (o *Voice) HasVoice() bool {
	if o != nil && o.Voice.IsSet() {
		return true
	}

	return false
}

// SetVoice gets a reference to the given NullableString and assigns it to the Voice field.
func (o *Voice) SetVoice(v string) {
	o.Voice.Set(&v)
}
// SetVoiceNil sets the value for Voice to be an explicit nil
func (o *Voice) SetVoiceNil() {
	o.Voice.Set(nil)
}

// UnsetVoice ensures that no value is present for Voice, not even an explicit nil
func (o *Voice) UnsetVoice() {
	o.Voice.Unset()
}

// GetLang returns the Lang field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Voice) GetLang() string {
	if o == nil || IsNil(o.Lang.Get()) {
		var ret string
		return ret
	}
	return *o.Lang.Get()
}

// GetLangOk returns a tuple with the Lang field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Voice) GetLangOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Lang.Get(), o.Lang.IsSet()
}

// HasLang returns a boolean if a field has been set.
func (o *Voice) HasLang() bool {
	if o != nil && o.Lang.IsSet() {
		return true
	}

	return false
}

// SetLang gets a reference to the given NullableString and assigns it to the Lang field.
func (o *Voice) SetLang(v string) {
	o.Lang.Set(&v)
}
// SetLangNil sets the value for Lang to be an explicit nil
func (o *Voice) SetLangNil() {
	o.Lang.Set(nil)
}

// UnsetLang ensures that no value is present for Lang, not even an explicit nil
func (o *Voice) UnsetLang() {
	o.Lang.Unset()
}

func (o Voice) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Voice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Sender) {
		toSerialize["sender"] = o.Sender
	}
	toSerialize["text"] = o.Text
	toSerialize["category"] = o.Category
	if o.Voice.IsSet() {
		toSerialize["voice"] = o.Voice.Get()
	}
	if o.Lang.IsSet() {
		toSerialize["lang"] = o.Lang.Get()
	}
	return toSerialize, nil
}

func (o *Voice) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
		"category",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVoice := _Voice{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVoice)

	if err != nil {
		return err
	}

	*o = Voice(varVoice)

	return err
}

type NullableVoice struct {
	value *Voice
	isSet bool
}

func (v NullableVoice) Get() *Voice {
	return v.value
}

func (v *NullableVoice) Set(val *Voice) {
	v.value = val
	v.isSet = true
}

func (v NullableVoice) IsSet() bool {
	return v.isSet
}

func (v *NullableVoice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVoice(val *Voice) *NullableVoice {
	return &NullableVoice{value: val, isSet: true}
}

func (v NullableVoice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVoice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


