/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StoplistAddRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoplistAddRequest{}

// StoplistAddRequest struct for StoplistAddRequest
type StoplistAddRequest struct {
	// Array of the phone numbers
	Phones []int32 `json:"phones"`
	// Specify the stop list type
	Types []string `json:"types"`
}

type _StoplistAddRequest StoplistAddRequest

// NewStoplistAddRequest instantiates a new StoplistAddRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoplistAddRequest(phones []int32, types []string) *StoplistAddRequest {
	this := StoplistAddRequest{}
	this.Phones = phones
	this.Types = types
	return &this
}

// NewStoplistAddRequestWithDefaults instantiates a new StoplistAddRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoplistAddRequestWithDefaults() *StoplistAddRequest {
	this := StoplistAddRequest{}
	return &this
}

// GetPhones returns the Phones field value
func (o *StoplistAddRequest) GetPhones() []int32 {
	if o == nil {
		var ret []int32
		return ret
	}

	return o.Phones
}

// GetPhonesOk returns a tuple with the Phones field value
// and a boolean to check if the value has been set.
func (o *StoplistAddRequest) GetPhonesOk() ([]int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Phones, true
}

// SetPhones sets field value
func (o *StoplistAddRequest) SetPhones(v []int32) {
	o.Phones = v
}

// GetTypes returns the Types field value
func (o *StoplistAddRequest) GetTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Types
}

// GetTypesOk returns a tuple with the Types field value
// and a boolean to check if the value has been set.
func (o *StoplistAddRequest) GetTypesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Types, true
}

// SetTypes sets field value
func (o *StoplistAddRequest) SetTypes(v []string) {
	o.Types = v
}

func (o StoplistAddRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoplistAddRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["phones"] = o.Phones
	toSerialize["types"] = o.Types
	return toSerialize, nil
}

func (o *StoplistAddRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"phones",
		"types",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStoplistAddRequest := _StoplistAddRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStoplistAddRequest)

	if err != nil {
		return err
	}

	*o = StoplistAddRequest(varStoplistAddRequest)

	return err
}

type NullableStoplistAddRequest struct {
	value *StoplistAddRequest
	isSet bool
}

func (v NullableStoplistAddRequest) Get() *StoplistAddRequest {
	return v.value
}

func (v *NullableStoplistAddRequest) Set(val *StoplistAddRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableStoplistAddRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableStoplistAddRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoplistAddRequest(val *StoplistAddRequest) *NullableStoplistAddRequest {
	return &NullableStoplistAddRequest{value: val, isSet: true}
}

func (v NullableStoplistAddRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoplistAddRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


