/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
	"time"
)

// checks if the RcsClickCallback type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RcsClickCallback{}

// RcsClickCallback RCS click callback object
type RcsClickCallback struct {
	// Message ID – a unique identifier automatically generated on the Platform when the message is created
	Id *int32 `json:"id,omitempty"`
	// external unique ID. String up to 32 characters containing only alpha numeric characters.  **Please note:** messages with duplicate reference_id will be rejected
	Reference *string `json:"reference,omitempty"`
	// Phone number
	Msisdn *string `json:"msisdn,omitempty"`
	// Text on clicked button from suggestions
	Text *string `json:"text,omitempty"`
	// postback_data field value from suggestion button object
	Postback *string `json:"postback,omitempty"`
	// Date when the item was created in the system ― set by the system automatically. Display format ― Y-m-d H:i:s
	TimeClick *time.Time `json:"time_click,omitempty"`
}

// NewRcsClickCallback instantiates a new RcsClickCallback object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRcsClickCallback() *RcsClickCallback {
	this := RcsClickCallback{}
	return &this
}

// NewRcsClickCallbackWithDefaults instantiates a new RcsClickCallback object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRcsClickCallbackWithDefaults() *RcsClickCallback {
	this := RcsClickCallback{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RcsClickCallback) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RcsClickCallback) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RcsClickCallback) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *RcsClickCallback) SetId(v int32) {
	o.Id = &v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *RcsClickCallback) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RcsClickCallback) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *RcsClickCallback) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *RcsClickCallback) SetReference(v string) {
	o.Reference = &v
}

// GetMsisdn returns the Msisdn field value if set, zero value otherwise.
func (o *RcsClickCallback) GetMsisdn() string {
	if o == nil || IsNil(o.Msisdn) {
		var ret string
		return ret
	}
	return *o.Msisdn
}

// GetMsisdnOk returns a tuple with the Msisdn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RcsClickCallback) GetMsisdnOk() (*string, bool) {
	if o == nil || IsNil(o.Msisdn) {
		return nil, false
	}
	return o.Msisdn, true
}

// HasMsisdn returns a boolean if a field has been set.
func (o *RcsClickCallback) HasMsisdn() bool {
	if o != nil && !IsNil(o.Msisdn) {
		return true
	}

	return false
}

// SetMsisdn gets a reference to the given string and assigns it to the Msisdn field.
func (o *RcsClickCallback) SetMsisdn(v string) {
	o.Msisdn = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *RcsClickCallback) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RcsClickCallback) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *RcsClickCallback) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *RcsClickCallback) SetText(v string) {
	o.Text = &v
}

// GetPostback returns the Postback field value if set, zero value otherwise.
func (o *RcsClickCallback) GetPostback() string {
	if o == nil || IsNil(o.Postback) {
		var ret string
		return ret
	}
	return *o.Postback
}

// GetPostbackOk returns a tuple with the Postback field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RcsClickCallback) GetPostbackOk() (*string, bool) {
	if o == nil || IsNil(o.Postback) {
		return nil, false
	}
	return o.Postback, true
}

// HasPostback returns a boolean if a field has been set.
func (o *RcsClickCallback) HasPostback() bool {
	if o != nil && !IsNil(o.Postback) {
		return true
	}

	return false
}

// SetPostback gets a reference to the given string and assigns it to the Postback field.
func (o *RcsClickCallback) SetPostback(v string) {
	o.Postback = &v
}

// GetTimeClick returns the TimeClick field value if set, zero value otherwise.
func (o *RcsClickCallback) GetTimeClick() time.Time {
	if o == nil || IsNil(o.TimeClick) {
		var ret time.Time
		return ret
	}
	return *o.TimeClick
}

// GetTimeClickOk returns a tuple with the TimeClick field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RcsClickCallback) GetTimeClickOk() (*time.Time, bool) {
	if o == nil || IsNil(o.TimeClick) {
		return nil, false
	}
	return o.TimeClick, true
}

// HasTimeClick returns a boolean if a field has been set.
func (o *RcsClickCallback) HasTimeClick() bool {
	if o != nil && !IsNil(o.TimeClick) {
		return true
	}

	return false
}

// SetTimeClick gets a reference to the given time.Time and assigns it to the TimeClick field.
func (o *RcsClickCallback) SetTimeClick(v time.Time) {
	o.TimeClick = &v
}

func (o RcsClickCallback) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RcsClickCallback) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	if !IsNil(o.Msisdn) {
		toSerialize["msisdn"] = o.Msisdn
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.Postback) {
		toSerialize["postback"] = o.Postback
	}
	if !IsNil(o.TimeClick) {
		toSerialize["time_click"] = o.TimeClick
	}
	return toSerialize, nil
}

type NullableRcsClickCallback struct {
	value *RcsClickCallback
	isSet bool
}

func (v NullableRcsClickCallback) Get() *RcsClickCallback {
	return v.value
}

func (v *NullableRcsClickCallback) Set(val *RcsClickCallback) {
	v.value = val
	v.isSet = true
}

func (v NullableRcsClickCallback) IsSet() bool {
	return v.isSet
}

func (v *NullableRcsClickCallback) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRcsClickCallback(val *RcsClickCallback) *NullableRcsClickCallback {
	return &NullableRcsClickCallback{value: val, isSet: true}
}

func (v NullableRcsClickCallback) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRcsClickCallback) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


