/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
)

// checks if the Senders200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Senders200Response{}

// Senders200Response struct for Senders200Response
type Senders200Response struct {
	Data []SenderSchema `json:"data,omitempty"`
	// Total items count at all of the pages
	Total *int32 `json:"total,omitempty"`
}

// NewSenders200Response instantiates a new Senders200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSenders200Response() *Senders200Response {
	this := Senders200Response{}
	return &this
}

// NewSenders200ResponseWithDefaults instantiates a new Senders200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSenders200ResponseWithDefaults() *Senders200Response {
	this := Senders200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *Senders200Response) GetData() []SenderSchema {
	if o == nil || IsNil(o.Data) {
		var ret []SenderSchema
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Senders200Response) GetDataOk() ([]SenderSchema, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *Senders200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []SenderSchema and assigns it to the Data field.
func (o *Senders200Response) SetData(v []SenderSchema) {
	o.Data = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *Senders200Response) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Senders200Response) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *Senders200Response) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *Senders200Response) SetTotal(v int32) {
	o.Total = &v
}

func (o Senders200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Senders200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableSenders200Response struct {
	value *Senders200Response
	isSet bool
}

func (v NullableSenders200Response) Get() *Senders200Response {
	return v.value
}

func (v *NullableSenders200Response) Set(val *Senders200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableSenders200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableSenders200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSenders200Response(val *Senders200Response) *NullableSenders200Response {
	return &NullableSenders200Response{value: val, isSet: true}
}

func (v NullableSenders200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSenders200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


