/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IndividualMessageData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndividualMessageData{}

// IndividualMessageData struct for IndividualMessageData
type IndividualMessageData struct {
	// Phone number without leading plus, just digits
	Phone int32 `json:"phone"`
	// SMS text, max length is 765 chars for GSM 7-bit encoding (Latin), and 355 for UCS-2
	Text string `json:"text"`
	// Sender’s name: from 3 to 11 characters for the sender’s alphanumeric name (Latin letters, symbols, numbers, spaces); 3 to 15 characters for the sender’s numeric name. To setup senders visit the [account](https://app.bsg.world/sms/senders)
	Sender string `json:"sender"`
	// Tariff code null by default. Your can pass specified one if you have several. For more information please visit the [account prices](https://app.bsg.world/prices/sms)
	TariffCode *int32 `json:"tariff_code,omitempty"`
	// external unique ID. String up to 32 characters containing only alpha numeric characters.  **Please note:** messages with duplicate reference_id will be rejected
	ReferenceId *string `json:"reference_id,omitempty"`
	// apply transliteration to sms text if it necessary
	Transliterate *bool `json:"transliterate,omitempty"`
}

type _IndividualMessageData IndividualMessageData

// NewIndividualMessageData instantiates a new IndividualMessageData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndividualMessageData(phone int32, text string, sender string) *IndividualMessageData {
	this := IndividualMessageData{}
	this.Phone = phone
	this.Text = text
	this.Sender = sender
	var transliterate bool = false
	this.Transliterate = &transliterate
	return &this
}

// NewIndividualMessageDataWithDefaults instantiates a new IndividualMessageData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndividualMessageDataWithDefaults() *IndividualMessageData {
	this := IndividualMessageData{}
	var transliterate bool = false
	this.Transliterate = &transliterate
	return &this
}

// GetPhone returns the Phone field value
func (o *IndividualMessageData) GetPhone() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value
// and a boolean to check if the value has been set.
func (o *IndividualMessageData) GetPhoneOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Phone, true
}

// SetPhone sets field value
func (o *IndividualMessageData) SetPhone(v int32) {
	o.Phone = v
}

// GetText returns the Text field value
func (o *IndividualMessageData) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *IndividualMessageData) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *IndividualMessageData) SetText(v string) {
	o.Text = v
}

// GetSender returns the Sender field value
func (o *IndividualMessageData) GetSender() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sender
}

// GetSenderOk returns a tuple with the Sender field value
// and a boolean to check if the value has been set.
func (o *IndividualMessageData) GetSenderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sender, true
}

// SetSender sets field value
func (o *IndividualMessageData) SetSender(v string) {
	o.Sender = v
}

// GetTariffCode returns the TariffCode field value if set, zero value otherwise.
func (o *IndividualMessageData) GetTariffCode() int32 {
	if o == nil || IsNil(o.TariffCode) {
		var ret int32
		return ret
	}
	return *o.TariffCode
}

// GetTariffCodeOk returns a tuple with the TariffCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndividualMessageData) GetTariffCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.TariffCode) {
		return nil, false
	}
	return o.TariffCode, true
}

// HasTariffCode returns a boolean if a field has been set.
func (o *IndividualMessageData) HasTariffCode() bool {
	if o != nil && !IsNil(o.TariffCode) {
		return true
	}

	return false
}

// SetTariffCode gets a reference to the given int32 and assigns it to the TariffCode field.
func (o *IndividualMessageData) SetTariffCode(v int32) {
	o.TariffCode = &v
}

// GetReferenceId returns the ReferenceId field value if set, zero value otherwise.
func (o *IndividualMessageData) GetReferenceId() string {
	if o == nil || IsNil(o.ReferenceId) {
		var ret string
		return ret
	}
	return *o.ReferenceId
}

// GetReferenceIdOk returns a tuple with the ReferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndividualMessageData) GetReferenceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ReferenceId) {
		return nil, false
	}
	return o.ReferenceId, true
}

// HasReferenceId returns a boolean if a field has been set.
func (o *IndividualMessageData) HasReferenceId() bool {
	if o != nil && !IsNil(o.ReferenceId) {
		return true
	}

	return false
}

// SetReferenceId gets a reference to the given string and assigns it to the ReferenceId field.
func (o *IndividualMessageData) SetReferenceId(v string) {
	o.ReferenceId = &v
}

// GetTransliterate returns the Transliterate field value if set, zero value otherwise.
func (o *IndividualMessageData) GetTransliterate() bool {
	if o == nil || IsNil(o.Transliterate) {
		var ret bool
		return ret
	}
	return *o.Transliterate
}

// GetTransliterateOk returns a tuple with the Transliterate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndividualMessageData) GetTransliterateOk() (*bool, bool) {
	if o == nil || IsNil(o.Transliterate) {
		return nil, false
	}
	return o.Transliterate, true
}

// HasTransliterate returns a boolean if a field has been set.
func (o *IndividualMessageData) HasTransliterate() bool {
	if o != nil && !IsNil(o.Transliterate) {
		return true
	}

	return false
}

// SetTransliterate gets a reference to the given bool and assigns it to the Transliterate field.
func (o *IndividualMessageData) SetTransliterate(v bool) {
	o.Transliterate = &v
}

func (o IndividualMessageData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndividualMessageData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["phone"] = o.Phone
	toSerialize["text"] = o.Text
	toSerialize["sender"] = o.Sender
	if !IsNil(o.TariffCode) {
		toSerialize["tariff_code"] = o.TariffCode
	}
	if !IsNil(o.ReferenceId) {
		toSerialize["reference_id"] = o.ReferenceId
	}
	if !IsNil(o.Transliterate) {
		toSerialize["transliterate"] = o.Transliterate
	}
	return toSerialize, nil
}

func (o *IndividualMessageData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"phone",
		"text",
		"sender",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIndividualMessageData := _IndividualMessageData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIndividualMessageData)

	if err != nil {
		return err
	}

	*o = IndividualMessageData(varIndividualMessageData)

	return err
}

type NullableIndividualMessageData struct {
	value *IndividualMessageData
	isSet bool
}

func (v NullableIndividualMessageData) Get() *IndividualMessageData {
	return v.value
}

func (v *NullableIndividualMessageData) Set(val *IndividualMessageData) {
	v.value = val
	v.isSet = true
}

func (v NullableIndividualMessageData) IsSet() bool {
	return v.isSet
}

func (v *NullableIndividualMessageData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndividualMessageData(val *IndividualMessageData) *NullableIndividualMessageData {
	return &NullableIndividualMessageData{value: val, isSet: true}
}

func (v NullableIndividualMessageData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndividualMessageData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


