/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetInternalCorePricesByCountryCode200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetInternalCorePricesByCountryCode200Response{}

// GetInternalCorePricesByCountryCode200Response struct for GetInternalCorePricesByCountryCode200Response
type GetInternalCorePricesByCountryCode200Response struct {
	Data CorePriceSchema `json:"data"`
}

type _GetInternalCorePricesByCountryCode200Response GetInternalCorePricesByCountryCode200Response

// NewGetInternalCorePricesByCountryCode200Response instantiates a new GetInternalCorePricesByCountryCode200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetInternalCorePricesByCountryCode200Response(data CorePriceSchema) *GetInternalCorePricesByCountryCode200Response {
	this := GetInternalCorePricesByCountryCode200Response{}
	this.Data = data
	return &this
}

// NewGetInternalCorePricesByCountryCode200ResponseWithDefaults instantiates a new GetInternalCorePricesByCountryCode200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetInternalCorePricesByCountryCode200ResponseWithDefaults() *GetInternalCorePricesByCountryCode200Response {
	this := GetInternalCorePricesByCountryCode200Response{}
	return &this
}

// GetData returns the Data field value
func (o *GetInternalCorePricesByCountryCode200Response) GetData() CorePriceSchema {
	if o == nil {
		var ret CorePriceSchema
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetInternalCorePricesByCountryCode200Response) GetDataOk() (*CorePriceSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetInternalCorePricesByCountryCode200Response) SetData(v CorePriceSchema) {
	o.Data = v
}

func (o GetInternalCorePricesByCountryCode200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetInternalCorePricesByCountryCode200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *GetInternalCorePricesByCountryCode200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetInternalCorePricesByCountryCode200Response := _GetInternalCorePricesByCountryCode200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetInternalCorePricesByCountryCode200Response)

	if err != nil {
		return err
	}

	*o = GetInternalCorePricesByCountryCode200Response(varGetInternalCorePricesByCountryCode200Response)

	return err
}

type NullableGetInternalCorePricesByCountryCode200Response struct {
	value *GetInternalCorePricesByCountryCode200Response
	isSet bool
}

func (v NullableGetInternalCorePricesByCountryCode200Response) Get() *GetInternalCorePricesByCountryCode200Response {
	return v.value
}

func (v *NullableGetInternalCorePricesByCountryCode200Response) Set(val *GetInternalCorePricesByCountryCode200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetInternalCorePricesByCountryCode200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetInternalCorePricesByCountryCode200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetInternalCorePricesByCountryCode200Response(val *GetInternalCorePricesByCountryCode200Response) *NullableGetInternalCorePricesByCountryCode200Response {
	return &NullableGetInternalCorePricesByCountryCode200Response{value: val, isSet: true}
}

func (v NullableGetInternalCorePricesByCountryCode200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetInternalCorePricesByCountryCode200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


