/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LinkStoreRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LinkStoreRequest{}

// LinkStoreRequest struct for LinkStoreRequest
type LinkStoreRequest struct {
	// Domain ID from connected short domains from [account](https://app.bsg.world/url-shortener/domains)  **Please note:** *only domains in **active** status accepted*
	DomainId string `json:"domain_id"`
	// Original link where to short link will redirect
	Link string `json:"link"`
}

type _LinkStoreRequest LinkStoreRequest

// NewLinkStoreRequest instantiates a new LinkStoreRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinkStoreRequest(domainId string, link string) *LinkStoreRequest {
	this := LinkStoreRequest{}
	this.DomainId = domainId
	this.Link = link
	return &this
}

// NewLinkStoreRequestWithDefaults instantiates a new LinkStoreRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinkStoreRequestWithDefaults() *LinkStoreRequest {
	this := LinkStoreRequest{}
	return &this
}

// GetDomainId returns the DomainId field value
func (o *LinkStoreRequest) GetDomainId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DomainId
}

// GetDomainIdOk returns a tuple with the DomainId field value
// and a boolean to check if the value has been set.
func (o *LinkStoreRequest) GetDomainIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DomainId, true
}

// SetDomainId sets field value
func (o *LinkStoreRequest) SetDomainId(v string) {
	o.DomainId = v
}

// GetLink returns the Link field value
func (o *LinkStoreRequest) GetLink() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Link
}

// GetLinkOk returns a tuple with the Link field value
// and a boolean to check if the value has been set.
func (o *LinkStoreRequest) GetLinkOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Link, true
}

// SetLink sets field value
func (o *LinkStoreRequest) SetLink(v string) {
	o.Link = v
}

func (o LinkStoreRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LinkStoreRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["domain_id"] = o.DomainId
	toSerialize["link"] = o.Link
	return toSerialize, nil
}

func (o *LinkStoreRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"domain_id",
		"link",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLinkStoreRequest := _LinkStoreRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLinkStoreRequest)

	if err != nil {
		return err
	}

	*o = LinkStoreRequest(varLinkStoreRequest)

	return err
}

type NullableLinkStoreRequest struct {
	value *LinkStoreRequest
	isSet bool
}

func (v NullableLinkStoreRequest) Get() *LinkStoreRequest {
	return v.value
}

func (v *NullableLinkStoreRequest) Set(val *LinkStoreRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLinkStoreRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLinkStoreRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinkStoreRequest(val *LinkStoreRequest) *NullableLinkStoreRequest {
	return &NullableLinkStoreRequest{value: val, isSet: true}
}

func (v NullableLinkStoreRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinkStoreRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


