/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
)

// checks if the StatisticsShort type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StatisticsShort{}

// StatisticsShort struct for StatisticsShort
type StatisticsShort struct {
	// messages that already delivered
	Delivered *int32 `json:"delivered,omitempty"`
	// messages that already sent
	Sent *int32 `json:"sent,omitempty"`
}

// NewStatisticsShort instantiates a new StatisticsShort object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStatisticsShort() *StatisticsShort {
	this := StatisticsShort{}
	return &this
}

// NewStatisticsShortWithDefaults instantiates a new StatisticsShort object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStatisticsShortWithDefaults() *StatisticsShort {
	this := StatisticsShort{}
	return &this
}

// GetDelivered returns the Delivered field value if set, zero value otherwise.
func (o *StatisticsShort) GetDelivered() int32 {
	if o == nil || IsNil(o.Delivered) {
		var ret int32
		return ret
	}
	return *o.Delivered
}

// GetDeliveredOk returns a tuple with the Delivered field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsShort) GetDeliveredOk() (*int32, bool) {
	if o == nil || IsNil(o.Delivered) {
		return nil, false
	}
	return o.Delivered, true
}

// HasDelivered returns a boolean if a field has been set.
func (o *StatisticsShort) HasDelivered() bool {
	if o != nil && !IsNil(o.Delivered) {
		return true
	}

	return false
}

// SetDelivered gets a reference to the given int32 and assigns it to the Delivered field.
func (o *StatisticsShort) SetDelivered(v int32) {
	o.Delivered = &v
}

// GetSent returns the Sent field value if set, zero value otherwise.
func (o *StatisticsShort) GetSent() int32 {
	if o == nil || IsNil(o.Sent) {
		var ret int32
		return ret
	}
	return *o.Sent
}

// GetSentOk returns a tuple with the Sent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StatisticsShort) GetSentOk() (*int32, bool) {
	if o == nil || IsNil(o.Sent) {
		return nil, false
	}
	return o.Sent, true
}

// HasSent returns a boolean if a field has been set.
func (o *StatisticsShort) HasSent() bool {
	if o != nil && !IsNil(o.Sent) {
		return true
	}

	return false
}

// SetSent gets a reference to the given int32 and assigns it to the Sent field.
func (o *StatisticsShort) SetSent(v int32) {
	o.Sent = &v
}

func (o StatisticsShort) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StatisticsShort) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Delivered) {
		toSerialize["delivered"] = o.Delivered
	}
	if !IsNil(o.Sent) {
		toSerialize["sent"] = o.Sent
	}
	return toSerialize, nil
}

type NullableStatisticsShort struct {
	value *StatisticsShort
	isSet bool
}

func (v NullableStatisticsShort) Get() *StatisticsShort {
	return v.value
}

func (v *NullableStatisticsShort) Set(val *StatisticsShort) {
	v.value = val
	v.isSet = true
}

func (v NullableStatisticsShort) IsSet() bool {
	return v.isSet
}

func (v *NullableStatisticsShort) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStatisticsShort(val *StatisticsShort) *NullableStatisticsShort {
	return &NullableStatisticsShort{value: val, isSet: true}
}

func (v NullableStatisticsShort) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStatisticsShort) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


