/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VerifyOtp200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyOtp200Response{}

// VerifyOtp200Response struct for VerifyOtp200Response
type VerifyOtp200Response struct {
	Data TwoFactorAuthenticationSchema `json:"data"`
}

type _VerifyOtp200Response VerifyOtp200Response

// NewVerifyOtp200Response instantiates a new VerifyOtp200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyOtp200Response(data TwoFactorAuthenticationSchema) *VerifyOtp200Response {
	this := VerifyOtp200Response{}
	this.Data = data
	return &this
}

// NewVerifyOtp200ResponseWithDefaults instantiates a new VerifyOtp200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyOtp200ResponseWithDefaults() *VerifyOtp200Response {
	this := VerifyOtp200Response{}
	return &this
}

// GetData returns the Data field value
func (o *VerifyOtp200Response) GetData() TwoFactorAuthenticationSchema {
	if o == nil {
		var ret TwoFactorAuthenticationSchema
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *VerifyOtp200Response) GetDataOk() (*TwoFactorAuthenticationSchema, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *VerifyOtp200Response) SetData(v TwoFactorAuthenticationSchema) {
	o.Data = v
}

func (o VerifyOtp200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyOtp200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *VerifyOtp200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerifyOtp200Response := _VerifyOtp200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerifyOtp200Response)

	if err != nil {
		return err
	}

	*o = VerifyOtp200Response(varVerifyOtp200Response)

	return err
}

type NullableVerifyOtp200Response struct {
	value *VerifyOtp200Response
	isSet bool
}

func (v NullableVerifyOtp200Response) Get() *VerifyOtp200Response {
	return v.value
}

func (v *NullableVerifyOtp200Response) Set(val *VerifyOtp200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyOtp200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyOtp200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyOtp200Response(val *VerifyOtp200Response) *NullableVerifyOtp200Response {
	return &NullableVerifyOtp200Response{value: val, isSet: true}
}

func (v NullableVerifyOtp200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyOtp200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


