/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
)

// checks if the CorePriceSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CorePriceSchema{}

// CorePriceSchema struct for CorePriceSchema
type CorePriceSchema struct {
	Tariff *int32 `json:"tariff,omitempty"`
	LimitationInfo NullableString `json:"limitation_info,omitempty"`
	CountryId *string `json:"country_id,omitempty"`
	Operators []OperatorSchema `json:"operators,omitempty"`
}

// NewCorePriceSchema instantiates a new CorePriceSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCorePriceSchema() *CorePriceSchema {
	this := CorePriceSchema{}
	return &this
}

// NewCorePriceSchemaWithDefaults instantiates a new CorePriceSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCorePriceSchemaWithDefaults() *CorePriceSchema {
	this := CorePriceSchema{}
	return &this
}

// GetTariff returns the Tariff field value if set, zero value otherwise.
func (o *CorePriceSchema) GetTariff() int32 {
	if o == nil || IsNil(o.Tariff) {
		var ret int32
		return ret
	}
	return *o.Tariff
}

// GetTariffOk returns a tuple with the Tariff field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorePriceSchema) GetTariffOk() (*int32, bool) {
	if o == nil || IsNil(o.Tariff) {
		return nil, false
	}
	return o.Tariff, true
}

// HasTariff returns a boolean if a field has been set.
func (o *CorePriceSchema) HasTariff() bool {
	if o != nil && !IsNil(o.Tariff) {
		return true
	}

	return false
}

// SetTariff gets a reference to the given int32 and assigns it to the Tariff field.
func (o *CorePriceSchema) SetTariff(v int32) {
	o.Tariff = &v
}

// GetLimitationInfo returns the LimitationInfo field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CorePriceSchema) GetLimitationInfo() string {
	if o == nil || IsNil(o.LimitationInfo.Get()) {
		var ret string
		return ret
	}
	return *o.LimitationInfo.Get()
}

// GetLimitationInfoOk returns a tuple with the LimitationInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CorePriceSchema) GetLimitationInfoOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LimitationInfo.Get(), o.LimitationInfo.IsSet()
}

// HasLimitationInfo returns a boolean if a field has been set.
func (o *CorePriceSchema) HasLimitationInfo() bool {
	if o != nil && o.LimitationInfo.IsSet() {
		return true
	}

	return false
}

// SetLimitationInfo gets a reference to the given NullableString and assigns it to the LimitationInfo field.
func (o *CorePriceSchema) SetLimitationInfo(v string) {
	o.LimitationInfo.Set(&v)
}
// SetLimitationInfoNil sets the value for LimitationInfo to be an explicit nil
func (o *CorePriceSchema) SetLimitationInfoNil() {
	o.LimitationInfo.Set(nil)
}

// UnsetLimitationInfo ensures that no value is present for LimitationInfo, not even an explicit nil
func (o *CorePriceSchema) UnsetLimitationInfo() {
	o.LimitationInfo.Unset()
}

// GetCountryId returns the CountryId field value if set, zero value otherwise.
func (o *CorePriceSchema) GetCountryId() string {
	if o == nil || IsNil(o.CountryId) {
		var ret string
		return ret
	}
	return *o.CountryId
}

// GetCountryIdOk returns a tuple with the CountryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorePriceSchema) GetCountryIdOk() (*string, bool) {
	if o == nil || IsNil(o.CountryId) {
		return nil, false
	}
	return o.CountryId, true
}

// HasCountryId returns a boolean if a field has been set.
func (o *CorePriceSchema) HasCountryId() bool {
	if o != nil && !IsNil(o.CountryId) {
		return true
	}

	return false
}

// SetCountryId gets a reference to the given string and assigns it to the CountryId field.
func (o *CorePriceSchema) SetCountryId(v string) {
	o.CountryId = &v
}

// GetOperators returns the Operators field value if set, zero value otherwise.
func (o *CorePriceSchema) GetOperators() []OperatorSchema {
	if o == nil || IsNil(o.Operators) {
		var ret []OperatorSchema
		return ret
	}
	return o.Operators
}

// GetOperatorsOk returns a tuple with the Operators field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CorePriceSchema) GetOperatorsOk() ([]OperatorSchema, bool) {
	if o == nil || IsNil(o.Operators) {
		return nil, false
	}
	return o.Operators, true
}

// HasOperators returns a boolean if a field has been set.
func (o *CorePriceSchema) HasOperators() bool {
	if o != nil && !IsNil(o.Operators) {
		return true
	}

	return false
}

// SetOperators gets a reference to the given []OperatorSchema and assigns it to the Operators field.
func (o *CorePriceSchema) SetOperators(v []OperatorSchema) {
	o.Operators = v
}

func (o CorePriceSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CorePriceSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tariff) {
		toSerialize["tariff"] = o.Tariff
	}
	if o.LimitationInfo.IsSet() {
		toSerialize["limitation_info"] = o.LimitationInfo.Get()
	}
	if !IsNil(o.CountryId) {
		toSerialize["country_id"] = o.CountryId
	}
	if !IsNil(o.Operators) {
		toSerialize["operators"] = o.Operators
	}
	return toSerialize, nil
}

type NullableCorePriceSchema struct {
	value *CorePriceSchema
	isSet bool
}

func (v NullableCorePriceSchema) Get() *CorePriceSchema {
	return v.value
}

func (v *NullableCorePriceSchema) Set(val *CorePriceSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableCorePriceSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableCorePriceSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCorePriceSchema(val *CorePriceSchema) *NullableCorePriceSchema {
	return &NullableCorePriceSchema{value: val, isSet: true}
}

func (v NullableCorePriceSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCorePriceSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


