/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ContactListCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContactListCreateRequest{}

// ContactListCreateRequest struct for ContactListCreateRequest
type ContactListCreateRequest struct {
	// Name of the contact list
	Name string `json:"name"`
	// Description of the contact list
	Description NullableString `json:"description,omitempty"`
	// Specifies whether the contact list is a default one
	Default NullableBool `json:"default,omitempty"`
}

type _ContactListCreateRequest ContactListCreateRequest

// NewContactListCreateRequest instantiates a new ContactListCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContactListCreateRequest(name string) *ContactListCreateRequest {
	this := ContactListCreateRequest{}
	this.Name = name
	var default_ bool = false
	this.Default = *NewNullableBool(&default_)
	return &this
}

// NewContactListCreateRequestWithDefaults instantiates a new ContactListCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContactListCreateRequestWithDefaults() *ContactListCreateRequest {
	this := ContactListCreateRequest{}
	var default_ bool = false
	this.Default = *NewNullableBool(&default_)
	return &this
}

// GetName returns the Name field value
func (o *ContactListCreateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ContactListCreateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ContactListCreateRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ContactListCreateRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContactListCreateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *ContactListCreateRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *ContactListCreateRequest) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *ContactListCreateRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *ContactListCreateRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetDefault returns the Default field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ContactListCreateRequest) GetDefault() bool {
	if o == nil || IsNil(o.Default.Get()) {
		var ret bool
		return ret
	}
	return *o.Default.Get()
}

// GetDefaultOk returns a tuple with the Default field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContactListCreateRequest) GetDefaultOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Default.Get(), o.Default.IsSet()
}

// HasDefault returns a boolean if a field has been set.
func (o *ContactListCreateRequest) HasDefault() bool {
	if o != nil && o.Default.IsSet() {
		return true
	}

	return false
}

// SetDefault gets a reference to the given NullableBool and assigns it to the Default field.
func (o *ContactListCreateRequest) SetDefault(v bool) {
	o.Default.Set(&v)
}
// SetDefaultNil sets the value for Default to be an explicit nil
func (o *ContactListCreateRequest) SetDefaultNil() {
	o.Default.Set(nil)
}

// UnsetDefault ensures that no value is present for Default, not even an explicit nil
func (o *ContactListCreateRequest) UnsetDefault() {
	o.Default.Unset()
}

func (o ContactListCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContactListCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Default.IsSet() {
		toSerialize["default"] = o.Default.Get()
	}
	return toSerialize, nil
}

func (o *ContactListCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContactListCreateRequest := _ContactListCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContactListCreateRequest)

	if err != nil {
		return err
	}

	*o = ContactListCreateRequest(varContactListCreateRequest)

	return err
}

type NullableContactListCreateRequest struct {
	value *ContactListCreateRequest
	isSet bool
}

func (v NullableContactListCreateRequest) Get() *ContactListCreateRequest {
	return v.value
}

func (v *NullableContactListCreateRequest) Set(val *ContactListCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableContactListCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableContactListCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContactListCreateRequest(val *ContactListCreateRequest) *NullableContactListCreateRequest {
	return &NullableContactListCreateRequest{value: val, isSet: true}
}

func (v NullableContactListCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContactListCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


