/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
)

// checks if the DetailCampaignSchemaAlternativeChannels type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DetailCampaignSchemaAlternativeChannels{}

// DetailCampaignSchemaAlternativeChannels struct for DetailCampaignSchemaAlternativeChannels
type DetailCampaignSchemaAlternativeChannels struct {
	Sms *DetailCampaignSchemaAlternativeChannelsStatistics `json:"sms,omitempty"`
}

// NewDetailCampaignSchemaAlternativeChannels instantiates a new DetailCampaignSchemaAlternativeChannels object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDetailCampaignSchemaAlternativeChannels() *DetailCampaignSchemaAlternativeChannels {
	this := DetailCampaignSchemaAlternativeChannels{}
	return &this
}

// NewDetailCampaignSchemaAlternativeChannelsWithDefaults instantiates a new DetailCampaignSchemaAlternativeChannels object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDetailCampaignSchemaAlternativeChannelsWithDefaults() *DetailCampaignSchemaAlternativeChannels {
	this := DetailCampaignSchemaAlternativeChannels{}
	return &this
}

// GetSms returns the Sms field value if set, zero value otherwise.
func (o *DetailCampaignSchemaAlternativeChannels) GetSms() DetailCampaignSchemaAlternativeChannelsStatistics {
	if o == nil || IsNil(o.Sms) {
		var ret DetailCampaignSchemaAlternativeChannelsStatistics
		return ret
	}
	return *o.Sms
}

// GetSmsOk returns a tuple with the Sms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetailCampaignSchemaAlternativeChannels) GetSmsOk() (*DetailCampaignSchemaAlternativeChannelsStatistics, bool) {
	if o == nil || IsNil(o.Sms) {
		return nil, false
	}
	return o.Sms, true
}

// HasSms returns a boolean if a field has been set.
func (o *DetailCampaignSchemaAlternativeChannels) HasSms() bool {
	if o != nil && !IsNil(o.Sms) {
		return true
	}

	return false
}

// SetSms gets a reference to the given DetailCampaignSchemaAlternativeChannelsStatistics and assigns it to the Sms field.
func (o *DetailCampaignSchemaAlternativeChannels) SetSms(v DetailCampaignSchemaAlternativeChannelsStatistics) {
	o.Sms = &v
}

func (o DetailCampaignSchemaAlternativeChannels) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DetailCampaignSchemaAlternativeChannels) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Sms) {
		toSerialize["sms"] = o.Sms
	}
	return toSerialize, nil
}

type NullableDetailCampaignSchemaAlternativeChannels struct {
	value *DetailCampaignSchemaAlternativeChannels
	isSet bool
}

func (v NullableDetailCampaignSchemaAlternativeChannels) Get() *DetailCampaignSchemaAlternativeChannels {
	return v.value
}

func (v *NullableDetailCampaignSchemaAlternativeChannels) Set(val *DetailCampaignSchemaAlternativeChannels) {
	v.value = val
	v.isSet = true
}

func (v NullableDetailCampaignSchemaAlternativeChannels) IsSet() bool {
	return v.isSet
}

func (v *NullableDetailCampaignSchemaAlternativeChannels) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDetailCampaignSchemaAlternativeChannels(val *DetailCampaignSchemaAlternativeChannels) *NullableDetailCampaignSchemaAlternativeChannels {
	return &NullableDetailCampaignSchemaAlternativeChannels{value: val, isSet: true}
}

func (v NullableDetailCampaignSchemaAlternativeChannels) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDetailCampaignSchemaAlternativeChannels) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


