/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
)

// checks if the AccountTariffs200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountTariffs200Response{}

// AccountTariffs200Response struct for AccountTariffs200Response
type AccountTariffs200Response struct {
	Data []TariffSchema `json:"data,omitempty"`
	// Total items count at all of the pages
	Total *int32 `json:"total,omitempty"`
}

// NewAccountTariffs200Response instantiates a new AccountTariffs200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountTariffs200Response() *AccountTariffs200Response {
	this := AccountTariffs200Response{}
	return &this
}

// NewAccountTariffs200ResponseWithDefaults instantiates a new AccountTariffs200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountTariffs200ResponseWithDefaults() *AccountTariffs200Response {
	this := AccountTariffs200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AccountTariffs200Response) GetData() []TariffSchema {
	if o == nil || IsNil(o.Data) {
		var ret []TariffSchema
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTariffs200Response) GetDataOk() ([]TariffSchema, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AccountTariffs200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []TariffSchema and assigns it to the Data field.
func (o *AccountTariffs200Response) SetData(v []TariffSchema) {
	o.Data = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *AccountTariffs200Response) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountTariffs200Response) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *AccountTariffs200Response) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *AccountTariffs200Response) SetTotal(v int32) {
	o.Total = &v
}

func (o AccountTariffs200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountTariffs200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableAccountTariffs200Response struct {
	value *AccountTariffs200Response
	isSet bool
}

func (v NullableAccountTariffs200Response) Get() *AccountTariffs200Response {
	return v.value
}

func (v *NullableAccountTariffs200Response) Set(val *AccountTariffs200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountTariffs200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountTariffs200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountTariffs200Response(val *AccountTariffs200Response) *NullableAccountTariffs200Response {
	return &NullableAccountTariffs200Response{value: val, isSet: true}
}

func (v NullableAccountTariffs200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountTariffs200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


