/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
)

// checks if the ContactListCreate201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContactListCreate201Response{}

// ContactListCreate201Response struct for ContactListCreate201Response
type ContactListCreate201Response struct {
	Data *ContactGroupSchema `json:"data,omitempty"`
}

// NewContactListCreate201Response instantiates a new ContactListCreate201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContactListCreate201Response() *ContactListCreate201Response {
	this := ContactListCreate201Response{}
	return &this
}

// NewContactListCreate201ResponseWithDefaults instantiates a new ContactListCreate201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContactListCreate201ResponseWithDefaults() *ContactListCreate201Response {
	this := ContactListCreate201Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ContactListCreate201Response) GetData() ContactGroupSchema {
	if o == nil || IsNil(o.Data) {
		var ret ContactGroupSchema
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactListCreate201Response) GetDataOk() (*ContactGroupSchema, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ContactListCreate201Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ContactGroupSchema and assigns it to the Data field.
func (o *ContactListCreate201Response) SetData(v ContactGroupSchema) {
	o.Data = &v
}

func (o ContactListCreate201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContactListCreate201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableContactListCreate201Response struct {
	value *ContactListCreate201Response
	isSet bool
}

func (v NullableContactListCreate201Response) Get() *ContactListCreate201Response {
	return v.value
}

func (v *NullableContactListCreate201Response) Set(val *ContactListCreate201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableContactListCreate201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableContactListCreate201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContactListCreate201Response(val *ContactListCreate201Response) *NullableContactListCreate201Response {
	return &NullableContactListCreate201Response{value: val, isSet: true}
}

func (v NullableContactListCreate201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContactListCreate201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


