/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SendOtpRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendOtpRequest{}

// SendOtpRequest struct for SendOtpRequest
type SendOtpRequest struct {
	// The phone number of the recipient of the one-time password. 9 to 15 digits without the + sign. 3 to 15 characters for the sender’s numeric name.
	Recipient string `json:"recipient"`
	// A channel for sending a one-time password. Possible values: sms, viber.
	Channel string `json:"channel"`
	// Sender’s name: from 3 to 11 characters for the sender’s alphanumeric name (Latin letters, symbols, numbers, spaces); 3 to 15 characters for the sender’s numeric name. To setup senders visit the [account](https://app.bsg.world/sms/senders)
	Sender string `json:"sender"`
	// Used only for the Viber channel to alternatively send a one-time code in SMS (if it was not possible to send the code in a Viber message, for example, if the recipient is not a Viber user).The name or number of the SMS sender. String up to 15 characters: from 3 to 11 characters for the sender’s alphanumeric name (Latin letters, symbols, numbers, spaces); 3 to 15 characters for the sender’s numeric name.
	SenderAlt NullableString `json:"sender_alt,omitempty"`
	// Unique identifier of the [template](https://app.bsg.world/2fa/templates) with the Approved status. It’s not allowed to specify the template ID in other statuses. The template ID must be from 1 to 9 digits
	TemplateId int32 `json:"template_id"`
	// The password expiration time after which the password becomes invalid. An integer from 30 seconds to 300 seconds.
	CodeLifetime int32 `json:"code_lifetime"`
	// The number of password verification attempts. An integer from 1 to 5.
	CodeMaxTries int32 `json:"code_max_tries"`
	// The length of the numeric code, from 3 to 9 digits.
	CodeDigits int32 `json:"code_digits"`
}

type _SendOtpRequest SendOtpRequest

// NewSendOtpRequest instantiates a new SendOtpRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendOtpRequest(recipient string, channel string, sender string, templateId int32, codeLifetime int32, codeMaxTries int32, codeDigits int32) *SendOtpRequest {
	this := SendOtpRequest{}
	this.Recipient = recipient
	this.Channel = channel
	this.Sender = sender
	this.TemplateId = templateId
	this.CodeLifetime = codeLifetime
	this.CodeMaxTries = codeMaxTries
	this.CodeDigits = codeDigits
	return &this
}

// NewSendOtpRequestWithDefaults instantiates a new SendOtpRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendOtpRequestWithDefaults() *SendOtpRequest {
	this := SendOtpRequest{}
	return &this
}

// GetRecipient returns the Recipient field value
func (o *SendOtpRequest) GetRecipient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value
// and a boolean to check if the value has been set.
func (o *SendOtpRequest) GetRecipientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Recipient, true
}

// SetRecipient sets field value
func (o *SendOtpRequest) SetRecipient(v string) {
	o.Recipient = v
}

// GetChannel returns the Channel field value
func (o *SendOtpRequest) GetChannel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Channel
}

// GetChannelOk returns a tuple with the Channel field value
// and a boolean to check if the value has been set.
func (o *SendOtpRequest) GetChannelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Channel, true
}

// SetChannel sets field value
func (o *SendOtpRequest) SetChannel(v string) {
	o.Channel = v
}

// GetSender returns the Sender field value
func (o *SendOtpRequest) GetSender() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sender
}

// GetSenderOk returns a tuple with the Sender field value
// and a boolean to check if the value has been set.
func (o *SendOtpRequest) GetSenderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sender, true
}

// SetSender sets field value
func (o *SendOtpRequest) SetSender(v string) {
	o.Sender = v
}

// GetSenderAlt returns the SenderAlt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SendOtpRequest) GetSenderAlt() string {
	if o == nil || IsNil(o.SenderAlt.Get()) {
		var ret string
		return ret
	}
	return *o.SenderAlt.Get()
}

// GetSenderAltOk returns a tuple with the SenderAlt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SendOtpRequest) GetSenderAltOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SenderAlt.Get(), o.SenderAlt.IsSet()
}

// HasSenderAlt returns a boolean if a field has been set.
func (o *SendOtpRequest) HasSenderAlt() bool {
	if o != nil && o.SenderAlt.IsSet() {
		return true
	}

	return false
}

// SetSenderAlt gets a reference to the given NullableString and assigns it to the SenderAlt field.
func (o *SendOtpRequest) SetSenderAlt(v string) {
	o.SenderAlt.Set(&v)
}
// SetSenderAltNil sets the value for SenderAlt to be an explicit nil
func (o *SendOtpRequest) SetSenderAltNil() {
	o.SenderAlt.Set(nil)
}

// UnsetSenderAlt ensures that no value is present for SenderAlt, not even an explicit nil
func (o *SendOtpRequest) UnsetSenderAlt() {
	o.SenderAlt.Unset()
}

// GetTemplateId returns the TemplateId field value
func (o *SendOtpRequest) GetTemplateId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value
// and a boolean to check if the value has been set.
func (o *SendOtpRequest) GetTemplateIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateId, true
}

// SetTemplateId sets field value
func (o *SendOtpRequest) SetTemplateId(v int32) {
	o.TemplateId = v
}

// GetCodeLifetime returns the CodeLifetime field value
func (o *SendOtpRequest) GetCodeLifetime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CodeLifetime
}

// GetCodeLifetimeOk returns a tuple with the CodeLifetime field value
// and a boolean to check if the value has been set.
func (o *SendOtpRequest) GetCodeLifetimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CodeLifetime, true
}

// SetCodeLifetime sets field value
func (o *SendOtpRequest) SetCodeLifetime(v int32) {
	o.CodeLifetime = v
}

// GetCodeMaxTries returns the CodeMaxTries field value
func (o *SendOtpRequest) GetCodeMaxTries() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CodeMaxTries
}

// GetCodeMaxTriesOk returns a tuple with the CodeMaxTries field value
// and a boolean to check if the value has been set.
func (o *SendOtpRequest) GetCodeMaxTriesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CodeMaxTries, true
}

// SetCodeMaxTries sets field value
func (o *SendOtpRequest) SetCodeMaxTries(v int32) {
	o.CodeMaxTries = v
}

// GetCodeDigits returns the CodeDigits field value
func (o *SendOtpRequest) GetCodeDigits() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CodeDigits
}

// GetCodeDigitsOk returns a tuple with the CodeDigits field value
// and a boolean to check if the value has been set.
func (o *SendOtpRequest) GetCodeDigitsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CodeDigits, true
}

// SetCodeDigits sets field value
func (o *SendOtpRequest) SetCodeDigits(v int32) {
	o.CodeDigits = v
}

func (o SendOtpRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendOtpRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["recipient"] = o.Recipient
	toSerialize["channel"] = o.Channel
	toSerialize["sender"] = o.Sender
	if o.SenderAlt.IsSet() {
		toSerialize["sender_alt"] = o.SenderAlt.Get()
	}
	toSerialize["template_id"] = o.TemplateId
	toSerialize["code_lifetime"] = o.CodeLifetime
	toSerialize["code_max_tries"] = o.CodeMaxTries
	toSerialize["code_digits"] = o.CodeDigits
	return toSerialize, nil
}

func (o *SendOtpRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"recipient",
		"channel",
		"sender",
		"template_id",
		"code_lifetime",
		"code_max_tries",
		"code_digits",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSendOtpRequest := _SendOtpRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSendOtpRequest)

	if err != nil {
		return err
	}

	*o = SendOtpRequest(varSendOtpRequest)

	return err
}

type NullableSendOtpRequest struct {
	value *SendOtpRequest
	isSet bool
}

func (v NullableSendOtpRequest) Get() *SendOtpRequest {
	return v.value
}

func (v *NullableSendOtpRequest) Set(val *SendOtpRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSendOtpRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSendOtpRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendOtpRequest(val *SendOtpRequest) *NullableSendOtpRequest {
	return &NullableSendOtpRequest{value: val, isSet: true}
}

func (v NullableSendOtpRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendOtpRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


