/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
	"fmt"
)

// OtpChannel Authentication channel selected for sending the one-time code
type OtpChannel string

// List of OtpChannel
const (
	SMS OtpChannel = "sms"
	VIBER OtpChannel = "viber"
)

// All allowed values of OtpChannel enum
var AllowedOtpChannelEnumValues = []OtpChannel{
	"sms",
	"viber",
}

func (v *OtpChannel) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OtpChannel(value)
	for _, existing := range AllowedOtpChannelEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OtpChannel", value)
}

// NewOtpChannelFromValue returns a pointer to a valid OtpChannel
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOtpChannelFromValue(v string) (*OtpChannel, error) {
	ev := OtpChannel(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OtpChannel: valid values are %v", v, AllowedOtpChannelEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OtpChannel) IsValid() bool {
	for _, existing := range AllowedOtpChannelEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OtpChannel value
func (v OtpChannel) Ptr() *OtpChannel {
	return &v
}

type NullableOtpChannel struct {
	value *OtpChannel
	isSet bool
}

func (v NullableOtpChannel) Get() *OtpChannel {
	return v.value
}

func (v *NullableOtpChannel) Set(val *OtpChannel) {
	v.value = val
	v.isSet = true
}

func (v NullableOtpChannel) IsSet() bool {
	return v.isSet
}

func (v *NullableOtpChannel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOtpChannel(val *OtpChannel) *NullableOtpChannel {
	return &NullableOtpChannel{value: val, isSet: true}
}

func (v NullableOtpChannel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOtpChannel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

