/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SenderRequestNaturalRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SenderRequestNaturalRequest{}

// SenderRequestNaturalRequest struct for SenderRequestNaturalRequest
type SenderRequestNaturalRequest struct {
	// Country code according to ISO 3166-1 alpha-2 standard
	CountryCode string `json:"country_code"`
	Type SenderRequestType `json:"type"`
	// Sender name.   Up to 11 Latin letters or digits, up to 15 – only digits. To setup senders visit the [account](https://app.bsg.world/sms/senders) or use [sender api](#tag/Senders)
	Sender string `json:"sender"`
	// Last name, first name, and middle name
	Name string `json:"name"`
	// National registration code of Company (ЄДРПОУ for Ukraine)
	CodeOfCompany string `json:"code_of_company"`
	// Service description
	Description string `json:"description"`
	// Purpose of informing
	InformingPurpose string `json:"informing_purpose"`
	// Website URL of your service
	SiteUrl *string `json:"site_url,omitempty"`
	// any additional information
	Comment NullableString `json:"comment,omitempty"`
}

type _SenderRequestNaturalRequest SenderRequestNaturalRequest

// NewSenderRequestNaturalRequest instantiates a new SenderRequestNaturalRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSenderRequestNaturalRequest(countryCode string, type_ SenderRequestType, sender string, name string, codeOfCompany string, description string, informingPurpose string) *SenderRequestNaturalRequest {
	this := SenderRequestNaturalRequest{}
	this.CountryCode = countryCode
	this.Type = type_
	this.Sender = sender
	this.Name = name
	this.CodeOfCompany = codeOfCompany
	this.Description = description
	this.InformingPurpose = informingPurpose
	return &this
}

// NewSenderRequestNaturalRequestWithDefaults instantiates a new SenderRequestNaturalRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSenderRequestNaturalRequestWithDefaults() *SenderRequestNaturalRequest {
	this := SenderRequestNaturalRequest{}
	var type_ SenderRequestType = SMS
	this.Type = type_
	return &this
}

// GetCountryCode returns the CountryCode field value
func (o *SenderRequestNaturalRequest) GetCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
func (o *SenderRequestNaturalRequest) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryCode, true
}

// SetCountryCode sets field value
func (o *SenderRequestNaturalRequest) SetCountryCode(v string) {
	o.CountryCode = v
}

// GetType returns the Type field value
func (o *SenderRequestNaturalRequest) GetType() SenderRequestType {
	if o == nil {
		var ret SenderRequestType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *SenderRequestNaturalRequest) GetTypeOk() (*SenderRequestType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *SenderRequestNaturalRequest) SetType(v SenderRequestType) {
	o.Type = v
}

// GetSender returns the Sender field value
func (o *SenderRequestNaturalRequest) GetSender() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sender
}

// GetSenderOk returns a tuple with the Sender field value
// and a boolean to check if the value has been set.
func (o *SenderRequestNaturalRequest) GetSenderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sender, true
}

// SetSender sets field value
func (o *SenderRequestNaturalRequest) SetSender(v string) {
	o.Sender = v
}

// GetName returns the Name field value
func (o *SenderRequestNaturalRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SenderRequestNaturalRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SenderRequestNaturalRequest) SetName(v string) {
	o.Name = v
}

// GetCodeOfCompany returns the CodeOfCompany field value
func (o *SenderRequestNaturalRequest) GetCodeOfCompany() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CodeOfCompany
}

// GetCodeOfCompanyOk returns a tuple with the CodeOfCompany field value
// and a boolean to check if the value has been set.
func (o *SenderRequestNaturalRequest) GetCodeOfCompanyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CodeOfCompany, true
}

// SetCodeOfCompany sets field value
func (o *SenderRequestNaturalRequest) SetCodeOfCompany(v string) {
	o.CodeOfCompany = v
}

// GetDescription returns the Description field value
func (o *SenderRequestNaturalRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *SenderRequestNaturalRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *SenderRequestNaturalRequest) SetDescription(v string) {
	o.Description = v
}

// GetInformingPurpose returns the InformingPurpose field value
func (o *SenderRequestNaturalRequest) GetInformingPurpose() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InformingPurpose
}

// GetInformingPurposeOk returns a tuple with the InformingPurpose field value
// and a boolean to check if the value has been set.
func (o *SenderRequestNaturalRequest) GetInformingPurposeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InformingPurpose, true
}

// SetInformingPurpose sets field value
func (o *SenderRequestNaturalRequest) SetInformingPurpose(v string) {
	o.InformingPurpose = v
}

// GetSiteUrl returns the SiteUrl field value if set, zero value otherwise.
func (o *SenderRequestNaturalRequest) GetSiteUrl() string {
	if o == nil || IsNil(o.SiteUrl) {
		var ret string
		return ret
	}
	return *o.SiteUrl
}

// GetSiteUrlOk returns a tuple with the SiteUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SenderRequestNaturalRequest) GetSiteUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SiteUrl) {
		return nil, false
	}
	return o.SiteUrl, true
}

// HasSiteUrl returns a boolean if a field has been set.
func (o *SenderRequestNaturalRequest) HasSiteUrl() bool {
	if o != nil && !IsNil(o.SiteUrl) {
		return true
	}

	return false
}

// SetSiteUrl gets a reference to the given string and assigns it to the SiteUrl field.
func (o *SenderRequestNaturalRequest) SetSiteUrl(v string) {
	o.SiteUrl = &v
}

// GetComment returns the Comment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SenderRequestNaturalRequest) GetComment() string {
	if o == nil || IsNil(o.Comment.Get()) {
		var ret string
		return ret
	}
	return *o.Comment.Get()
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SenderRequestNaturalRequest) GetCommentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Comment.Get(), o.Comment.IsSet()
}

// HasComment returns a boolean if a field has been set.
func (o *SenderRequestNaturalRequest) HasComment() bool {
	if o != nil && o.Comment.IsSet() {
		return true
	}

	return false
}

// SetComment gets a reference to the given NullableString and assigns it to the Comment field.
func (o *SenderRequestNaturalRequest) SetComment(v string) {
	o.Comment.Set(&v)
}
// SetCommentNil sets the value for Comment to be an explicit nil
func (o *SenderRequestNaturalRequest) SetCommentNil() {
	o.Comment.Set(nil)
}

// UnsetComment ensures that no value is present for Comment, not even an explicit nil
func (o *SenderRequestNaturalRequest) UnsetComment() {
	o.Comment.Unset()
}

func (o SenderRequestNaturalRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SenderRequestNaturalRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["country_code"] = o.CountryCode
	toSerialize["type"] = o.Type
	toSerialize["sender"] = o.Sender
	toSerialize["name"] = o.Name
	toSerialize["code_of_company"] = o.CodeOfCompany
	toSerialize["description"] = o.Description
	toSerialize["informing_purpose"] = o.InformingPurpose
	if !IsNil(o.SiteUrl) {
		toSerialize["site_url"] = o.SiteUrl
	}
	if o.Comment.IsSet() {
		toSerialize["comment"] = o.Comment.Get()
	}
	return toSerialize, nil
}

func (o *SenderRequestNaturalRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"country_code",
		"type",
		"sender",
		"name",
		"code_of_company",
		"description",
		"informing_purpose",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSenderRequestNaturalRequest := _SenderRequestNaturalRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSenderRequestNaturalRequest)

	if err != nil {
		return err
	}

	*o = SenderRequestNaturalRequest(varSenderRequestNaturalRequest)

	return err
}

type NullableSenderRequestNaturalRequest struct {
	value *SenderRequestNaturalRequest
	isSet bool
}

func (v NullableSenderRequestNaturalRequest) Get() *SenderRequestNaturalRequest {
	return v.value
}

func (v *NullableSenderRequestNaturalRequest) Set(val *SenderRequestNaturalRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSenderRequestNaturalRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSenderRequestNaturalRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSenderRequestNaturalRequest(val *SenderRequestNaturalRequest) *NullableSenderRequestNaturalRequest {
	return &NullableSenderRequestNaturalRequest{value: val, isSet: true}
}

func (v NullableSenderRequestNaturalRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSenderRequestNaturalRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


