/*
One-API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bsgapi

import (
	"encoding/json"
)

// checks if the OperatorSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OperatorSchema{}

// OperatorSchema struct for OperatorSchema
type OperatorSchema struct {
	Id *int32 `json:"id,omitempty"`
	Mcc *int32 `json:"mcc,omitempty"`
	Mnc *int32 `json:"mnc,omitempty"`
	Brand *string `json:"brand,omitempty"`
	Name *string `json:"name,omitempty"`
	Price *float32 `json:"price,omitempty"`
	Currency *string `json:"currency,omitempty"`
	PriceType *string `json:"price_type,omitempty"`
	SenderRegistration *bool `json:"sender_registration,omitempty"`
}

// NewOperatorSchema instantiates a new OperatorSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOperatorSchema() *OperatorSchema {
	this := OperatorSchema{}
	return &this
}

// NewOperatorSchemaWithDefaults instantiates a new OperatorSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOperatorSchemaWithDefaults() *OperatorSchema {
	this := OperatorSchema{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OperatorSchema) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatorSchema) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OperatorSchema) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *OperatorSchema) SetId(v int32) {
	o.Id = &v
}

// GetMcc returns the Mcc field value if set, zero value otherwise.
func (o *OperatorSchema) GetMcc() int32 {
	if o == nil || IsNil(o.Mcc) {
		var ret int32
		return ret
	}
	return *o.Mcc
}

// GetMccOk returns a tuple with the Mcc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatorSchema) GetMccOk() (*int32, bool) {
	if o == nil || IsNil(o.Mcc) {
		return nil, false
	}
	return o.Mcc, true
}

// HasMcc returns a boolean if a field has been set.
func (o *OperatorSchema) HasMcc() bool {
	if o != nil && !IsNil(o.Mcc) {
		return true
	}

	return false
}

// SetMcc gets a reference to the given int32 and assigns it to the Mcc field.
func (o *OperatorSchema) SetMcc(v int32) {
	o.Mcc = &v
}

// GetMnc returns the Mnc field value if set, zero value otherwise.
func (o *OperatorSchema) GetMnc() int32 {
	if o == nil || IsNil(o.Mnc) {
		var ret int32
		return ret
	}
	return *o.Mnc
}

// GetMncOk returns a tuple with the Mnc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatorSchema) GetMncOk() (*int32, bool) {
	if o == nil || IsNil(o.Mnc) {
		return nil, false
	}
	return o.Mnc, true
}

// HasMnc returns a boolean if a field has been set.
func (o *OperatorSchema) HasMnc() bool {
	if o != nil && !IsNil(o.Mnc) {
		return true
	}

	return false
}

// SetMnc gets a reference to the given int32 and assigns it to the Mnc field.
func (o *OperatorSchema) SetMnc(v int32) {
	o.Mnc = &v
}

// GetBrand returns the Brand field value if set, zero value otherwise.
func (o *OperatorSchema) GetBrand() string {
	if o == nil || IsNil(o.Brand) {
		var ret string
		return ret
	}
	return *o.Brand
}

// GetBrandOk returns a tuple with the Brand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatorSchema) GetBrandOk() (*string, bool) {
	if o == nil || IsNil(o.Brand) {
		return nil, false
	}
	return o.Brand, true
}

// HasBrand returns a boolean if a field has been set.
func (o *OperatorSchema) HasBrand() bool {
	if o != nil && !IsNil(o.Brand) {
		return true
	}

	return false
}

// SetBrand gets a reference to the given string and assigns it to the Brand field.
func (o *OperatorSchema) SetBrand(v string) {
	o.Brand = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *OperatorSchema) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatorSchema) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *OperatorSchema) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *OperatorSchema) SetName(v string) {
	o.Name = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *OperatorSchema) GetPrice() float32 {
	if o == nil || IsNil(o.Price) {
		var ret float32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatorSchema) GetPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *OperatorSchema) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float32 and assigns it to the Price field.
func (o *OperatorSchema) SetPrice(v float32) {
	o.Price = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *OperatorSchema) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatorSchema) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *OperatorSchema) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *OperatorSchema) SetCurrency(v string) {
	o.Currency = &v
}

// GetPriceType returns the PriceType field value if set, zero value otherwise.
func (o *OperatorSchema) GetPriceType() string {
	if o == nil || IsNil(o.PriceType) {
		var ret string
		return ret
	}
	return *o.PriceType
}

// GetPriceTypeOk returns a tuple with the PriceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatorSchema) GetPriceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PriceType) {
		return nil, false
	}
	return o.PriceType, true
}

// HasPriceType returns a boolean if a field has been set.
func (o *OperatorSchema) HasPriceType() bool {
	if o != nil && !IsNil(o.PriceType) {
		return true
	}

	return false
}

// SetPriceType gets a reference to the given string and assigns it to the PriceType field.
func (o *OperatorSchema) SetPriceType(v string) {
	o.PriceType = &v
}

// GetSenderRegistration returns the SenderRegistration field value if set, zero value otherwise.
func (o *OperatorSchema) GetSenderRegistration() bool {
	if o == nil || IsNil(o.SenderRegistration) {
		var ret bool
		return ret
	}
	return *o.SenderRegistration
}

// GetSenderRegistrationOk returns a tuple with the SenderRegistration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OperatorSchema) GetSenderRegistrationOk() (*bool, bool) {
	if o == nil || IsNil(o.SenderRegistration) {
		return nil, false
	}
	return o.SenderRegistration, true
}

// HasSenderRegistration returns a boolean if a field has been set.
func (o *OperatorSchema) HasSenderRegistration() bool {
	if o != nil && !IsNil(o.SenderRegistration) {
		return true
	}

	return false
}

// SetSenderRegistration gets a reference to the given bool and assigns it to the SenderRegistration field.
func (o *OperatorSchema) SetSenderRegistration(v bool) {
	o.SenderRegistration = &v
}

func (o OperatorSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OperatorSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Mcc) {
		toSerialize["mcc"] = o.Mcc
	}
	if !IsNil(o.Mnc) {
		toSerialize["mnc"] = o.Mnc
	}
	if !IsNil(o.Brand) {
		toSerialize["brand"] = o.Brand
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.PriceType) {
		toSerialize["price_type"] = o.PriceType
	}
	if !IsNil(o.SenderRegistration) {
		toSerialize["sender_registration"] = o.SenderRegistration
	}
	return toSerialize, nil
}

type NullableOperatorSchema struct {
	value *OperatorSchema
	isSet bool
}

func (v NullableOperatorSchema) Get() *OperatorSchema {
	return v.value
}

func (v *NullableOperatorSchema) Set(val *OperatorSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableOperatorSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableOperatorSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOperatorSchema(val *OperatorSchema) *NullableOperatorSchema {
	return &NullableOperatorSchema{value: val, isSet: true}
}

func (v NullableOperatorSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOperatorSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


